{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c77f8da1-2837-4bf7-b3f4-dfcaa7ab42f6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-09T03:14:13.599342Z",
     "iopub.status.busy": "2023-11-09T03:14:13.599194Z",
     "iopub.status.idle": "2023-11-09T03:14:13.687648Z",
     "shell.execute_reply": "2023-11-09T03:14:13.686999Z"
    }
   },
   "outputs": [],
   "source": [
    "import scipy.io\n",
    "import numpy as np\n",
    "import random\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3fe25376-b856-4296-ba02-5e3771ff9451",
   "metadata": {
    "collapsed": true,
    "execution": {
     "iopub.execute_input": "2023-11-09T03:14:13.689859Z",
     "iopub.status.busy": "2023-11-09T03:14:13.689698Z",
     "iopub.status.idle": "2023-11-09T05:05:31.457264Z",
     "shell.execute_reply": "2023-11-09T05:05:31.456422Z"
    },
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:14:13.867000: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/usr/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1, this may cause problems\n",
      "  _warn((\"h5py is running against HDF5 {0} when it was built against {1}, \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "34841\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "non-resource variables are not supported in the long term\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:15:37.035790: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.047328: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.047554: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.050766: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.050953: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.051120: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.122627: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.122828: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.122996: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:37.123137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:41:00.0, compute capability: 8.6\n",
      "2023-11-08 22:15:37.123599: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:15:38.044625: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:38.044913: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:38.045103: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:38.045315: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:38.045489: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:15:38.045628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:41:00.0, compute capability: 8.6\n",
      "2023-11-08 22:15:38.045659: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n",
      "2023-11-08 22:15:38.068744: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled\n",
      "2023-11-08 22:15:38.285709: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_17/lstm_cell_17/kernel/Assign' id:2821 op device:{requested: '', assigned: ''} def:{{{node lstm_17/lstm_cell_17/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_17/lstm_cell_17/kernel, lstm_17/lstm_cell_17/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:15:38.416466: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_1' id:3634 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_1}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 0 0 0...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:15:38.449445: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_2' id:3635 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_2}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 1 1 1...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "(31351, 95)\n",
      "Train on 31351 samples, validate on 3490 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:15:42.840123: W tensorflow/c/c_api.cc:304] Operation '{name:'training/Adam/lstm_36/lstm_cell_36/recurrent_kernel/v/Assign' id:17582 op device:{requested: '', assigned: ''} def:{{{node training/Adam/lstm_36/lstm_cell_36/recurrent_kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](training/Adam/lstm_36/lstm_cell_36/recurrent_kernel/v, training/Adam/lstm_36/lstm_cell_36/recurrent_kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:15:46.753757: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n",
      "2023-11-08 22:15:48.987370: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "2023-11-08 22:15:48.999369: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8902\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31351/31351 [==============================] - ETA: 0s - loss: 3.4056"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2335: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates = self.state_updates\n",
      "2023-11-08 22:16:08.816287: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_1/mul' id:6477 op device:{requested: '', assigned: ''} def:{{{node loss_1/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_1/mul/x, loss_1/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.89797, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 27s 862us/sample - loss: 3.4056 - val_loss: 1.8980\n",
      "Epoch 2/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.8396\n",
      "Epoch 2: val_loss improved from 1.89797 to 1.61256, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 625us/sample - loss: 1.8396 - val_loss: 1.6126\n",
      "Epoch 3/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.6187\n",
      "Epoch 3: val_loss improved from 1.61256 to 1.51792, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 615us/sample - loss: 1.6187 - val_loss: 1.5179\n",
      "Epoch 4/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5578\n",
      "Epoch 4: val_loss improved from 1.51792 to 1.48239, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 611us/sample - loss: 1.5578 - val_loss: 1.4824\n",
      "Epoch 5/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5299\n",
      "Epoch 5: val_loss improved from 1.48239 to 1.46448, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 612us/sample - loss: 1.5299 - val_loss: 1.4645\n",
      "Epoch 6/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5156\n",
      "Epoch 6: val_loss improved from 1.46448 to 1.45426, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 615us/sample - loss: 1.5156 - val_loss: 1.4543\n",
      "Epoch 7/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5051\n",
      "Epoch 7: val_loss improved from 1.45426 to 1.44657, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 634us/sample - loss: 1.5051 - val_loss: 1.4466\n",
      "Epoch 8/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4975\n",
      "Epoch 8: val_loss improved from 1.44657 to 1.43998, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 717us/sample - loss: 1.4975 - val_loss: 1.4400\n",
      "Epoch 9/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4880\n",
      "Epoch 9: val_loss improved from 1.43998 to 1.43565, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 21s 677us/sample - loss: 1.4880 - val_loss: 1.4356\n",
      "Epoch 10/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4909\n",
      "Epoch 10: val_loss did not improve from 1.43565\n",
      "31351/31351 [==============================] - 19s 616us/sample - loss: 1.4909 - val_loss: 1.4474\n",
      "Epoch 11/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4798\n",
      "Epoch 11: val_loss improved from 1.43565 to 1.42835, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 613us/sample - loss: 1.4798 - val_loss: 1.4284\n",
      "Epoch 12/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5675\n",
      "Epoch 12: val_loss did not improve from 1.42835\n",
      "31351/31351 [==============================] - 19s 608us/sample - loss: 1.5675 - val_loss: 1.4371\n",
      "Epoch 13/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5740\n",
      "Epoch 13: val_loss did not improve from 1.42835\n",
      "31351/31351 [==============================] - 21s 676us/sample - loss: 1.5740 - val_loss: 1.4306\n",
      "Epoch 14/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4961\n",
      "Epoch 14: val_loss improved from 1.42835 to 1.42585, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 643us/sample - loss: 1.4961 - val_loss: 1.4258\n",
      "Epoch 15/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4799\n",
      "Epoch 15: val_loss did not improve from 1.42585\n",
      "31351/31351 [==============================] - 19s 614us/sample - loss: 1.4799 - val_loss: 1.4262\n",
      "Epoch 16/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4793\n",
      "Epoch 16: val_loss improved from 1.42585 to 1.42244, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 613us/sample - loss: 1.4793 - val_loss: 1.4224\n",
      "Epoch 17/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5308\n",
      "Epoch 17: val_loss improved from 1.42244 to 1.42006, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 616us/sample - loss: 1.5308 - val_loss: 1.4201\n",
      "Epoch 18/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.5252\n",
      "Epoch 18: val_loss did not improve from 1.42006\n",
      "31351/31351 [==============================] - 22s 698us/sample - loss: 1.5252 - val_loss: 1.4405\n",
      "Epoch 19/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4954\n",
      "Epoch 19: val_loss did not improve from 1.42006\n",
      "31351/31351 [==============================] - 21s 679us/sample - loss: 1.4954 - val_loss: 1.4328\n",
      "Epoch 20/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4754\n",
      "Epoch 20: val_loss did not improve from 1.42006\n",
      "31351/31351 [==============================] - 20s 646us/sample - loss: 1.4754 - val_loss: 1.4260\n",
      "Epoch 21/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4679\n",
      "Epoch 21: val_loss did not improve from 1.42006\n",
      "31351/31351 [==============================] - 22s 706us/sample - loss: 1.4679 - val_loss: 1.4316\n",
      "Epoch 22/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4664\n",
      "Epoch 22: val_loss did not improve from 1.42006\n",
      "31351/31351 [==============================] - 22s 695us/sample - loss: 1.4664 - val_loss: 1.4204\n",
      "Epoch 23/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4624\n",
      "Epoch 23: val_loss improved from 1.42006 to 1.41799, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 698us/sample - loss: 1.4624 - val_loss: 1.4180\n",
      "Epoch 24/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4597\n",
      "Epoch 24: val_loss did not improve from 1.41799\n",
      "31351/31351 [==============================] - 22s 707us/sample - loss: 1.4597 - val_loss: 1.4190\n",
      "Epoch 25/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4565\n",
      "Epoch 25: val_loss improved from 1.41799 to 1.41438, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 21s 669us/sample - loss: 1.4565 - val_loss: 1.4144\n",
      "Epoch 26/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4486\n",
      "Epoch 26: val_loss improved from 1.41438 to 1.41182, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 625us/sample - loss: 1.4486 - val_loss: 1.4118\n",
      "Epoch 27/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4474\n",
      "Epoch 27: val_loss did not improve from 1.41182\n",
      "31351/31351 [==============================] - 19s 612us/sample - loss: 1.4474 - val_loss: 1.4163\n",
      "Epoch 28/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4449\n",
      "Epoch 28: val_loss did not improve from 1.41182\n",
      "31351/31351 [==============================] - 19s 610us/sample - loss: 1.4449 - val_loss: 1.4142\n",
      "Epoch 29/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4412\n",
      "Epoch 29: val_loss improved from 1.41182 to 1.40760, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 19s 611us/sample - loss: 1.4412 - val_loss: 1.4076\n",
      "Epoch 30/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4420\n",
      "Epoch 30: val_loss did not improve from 1.40760\n",
      "31351/31351 [==============================] - 19s 612us/sample - loss: 1.4420 - val_loss: 1.4113\n",
      "Epoch 31/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4396\n",
      "Epoch 31: val_loss did not improve from 1.40760\n",
      "31351/31351 [==============================] - 19s 611us/sample - loss: 1.4396 - val_loss: 1.4097\n",
      "Epoch 32/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4389\n",
      "Epoch 32: val_loss did not improve from 1.40760\n",
      "31351/31351 [==============================] - 19s 615us/sample - loss: 1.4389 - val_loss: 1.4087\n",
      "Epoch 33/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4378\n",
      "Epoch 33: val_loss did not improve from 1.40760\n",
      "31351/31351 [==============================] - 22s 687us/sample - loss: 1.4378 - val_loss: 1.4082\n",
      "Epoch 34/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4332\n",
      "Epoch 34: val_loss improved from 1.40760 to 1.40517, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 704us/sample - loss: 1.4332 - val_loss: 1.4052\n",
      "Epoch 35/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4321\n",
      "Epoch 35: val_loss improved from 1.40517 to 1.40357, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 708us/sample - loss: 1.4321 - val_loss: 1.4036\n",
      "Epoch 36/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4327\n",
      "Epoch 36: val_loss improved from 1.40357 to 1.40206, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 701us/sample - loss: 1.4327 - val_loss: 1.4021\n",
      "Epoch 37/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4299\n",
      "Epoch 37: val_loss did not improve from 1.40206\n",
      "31351/31351 [==============================] - 22s 703us/sample - loss: 1.4299 - val_loss: 1.4046\n",
      "Epoch 38/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4283\n",
      "Epoch 38: val_loss improved from 1.40206 to 1.40177, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 694us/sample - loss: 1.4283 - val_loss: 1.4018\n",
      "Epoch 39/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4275\n",
      "Epoch 39: val_loss did not improve from 1.40177\n",
      "31351/31351 [==============================] - 22s 691us/sample - loss: 1.4275 - val_loss: 1.4028\n",
      "Epoch 40/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4223\n",
      "Epoch 40: val_loss improved from 1.40177 to 1.40028, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 711us/sample - loss: 1.4223 - val_loss: 1.4003\n",
      "Epoch 41/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4215\n",
      "Epoch 41: val_loss improved from 1.40028 to 1.39963, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 700us/sample - loss: 1.4215 - val_loss: 1.3996\n",
      "Epoch 42/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4219\n",
      "Epoch 42: val_loss improved from 1.39963 to 1.39244, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 21s 677us/sample - loss: 1.4219 - val_loss: 1.3924\n",
      "Epoch 43/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4182\n",
      "Epoch 43: val_loss did not improve from 1.39244\n",
      "31351/31351 [==============================] - 21s 674us/sample - loss: 1.4182 - val_loss: 1.3949\n",
      "Epoch 44/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4171\n",
      "Epoch 44: val_loss did not improve from 1.39244\n",
      "31351/31351 [==============================] - 21s 671us/sample - loss: 1.4171 - val_loss: 1.3940\n",
      "Epoch 45/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4165\n",
      "Epoch 45: val_loss did not improve from 1.39244\n",
      "31351/31351 [==============================] - 21s 668us/sample - loss: 1.4165 - val_loss: 1.3956\n",
      "Epoch 46/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4127\n",
      "Epoch 46: val_loss did not improve from 1.39244\n",
      "31351/31351 [==============================] - 22s 703us/sample - loss: 1.4127 - val_loss: 1.3981\n",
      "Epoch 47/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4141\n",
      "Epoch 47: val_loss did not improve from 1.39244\n",
      "31351/31351 [==============================] - 20s 641us/sample - loss: 1.4141 - val_loss: 1.4008\n",
      "Epoch 48/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4128\n",
      "Epoch 48: val_loss did not improve from 1.39244\n",
      "31351/31351 [==============================] - 20s 626us/sample - loss: 1.4128 - val_loss: 1.3962\n",
      "Epoch 49/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4080\n",
      "Epoch 49: val_loss improved from 1.39244 to 1.39206, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 633us/sample - loss: 1.4080 - val_loss: 1.3921\n",
      "Epoch 50/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4080\n",
      "Epoch 50: val_loss improved from 1.39206 to 1.39105, saving model to ./checkpoints/unknown_person_baseline_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 644us/sample - loss: 1.4080 - val_loss: 1.3910\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:33:02.423926: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_18_1/lstm_cell_55/kernel/Assign' id:21520 op device:{requested: '', assigned: ''} def:{{{node lstm_18_1/lstm_cell_55/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_18_1/lstm_cell_55/kernel, lstm_18_1/lstm_cell_55/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:33:04.115373: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_36_1/lstm_cell_73/bias/v/Assign' id:26445 op device:{requested: '', assigned: ''} def:{{{node lstm_36_1/lstm_cell_73/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_36_1/lstm_cell_73/bias/v, lstm_36_1/lstm_cell_73/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates=self.state_updates,\n",
      "2023-11-08 22:33:05.453676: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_1/cond/Merge' id:24591 op device:{requested: '', assigned: ''} def:{{{node dropout_4_1/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_1/cond/Identity, dropout_4_1/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 2160)\n",
      "(1514, 2160)\n",
      "(1644, 2160)\n",
      "(1764, 2160)\n",
      "(1836, 2160)\n",
      "(1699, 2160)\n",
      "(1369, 2160)\n",
      "(1766, 2160)\n",
      "(1631, 2160)\n",
      "(1692, 2160)\n",
      "(1550, 2160)\n",
      "(1920, 2160)\n",
      "(1739, 2160)\n",
      "(1788, 2160)\n",
      "(1812, 2160)\n",
      "(1788, 2160)\n",
      "(1776, 2160)\n",
      "(922, 2160)\n",
      "(1656, 2160)\n",
      "{1: 5.465799522373249, 2: 1.4964933607997501, 4: 5.105791891650011, 5: 10.0, 6: 9.803390529738625, 8: 5.372833643952966, 9: 1.325991738878535, 10: 7.131789538058625, 11: 3.7087513090772632, 12: 5.158173627215618, 13: 6.518351810883672, 17: 4.912672770721889, 19: 5.552902815046028, 21: 6.553159920175727, 22: 2.647736336530596, 25: 4.2366295519383765, 26: 3.8065658762221326, 27: 1.0, 28: 4.929239565457003}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_2793774/2151781804.py:300: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)\n",
      "  w_train[i] = weights_dict[int(p_train[i])]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31351 samples, validate on 3490 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:37:02.662603: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_5/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31351/31351 [==============================] - ETA: 0s - loss: 7.6206\n",
      "Epoch 1: val_loss improved from inf to 1.40056, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 26s 824us/sample - loss: 7.6206 - val_loss: 1.4006\n",
      "Epoch 2/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.5393\n",
      "Epoch 2: val_loss did not improve from 1.40056\n",
      "31351/31351 [==============================] - 20s 638us/sample - loss: 7.5393 - val_loss: 1.4027\n",
      "Epoch 3/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.5079\n",
      "Epoch 3: val_loss did not improve from 1.40056\n",
      "31351/31351 [==============================] - 22s 692us/sample - loss: 7.5079 - val_loss: 1.4017\n",
      "Epoch 4/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.4861\n",
      "Epoch 4: val_loss improved from 1.40056 to 1.38907, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 23s 718us/sample - loss: 7.4861 - val_loss: 1.3891\n",
      "Epoch 5/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.4384\n",
      "Epoch 5: val_loss did not improve from 1.38907\n",
      "31351/31351 [==============================] - 22s 716us/sample - loss: 7.4384 - val_loss: 1.3970\n",
      "Epoch 6/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.4240\n",
      "Epoch 6: val_loss did not improve from 1.38907\n",
      "31351/31351 [==============================] - 22s 690us/sample - loss: 7.4240 - val_loss: 1.3996\n",
      "Epoch 7/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.4218\n",
      "Epoch 7: val_loss improved from 1.38907 to 1.38820, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 23s 723us/sample - loss: 7.4218 - val_loss: 1.3882\n",
      "Epoch 8/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.4173\n",
      "Epoch 8: val_loss improved from 1.38820 to 1.38315, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 23s 725us/sample - loss: 7.4173 - val_loss: 1.3832\n",
      "Epoch 9/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3995\n",
      "Epoch 9: val_loss did not improve from 1.38315\n",
      "31351/31351 [==============================] - 21s 673us/sample - loss: 7.3995 - val_loss: 1.3932\n",
      "Epoch 10/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3764\n",
      "Epoch 10: val_loss did not improve from 1.38315\n",
      "31351/31351 [==============================] - 20s 635us/sample - loss: 7.3764 - val_loss: 1.3893\n",
      "Epoch 11/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3662\n",
      "Epoch 11: val_loss did not improve from 1.38315\n",
      "31351/31351 [==============================] - 20s 629us/sample - loss: 7.3662 - val_loss: 1.3832\n",
      "Epoch 12/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3660\n",
      "Epoch 12: val_loss improved from 1.38315 to 1.37732, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 634us/sample - loss: 7.3660 - val_loss: 1.3773\n",
      "Epoch 13/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3469\n",
      "Epoch 13: val_loss did not improve from 1.37732\n",
      "31351/31351 [==============================] - 20s 632us/sample - loss: 7.3469 - val_loss: 1.3866\n",
      "Epoch 14/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3315\n",
      "Epoch 14: val_loss improved from 1.37732 to 1.37422, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 633us/sample - loss: 7.3315 - val_loss: 1.3742\n",
      "Epoch 15/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3333\n",
      "Epoch 15: val_loss did not improve from 1.37422\n",
      "31351/31351 [==============================] - 20s 631us/sample - loss: 7.3333 - val_loss: 1.3808\n",
      "Epoch 16/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3279\n",
      "Epoch 16: val_loss did not improve from 1.37422\n",
      "31351/31351 [==============================] - 20s 635us/sample - loss: 7.3279 - val_loss: 1.3795\n",
      "Epoch 17/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3006\n",
      "Epoch 17: val_loss did not improve from 1.37422\n",
      "31351/31351 [==============================] - 20s 626us/sample - loss: 7.3006 - val_loss: 1.3783\n",
      "Epoch 18/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3005\n",
      "Epoch 18: val_loss did not improve from 1.37422\n",
      "31351/31351 [==============================] - 20s 624us/sample - loss: 7.3005 - val_loss: 1.3825\n",
      "Epoch 19/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3031\n",
      "Epoch 19: val_loss improved from 1.37422 to 1.37407, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 626us/sample - loss: 7.3031 - val_loss: 1.3741\n",
      "Epoch 20/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.2916\n",
      "Epoch 20: val_loss improved from 1.37407 to 1.37354, saving model to ./checkpoints/unknown_person_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 631us/sample - loss: 7.2916 - val_loss: 1.3735\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:44:02.602678: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_33_2/lstm_cell_107/kernel/Assign' id:43320 op device:{requested: '', assigned: ''} def:{{{node lstm_33_2/lstm_cell_107/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_33_2/lstm_cell_107/kernel, lstm_33_2/lstm_cell_107/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:44:05.092543: W tensorflow/c/c_api.cc:304] Operation '{name:'dense_2_2/bias/v/Assign' id:45879 op device:{requested: '', assigned: ''} def:{{{node dense_2_2/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_2_2/bias/v, dense_2_2/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31351 samples, validate on 3490 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:44:10.290743: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:44:23.213018: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_6/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4091"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:44:44.461577: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.39948, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 27s 876us/sample - loss: 1.4091 - val_loss: 1.3995\n",
      "Epoch 2/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4054\n",
      "Epoch 2: val_loss improved from 1.39948 to 1.38983, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 688us/sample - loss: 1.4054 - val_loss: 1.3898\n",
      "Epoch 3/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4036\n",
      "Epoch 3: val_loss did not improve from 1.38983\n",
      "31351/31351 [==============================] - 22s 704us/sample - loss: 1.4036 - val_loss: 1.3921\n",
      "Epoch 4/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4058\n",
      "Epoch 4: val_loss did not improve from 1.38983\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.4058 - val_loss: 1.3938\n",
      "Epoch 5/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4038\n",
      "Epoch 5: val_loss improved from 1.38983 to 1.38840, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 21s 669us/sample - loss: 1.4038 - val_loss: 1.3884\n",
      "Epoch 6/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4014\n",
      "Epoch 6: val_loss did not improve from 1.38840\n",
      "31351/31351 [==============================] - 19s 622us/sample - loss: 1.4014 - val_loss: 1.3950\n",
      "Epoch 7/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3983\n",
      "Epoch 7: val_loss did not improve from 1.38840\n",
      "31351/31351 [==============================] - 20s 627us/sample - loss: 1.3983 - val_loss: 1.3891\n",
      "Epoch 8/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3965\n",
      "Epoch 8: val_loss improved from 1.38840 to 1.38603, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 637us/sample - loss: 1.3965 - val_loss: 1.3860\n",
      "Epoch 9/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3953\n",
      "Epoch 9: val_loss improved from 1.38603 to 1.38542, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 692us/sample - loss: 1.3953 - val_loss: 1.3854\n",
      "Epoch 10/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3943\n",
      "Epoch 10: val_loss did not improve from 1.38542\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.3943 - val_loss: 1.3875\n",
      "Epoch 11/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3907\n",
      "Epoch 11: val_loss improved from 1.38542 to 1.38336, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 714us/sample - loss: 1.3907 - val_loss: 1.3834\n",
      "Epoch 12/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3892\n",
      "Epoch 12: val_loss improved from 1.38336 to 1.38047, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 22s 692us/sample - loss: 1.3892 - val_loss: 1.3805\n",
      "Epoch 13/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3892\n",
      "Epoch 13: val_loss improved from 1.38047 to 1.37850, saving model to ./checkpoints/unknown_person_baseline_2_p29_20.h5\n",
      "31351/31351 [==============================] - 20s 633us/sample - loss: 1.3892 - val_loss: 1.3785\n",
      "Epoch 14/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3918\n",
      "Epoch 14: val_loss did not improve from 1.37850\n",
      "31351/31351 [==============================] - 21s 660us/sample - loss: 1.3918 - val_loss: 1.3803\n",
      "Epoch 15/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3890\n",
      "Epoch 15: val_loss did not improve from 1.37850\n",
      "31351/31351 [==============================] - 22s 700us/sample - loss: 1.3890 - val_loss: 1.3866\n",
      "Epoch 16/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3905\n",
      "Epoch 16: val_loss did not improve from 1.37850\n",
      "31351/31351 [==============================] - 22s 686us/sample - loss: 1.3905 - val_loss: 1.3808\n",
      "Epoch 17/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3856\n",
      "Epoch 17: val_loss did not improve from 1.37850\n",
      "31351/31351 [==============================] - 20s 645us/sample - loss: 1.3856 - val_loss: 1.3840\n",
      "Epoch 18/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3851\n",
      "Epoch 18: val_loss did not improve from 1.37850\n",
      "31351/31351 [==============================] - 22s 706us/sample - loss: 1.3851 - val_loss: 1.3807\n",
      "Epoch 19/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3851\n",
      "Epoch 19: val_loss did not improve from 1.37850\n",
      "31351/31351 [==============================] - 22s 706us/sample - loss: 1.3851 - val_loss: 1.3838\n",
      "Epoch 20/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3844\n",
      "Epoch 20: val_loss did not improve from 1.37850\n",
      "31351/31351 [==============================] - 22s 701us/sample - loss: 1.3844 - val_loss: 1.3809\n",
      "Train on 31351 samples, validate on 3490 samples\n",
      "Epoch 1/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3832\n",
      "Epoch 1: val_loss improved from inf to 1.37473, saving model to ./checkpoints/unknown_person_baseline_p29_21.h5\n",
      "31351/31351 [==============================] - 21s 659us/sample - loss: 1.3832 - val_loss: 1.3747\n",
      "Epoch 2/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3850\n",
      "Epoch 2: val_loss did not improve from 1.37473\n",
      "31351/31351 [==============================] - 21s 670us/sample - loss: 1.3850 - val_loss: 1.3752\n",
      "Epoch 3/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3812\n",
      "Epoch 3: val_loss did not improve from 1.37473\n",
      "31351/31351 [==============================] - 22s 706us/sample - loss: 1.3812 - val_loss: 1.3802\n",
      "Epoch 4/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3794\n",
      "Epoch 4: val_loss did not improve from 1.37473\n",
      "31351/31351 [==============================] - 22s 706us/sample - loss: 1.3794 - val_loss: 1.3757\n",
      "Epoch 5/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3779\n",
      "Epoch 5: val_loss improved from 1.37473 to 1.37262, saving model to ./checkpoints/unknown_person_baseline_p29_21.h5\n",
      "31351/31351 [==============================] - 21s 659us/sample - loss: 1.3779 - val_loss: 1.3726\n",
      "Epoch 6/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3769\n",
      "Epoch 6: val_loss did not improve from 1.37262\n",
      "31351/31351 [==============================] - 20s 643us/sample - loss: 1.3769 - val_loss: 1.3796\n",
      "Epoch 7/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3737\n",
      "Epoch 7: val_loss did not improve from 1.37262\n",
      "31351/31351 [==============================] - 19s 614us/sample - loss: 1.3737 - val_loss: 1.3734\n",
      "Epoch 8/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3832\n",
      "Epoch 8: val_loss did not improve from 1.37262\n",
      "31351/31351 [==============================] - 20s 630us/sample - loss: 1.3832 - val_loss: 1.3910\n",
      "Epoch 9/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3940\n",
      "Epoch 9: val_loss improved from 1.37262 to 1.37194, saving model to ./checkpoints/unknown_person_baseline_p29_21.h5\n",
      "31351/31351 [==============================] - 20s 639us/sample - loss: 1.3940 - val_loss: 1.3719\n",
      "Epoch 10/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3846\n",
      "Epoch 10: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 651us/sample - loss: 1.3846 - val_loss: 1.3771\n",
      "Epoch 11/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3870\n",
      "Epoch 11: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 650us/sample - loss: 1.3870 - val_loss: 1.3795\n",
      "Epoch 12/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3873\n",
      "Epoch 12: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 704us/sample - loss: 1.3873 - val_loss: 1.3831\n",
      "Epoch 13/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3961\n",
      "Epoch 13: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 677us/sample - loss: 1.3961 - val_loss: 1.3814\n",
      "Epoch 14/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3929\n",
      "Epoch 14: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 705us/sample - loss: 1.3929 - val_loss: 1.3806\n",
      "Epoch 15/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3988\n",
      "Epoch 15: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.3988 - val_loss: 1.3851\n",
      "Epoch 16/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3890\n",
      "Epoch 16: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 687us/sample - loss: 1.3890 - val_loss: 1.3826\n",
      "Epoch 17/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4014\n",
      "Epoch 17: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 679us/sample - loss: 1.4014 - val_loss: 1.3862\n",
      "Epoch 18/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3930\n",
      "Epoch 18: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 705us/sample - loss: 1.3930 - val_loss: 1.3895\n",
      "Epoch 19/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3944\n",
      "Epoch 19: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 704us/sample - loss: 1.3944 - val_loss: 1.3858\n",
      "Epoch 20/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4041\n",
      "Epoch 20: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.4041 - val_loss: 1.3870\n",
      "Epoch 21/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4068\n",
      "Epoch 21: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.4068 - val_loss: 1.3966\n",
      "Epoch 22/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4168\n",
      "Epoch 22: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 642us/sample - loss: 1.4168 - val_loss: 1.3915\n",
      "Epoch 23/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4355\n",
      "Epoch 23: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 19s 608us/sample - loss: 1.4355 - val_loss: 1.3858\n",
      "Epoch 24/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4901\n",
      "Epoch 24: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 642us/sample - loss: 1.4901 - val_loss: 1.3896\n",
      "Epoch 25/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4182\n",
      "Epoch 25: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 711us/sample - loss: 1.4182 - val_loss: 1.3854\n",
      "Epoch 26/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4141\n",
      "Epoch 26: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 672us/sample - loss: 1.4141 - val_loss: 1.3810\n",
      "Epoch 27/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4047\n",
      "Epoch 27: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 632us/sample - loss: 1.4047 - val_loss: 1.3887\n",
      "Epoch 28/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3975\n",
      "Epoch 28: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 659us/sample - loss: 1.3975 - val_loss: 1.3826\n",
      "Epoch 29/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3943\n",
      "Epoch 29: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 649us/sample - loss: 1.3943 - val_loss: 1.3841\n",
      "Epoch 30/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3943\n",
      "Epoch 30: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 679us/sample - loss: 1.3943 - val_loss: 1.3792\n",
      "Epoch 31/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3927\n",
      "Epoch 31: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 685us/sample - loss: 1.3927 - val_loss: 1.3824\n",
      "Epoch 32/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3916\n",
      "Epoch 32: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 633us/sample - loss: 1.3916 - val_loss: 1.3782\n",
      "Epoch 33/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3879\n",
      "Epoch 33: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 672us/sample - loss: 1.3879 - val_loss: 1.3877\n",
      "Epoch 34/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3906\n",
      "Epoch 34: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 20s 641us/sample - loss: 1.3906 - val_loss: 1.3788\n",
      "Epoch 35/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3863\n",
      "Epoch 35: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 701us/sample - loss: 1.3863 - val_loss: 1.3813\n",
      "Epoch 36/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3842\n",
      "Epoch 36: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 705us/sample - loss: 1.3842 - val_loss: 1.3827\n",
      "Epoch 37/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3859\n",
      "Epoch 37: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 662us/sample - loss: 1.3859 - val_loss: 1.3815\n",
      "Epoch 38/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3820\n",
      "Epoch 38: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 703us/sample - loss: 1.3820 - val_loss: 1.3797\n",
      "Epoch 39/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3814\n",
      "Epoch 39: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 711us/sample - loss: 1.3814 - val_loss: 1.3802\n",
      "Epoch 40/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3819\n",
      "Epoch 40: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 19s 621us/sample - loss: 1.3819 - val_loss: 1.3790\n",
      "Epoch 41/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3812\n",
      "Epoch 41: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 665us/sample - loss: 1.3812 - val_loss: 1.3799\n",
      "Epoch 42/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3786\n",
      "Epoch 42: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 21s 666us/sample - loss: 1.3786 - val_loss: 1.3778\n",
      "Epoch 43/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3780\n",
      "Epoch 43: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 708us/sample - loss: 1.3780 - val_loss: 1.3786\n",
      "Epoch 44/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3767\n",
      "Epoch 44: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 705us/sample - loss: 1.3767 - val_loss: 1.3805\n",
      "Epoch 45/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3760\n",
      "Epoch 45: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 687us/sample - loss: 1.3760 - val_loss: 1.3768\n",
      "Epoch 46/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3738\n",
      "Epoch 46: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.3738 - val_loss: 1.3785\n",
      "Epoch 47/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3735\n",
      "Epoch 47: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 692us/sample - loss: 1.3735 - val_loss: 1.3830\n",
      "Epoch 48/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3713\n",
      "Epoch 48: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 22s 698us/sample - loss: 1.3713 - val_loss: 1.3787\n",
      "Epoch 49/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3727\n",
      "Epoch 49: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 19s 619us/sample - loss: 1.3727 - val_loss: 1.3806\n",
      "Epoch 50/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3701\n",
      "Epoch 50: val_loss did not improve from 1.37194\n",
      "31351/31351 [==============================] - 19s 618us/sample - loss: 1.3701 - val_loss: 1.3801\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:09:10.742370: W tensorflow/c/c_api.cc:304] Operation '{name:'dense_1_3/bias/Assign' id:63364 op device:{requested: '', assigned: ''} def:{{{node dense_1_3/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_1_3/bias, dense_1_3/bias/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:09:14.028237: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_12_3/lstm_cell_123/kernel/m/Assign' id:64190 op device:{requested: '', assigned: ''} def:{{{node lstm_12_3/lstm_cell_123/kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_12_3/lstm_cell_123/kernel/m, lstm_12_3/lstm_cell_123/kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:09:17.199843: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_3/cond/Merge' id:63349 op device:{requested: '', assigned: ''} def:{{{node dropout_4_3/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_3/cond/Identity, dropout_4_3/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 2160)\n",
      "(1514, 2160)\n",
      "(1644, 2160)\n",
      "(1764, 2160)\n",
      "(1836, 2160)\n",
      "(1699, 2160)\n",
      "(1369, 2160)\n",
      "(1766, 2160)\n",
      "(1631, 2160)\n",
      "(1692, 2160)\n",
      "(1550, 2160)\n",
      "(1920, 2160)\n",
      "(1739, 2160)\n",
      "(1788, 2160)\n",
      "(1812, 2160)\n",
      "(1788, 2160)\n",
      "(1776, 2160)\n",
      "(922, 2160)\n",
      "(1656, 2160)\n",
      "{1: 5.421769569876141, 2: 1.5422427527483764, 4: 4.949670490287369, 5: 10.0, 6: 9.680107954537585, 8: 5.599679054077449, 9: 1.7502198655000214, 10: 6.776864563313647, 11: 3.577016726397756, 12: 5.130019754424663, 13: 6.65992630985593, 17: 5.043337763728956, 19: 5.192789242587012, 21: 6.6727368164952905, 22: 2.0348348204166298, 25: 4.077906206416426, 26: 3.3464126491103583, 27: 1.0, 28: 4.724994679370314}\n",
      "Train on 31351 samples, validate on 3490 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:13:33.355533: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_7/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3867\n",
      "Epoch 1: val_loss improved from inf to 1.38307, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 31s 1ms/sample - loss: 7.3867 - val_loss: 1.3831\n",
      "Epoch 2/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.3224\n",
      "Epoch 2: val_loss did not improve from 1.38307\n",
      "31351/31351 [==============================] - 21s 670us/sample - loss: 7.3224 - val_loss: 1.3907\n",
      "Epoch 3/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.2895\n",
      "Epoch 3: val_loss improved from 1.38307 to 1.38263, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 20s 651us/sample - loss: 7.2895 - val_loss: 1.3826\n",
      "Epoch 4/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.2587\n",
      "Epoch 4: val_loss did not improve from 1.38263\n",
      "31351/31351 [==============================] - 20s 640us/sample - loss: 7.2587 - val_loss: 1.3894\n",
      "Epoch 5/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.2428\n",
      "Epoch 5: val_loss improved from 1.38263 to 1.37895, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 20s 653us/sample - loss: 7.2428 - val_loss: 1.3790\n",
      "Epoch 6/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.2256\n",
      "Epoch 6: val_loss did not improve from 1.37895\n",
      "31351/31351 [==============================] - 20s 647us/sample - loss: 7.2256 - val_loss: 1.3811\n",
      "Epoch 7/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1697\n",
      "Epoch 7: val_loss improved from 1.37895 to 1.37702, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 20s 641us/sample - loss: 7.1697 - val_loss: 1.3770\n",
      "Epoch 8/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1693\n",
      "Epoch 8: val_loss did not improve from 1.37702\n",
      "31351/31351 [==============================] - 21s 682us/sample - loss: 7.1693 - val_loss: 1.3885\n",
      "Epoch 9/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1632\n",
      "Epoch 9: val_loss did not improve from 1.37702\n",
      "31351/31351 [==============================] - 23s 720us/sample - loss: 7.1632 - val_loss: 1.3778\n",
      "Epoch 10/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1614\n",
      "Epoch 10: val_loss improved from 1.37702 to 1.37691, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 23s 721us/sample - loss: 7.1614 - val_loss: 1.3769\n",
      "Epoch 11/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1476\n",
      "Epoch 11: val_loss improved from 1.37691 to 1.37188, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 23s 720us/sample - loss: 7.1476 - val_loss: 1.3719\n",
      "Epoch 12/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1425\n",
      "Epoch 12: val_loss did not improve from 1.37188\n",
      "31351/31351 [==============================] - 20s 634us/sample - loss: 7.1425 - val_loss: 1.3783\n",
      "Epoch 13/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1251\n",
      "Epoch 13: val_loss did not improve from 1.37188\n",
      "31351/31351 [==============================] - 22s 713us/sample - loss: 7.1251 - val_loss: 1.3737\n",
      "Epoch 14/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1312\n",
      "Epoch 14: val_loss improved from 1.37188 to 1.36741, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 23s 726us/sample - loss: 7.1312 - val_loss: 1.3674\n",
      "Epoch 15/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1116\n",
      "Epoch 15: val_loss did not improve from 1.36741\n",
      "31351/31351 [==============================] - 22s 691us/sample - loss: 7.1116 - val_loss: 1.3758\n",
      "Epoch 16/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.0966\n",
      "Epoch 16: val_loss did not improve from 1.36741\n",
      "31351/31351 [==============================] - 22s 718us/sample - loss: 7.0966 - val_loss: 1.3730\n",
      "Epoch 17/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.1023\n",
      "Epoch 17: val_loss improved from 1.36741 to 1.36555, saving model to ./checkpoints/unknown_person_p29_21.h5\n",
      "31351/31351 [==============================] - 22s 715us/sample - loss: 7.1023 - val_loss: 1.3655\n",
      "Epoch 18/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.0743\n",
      "Epoch 18: val_loss did not improve from 1.36555\n",
      "31351/31351 [==============================] - 22s 686us/sample - loss: 7.0743 - val_loss: 1.3661\n",
      "Epoch 19/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.0727\n",
      "Epoch 19: val_loss did not improve from 1.36555\n",
      "31351/31351 [==============================] - 22s 714us/sample - loss: 7.0727 - val_loss: 1.3707\n",
      "Epoch 20/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.0628\n",
      "Epoch 20: val_loss did not improve from 1.36555\n",
      "31351/31351 [==============================] - 21s 670us/sample - loss: 7.0628 - val_loss: 1.3721\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:20:54.988024: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_34_4/lstm_cell_182/bias/Assign' id:82267 op device:{requested: '', assigned: ''} def:{{{node lstm_34_4/lstm_cell_182/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_34_4/lstm_cell_182/bias, lstm_34_4/lstm_cell_182/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:20:59.122127: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_40/lstm_cell_148/kernel/m/Assign' id:83408 op device:{requested: '', assigned: ''} def:{{{node lstm_40/lstm_cell_148/kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_40/lstm_cell_148/kernel/m, lstm_40/lstm_cell_148/kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31351 samples, validate on 3490 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:21:05.754329: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:21:27.287372: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_8/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3819"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:21:48.240864: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.38087, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 30s 968us/sample - loss: 1.3819 - val_loss: 1.3809\n",
      "Epoch 2/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3766\n",
      "Epoch 2: val_loss improved from 1.38087 to 1.37476, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 20s 628us/sample - loss: 1.3766 - val_loss: 1.3748\n",
      "Epoch 3/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3812\n",
      "Epoch 3: val_loss did not improve from 1.37476\n",
      "31351/31351 [==============================] - 20s 649us/sample - loss: 1.3812 - val_loss: 1.3787\n",
      "Epoch 4/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3769\n",
      "Epoch 4: val_loss did not improve from 1.37476\n",
      "31351/31351 [==============================] - 21s 678us/sample - loss: 1.3769 - val_loss: 1.3749\n",
      "Epoch 5/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3748\n",
      "Epoch 5: val_loss improved from 1.37476 to 1.37109, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 21s 659us/sample - loss: 1.3748 - val_loss: 1.3711\n",
      "Epoch 6/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3737\n",
      "Epoch 6: val_loss did not improve from 1.37109\n",
      "31351/31351 [==============================] - 21s 667us/sample - loss: 1.3737 - val_loss: 1.3824\n",
      "Epoch 7/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3725\n",
      "Epoch 7: val_loss did not improve from 1.37109\n",
      "31351/31351 [==============================] - 20s 651us/sample - loss: 1.3725 - val_loss: 1.3840\n",
      "Epoch 8/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3722\n",
      "Epoch 8: val_loss did not improve from 1.37109\n",
      "31351/31351 [==============================] - 22s 710us/sample - loss: 1.3722 - val_loss: 1.3756\n",
      "Epoch 9/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3733\n",
      "Epoch 9: val_loss did not improve from 1.37109\n",
      "31351/31351 [==============================] - 22s 714us/sample - loss: 1.3733 - val_loss: 1.3744\n",
      "Epoch 10/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3698\n",
      "Epoch 10: val_loss did not improve from 1.37109\n",
      "31351/31351 [==============================] - 22s 712us/sample - loss: 1.3698 - val_loss: 1.3764\n",
      "Epoch 11/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3687\n",
      "Epoch 11: val_loss improved from 1.37109 to 1.36873, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 22s 715us/sample - loss: 1.3687 - val_loss: 1.3687\n",
      "Epoch 12/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3671\n",
      "Epoch 12: val_loss improved from 1.36873 to 1.36791, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 21s 660us/sample - loss: 1.3671 - val_loss: 1.3679\n",
      "Epoch 13/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3693\n",
      "Epoch 13: val_loss improved from 1.36791 to 1.36693, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 21s 681us/sample - loss: 1.3693 - val_loss: 1.3669\n",
      "Epoch 14/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3660\n",
      "Epoch 14: val_loss improved from 1.36693 to 1.36683, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 22s 714us/sample - loss: 1.3660 - val_loss: 1.3668\n",
      "Epoch 15/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3659\n",
      "Epoch 15: val_loss did not improve from 1.36683\n",
      "31351/31351 [==============================] - 22s 716us/sample - loss: 1.3659 - val_loss: 1.3731\n",
      "Epoch 16/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3630\n",
      "Epoch 16: val_loss did not improve from 1.36683\n",
      "31351/31351 [==============================] - 21s 676us/sample - loss: 1.3630 - val_loss: 1.3727\n",
      "Epoch 17/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3628\n",
      "Epoch 17: val_loss improved from 1.36683 to 1.36592, saving model to ./checkpoints/unknown_person_baseline_2_p29_21.h5\n",
      "31351/31351 [==============================] - 21s 673us/sample - loss: 1.3628 - val_loss: 1.3659\n",
      "Epoch 18/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3636\n",
      "Epoch 18: val_loss did not improve from 1.36592\n",
      "31351/31351 [==============================] - 21s 677us/sample - loss: 1.3636 - val_loss: 1.3718\n",
      "Epoch 19/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3607\n",
      "Epoch 19: val_loss did not improve from 1.36592\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.3607 - val_loss: 1.3686\n",
      "Epoch 20/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3607\n",
      "Epoch 20: val_loss did not improve from 1.36592\n",
      "31351/31351 [==============================] - 20s 628us/sample - loss: 1.3607 - val_loss: 1.3721\n",
      "Train on 31351 samples, validate on 3490 samples\n",
      "Epoch 1/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3633\n",
      "Epoch 1: val_loss improved from inf to 1.36650, saving model to ./checkpoints/unknown_person_baseline_p29_22.h5\n",
      "31351/31351 [==============================] - 22s 713us/sample - loss: 1.3633 - val_loss: 1.3665\n",
      "Epoch 2/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3587\n",
      "Epoch 2: val_loss did not improve from 1.36650\n",
      "31351/31351 [==============================] - 21s 668us/sample - loss: 1.3587 - val_loss: 1.3707\n",
      "Epoch 3/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3581\n",
      "Epoch 3: val_loss did not improve from 1.36650\n",
      "31351/31351 [==============================] - 21s 669us/sample - loss: 1.3581 - val_loss: 1.3668\n",
      "Epoch 4/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3540\n",
      "Epoch 4: val_loss did not improve from 1.36650\n",
      "31351/31351 [==============================] - 20s 624us/sample - loss: 1.3540 - val_loss: 1.3702\n",
      "Epoch 5/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3555\n",
      "Epoch 5: val_loss did not improve from 1.36650\n",
      "31351/31351 [==============================] - 21s 668us/sample - loss: 1.3555 - val_loss: 1.3762\n",
      "Epoch 6/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3547\n",
      "Epoch 6: val_loss improved from 1.36650 to 1.36407, saving model to ./checkpoints/unknown_person_baseline_p29_22.h5\n",
      "31351/31351 [==============================] - 22s 697us/sample - loss: 1.3547 - val_loss: 1.3641\n",
      "Epoch 7/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3539\n",
      "Epoch 7: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 20s 627us/sample - loss: 1.3539 - val_loss: 1.3689\n",
      "Epoch 8/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3666\n",
      "Epoch 8: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 710us/sample - loss: 1.3666 - val_loss: 1.3650\n",
      "Epoch 9/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3688\n",
      "Epoch 9: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.3688 - val_loss: 1.3676\n",
      "Epoch 10/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3639\n",
      "Epoch 10: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 710us/sample - loss: 1.3639 - val_loss: 1.3739\n",
      "Epoch 11/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3713\n",
      "Epoch 11: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 708us/sample - loss: 1.3713 - val_loss: 1.3736\n",
      "Epoch 12/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3733\n",
      "Epoch 12: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 21s 684us/sample - loss: 1.3733 - val_loss: 1.3742\n",
      "Epoch 13/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3800\n",
      "Epoch 13: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 612us/sample - loss: 1.3800 - val_loss: 1.3706\n",
      "Epoch 14/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4314\n",
      "Epoch 14: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 617us/sample - loss: 1.4314 - val_loss: 1.3852\n",
      "Epoch 15/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4366\n",
      "Epoch 15: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 705us/sample - loss: 1.4366 - val_loss: 1.3854\n",
      "Epoch 16/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3924\n",
      "Epoch 16: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 708us/sample - loss: 1.3924 - val_loss: 1.3804\n",
      "Epoch 17/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3988\n",
      "Epoch 17: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 711us/sample - loss: 1.3988 - val_loss: 1.3866\n",
      "Epoch 18/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4288\n",
      "Epoch 18: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 703us/sample - loss: 1.4288 - val_loss: 1.3921\n",
      "Epoch 19/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4244\n",
      "Epoch 19: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 21s 657us/sample - loss: 1.4244 - val_loss: 1.3966\n",
      "Epoch 20/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4420\n",
      "Epoch 20: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 696us/sample - loss: 1.4420 - val_loss: 1.3918\n",
      "Epoch 21/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4516\n",
      "Epoch 21: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 690us/sample - loss: 1.4516 - val_loss: 1.3908\n",
      "Epoch 22/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4442\n",
      "Epoch 22: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 20s 627us/sample - loss: 1.4442 - val_loss: 1.3951\n",
      "Epoch 23/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4345\n",
      "Epoch 23: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 619us/sample - loss: 1.4345 - val_loss: 1.3929\n",
      "Epoch 24/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4389\n",
      "Epoch 24: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 616us/sample - loss: 1.4389 - val_loss: 1.4010\n",
      "Epoch 25/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4358\n",
      "Epoch 25: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 612us/sample - loss: 1.4358 - val_loss: 1.4009\n",
      "Epoch 26/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4221\n",
      "Epoch 26: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 20s 628us/sample - loss: 1.4221 - val_loss: 1.4082\n",
      "Epoch 27/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4189\n",
      "Epoch 27: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 619us/sample - loss: 1.4189 - val_loss: 1.4000\n",
      "Epoch 28/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4171\n",
      "Epoch 28: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 21s 682us/sample - loss: 1.4171 - val_loss: 1.3982\n",
      "Epoch 29/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4201\n",
      "Epoch 29: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.4201 - val_loss: 1.3966\n",
      "Epoch 30/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4160\n",
      "Epoch 30: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 706us/sample - loss: 1.4160 - val_loss: 1.3938\n",
      "Epoch 31/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4175\n",
      "Epoch 31: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 706us/sample - loss: 1.4175 - val_loss: 1.3935\n",
      "Epoch 32/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4158\n",
      "Epoch 32: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 700us/sample - loss: 1.4158 - val_loss: 1.3895\n",
      "Epoch 33/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4107\n",
      "Epoch 33: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 704us/sample - loss: 1.4107 - val_loss: 1.3933\n",
      "Epoch 34/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4062\n",
      "Epoch 34: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 21s 655us/sample - loss: 1.4062 - val_loss: 1.3923\n",
      "Epoch 35/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4031\n",
      "Epoch 35: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.4031 - val_loss: 1.3925\n",
      "Epoch 36/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4040\n",
      "Epoch 36: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 711us/sample - loss: 1.4040 - val_loss: 1.3859\n",
      "Epoch 37/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4063\n",
      "Epoch 37: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 23s 719us/sample - loss: 1.4063 - val_loss: 1.3859\n",
      "Epoch 38/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4019\n",
      "Epoch 38: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 711us/sample - loss: 1.4019 - val_loss: 1.3847\n",
      "Epoch 39/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4055\n",
      "Epoch 39: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 606us/sample - loss: 1.4055 - val_loss: 1.3921\n",
      "Epoch 40/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4018\n",
      "Epoch 40: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 605us/sample - loss: 1.4018 - val_loss: 1.3867\n",
      "Epoch 41/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4054\n",
      "Epoch 41: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 19s 604us/sample - loss: 1.4054 - val_loss: 1.3909\n",
      "Epoch 42/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.4005\n",
      "Epoch 42: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 21s 683us/sample - loss: 1.4005 - val_loss: 1.3820\n",
      "Epoch 43/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3991\n",
      "Epoch 43: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.3991 - val_loss: 1.3834\n",
      "Epoch 44/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3973\n",
      "Epoch 44: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 709us/sample - loss: 1.3973 - val_loss: 1.3884\n",
      "Epoch 45/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3944\n",
      "Epoch 45: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 20s 643us/sample - loss: 1.3944 - val_loss: 1.3823\n",
      "Epoch 46/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3923\n",
      "Epoch 46: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 22s 708us/sample - loss: 1.3923 - val_loss: 1.3932\n",
      "Epoch 47/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3939\n",
      "Epoch 47: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 20s 651us/sample - loss: 1.3939 - val_loss: 1.3828\n",
      "Epoch 48/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3934\n",
      "Epoch 48: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 20s 634us/sample - loss: 1.3934 - val_loss: 1.3793\n",
      "Epoch 49/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3945\n",
      "Epoch 49: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 21s 680us/sample - loss: 1.3945 - val_loss: 1.3832\n",
      "Epoch 50/50\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3886\n",
      "Epoch 50: val_loss did not improve from 1.36407\n",
      "31351/31351 [==============================] - 20s 628us/sample - loss: 1.3886 - val_loss: 1.3808\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:46:18.411819: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_12_5/lstm_cell_197/kernel/Assign' id:98076 op device:{requested: '', assigned: ''} def:{{{node lstm_12_5/lstm_cell_197/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_12_5/lstm_cell_197/kernel, lstm_12_5/lstm_cell_197/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:46:23.486077: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_32_5/lstm_cell_217/bias/m/Assign' id:103258 op device:{requested: '', assigned: ''} def:{{{node lstm_32_5/lstm_cell_217/bias/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_32_5/lstm_cell_217/bias/m, lstm_32_5/lstm_cell_217/bias/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:46:28.397517: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_5/cond/Merge' id:102107 op device:{requested: '', assigned: ''} def:{{{node dropout_4_5/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_5/cond/Identity, dropout_4_5/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 2160)\n",
      "(1514, 2160)\n",
      "(1644, 2160)\n",
      "(1764, 2160)\n",
      "(1836, 2160)\n",
      "(1699, 2160)\n",
      "(1369, 2160)\n",
      "(1766, 2160)\n",
      "(1631, 2160)\n",
      "(1692, 2160)\n",
      "(1550, 2160)\n",
      "(1920, 2160)\n",
      "(1739, 2160)\n",
      "(1788, 2160)\n",
      "(1812, 2160)\n",
      "(1788, 2160)\n",
      "(1776, 2160)\n",
      "(922, 2160)\n",
      "(1656, 2160)\n",
      "{1: 4.857963962190981, 2: 1.3080829219578458, 4: 4.92884551817571, 5: 10.0, 6: 9.701656250227247, 8: 5.285317777266189, 9: 1.6661143101783296, 10: 6.442277749769255, 11: 3.458747466461188, 12: 4.890766978679659, 13: 6.342095832960918, 17: 4.864772104162492, 19: 5.155035224002157, 21: 6.304453054316292, 22: 2.0779406240400995, 25: 3.9919331774449667, 26: 3.205774208683055, 27: 1.0, 28: 4.509287348750529}\n",
      "Train on 31351 samples, validate on 3490 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:50:49.456896: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_9/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31351/31351 [==============================] - ETA: 0s - loss: 7.0127\n",
      "Epoch 1: val_loss improved from inf to 1.38655, saving model to ./checkpoints/unknown_person_p29_22.h5\n",
      "31351/31351 [==============================] - 32s 1ms/sample - loss: 7.0127 - val_loss: 1.3865\n",
      "Epoch 2/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.9849\n",
      "Epoch 2: val_loss improved from 1.38655 to 1.37182, saving model to ./checkpoints/unknown_person_p29_22.h5\n",
      "31351/31351 [==============================] - 20s 638us/sample - loss: 6.9849 - val_loss: 1.3718\n",
      "Epoch 3/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 7.0453\n",
      "Epoch 3: val_loss did not improve from 1.37182\n",
      "31351/31351 [==============================] - 22s 695us/sample - loss: 7.0453 - val_loss: 1.3736\n",
      "Epoch 4/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.9449\n",
      "Epoch 4: val_loss did not improve from 1.37182\n",
      "31351/31351 [==============================] - 22s 705us/sample - loss: 6.9449 - val_loss: 1.3809\n",
      "Epoch 5/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.9311\n",
      "Epoch 5: val_loss improved from 1.37182 to 1.37012, saving model to ./checkpoints/unknown_person_p29_22.h5\n",
      "31351/31351 [==============================] - 20s 648us/sample - loss: 6.9311 - val_loss: 1.3701\n",
      "Epoch 6/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8934\n",
      "Epoch 6: val_loss improved from 1.37012 to 1.36767, saving model to ./checkpoints/unknown_person_p29_22.h5\n",
      "31351/31351 [==============================] - 20s 627us/sample - loss: 6.8934 - val_loss: 1.3677\n",
      "Epoch 7/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.9036\n",
      "Epoch 7: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 22s 711us/sample - loss: 6.9036 - val_loss: 1.3763\n",
      "Epoch 8/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8736\n",
      "Epoch 8: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 20s 636us/sample - loss: 6.8736 - val_loss: 1.3705\n",
      "Epoch 9/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8780\n",
      "Epoch 9: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 19s 619us/sample - loss: 6.8780 - val_loss: 1.3706\n",
      "Epoch 10/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8729\n",
      "Epoch 10: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 20s 624us/sample - loss: 6.8729 - val_loss: 1.3785\n",
      "Epoch 11/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8462\n",
      "Epoch 11: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 20s 623us/sample - loss: 6.8462 - val_loss: 1.3710\n",
      "Epoch 12/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8515\n",
      "Epoch 12: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 20s 623us/sample - loss: 6.8515 - val_loss: 1.3733\n",
      "Epoch 13/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8427\n",
      "Epoch 13: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 20s 623us/sample - loss: 6.8427 - val_loss: 1.3777\n",
      "Epoch 14/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8409\n",
      "Epoch 14: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 20s 624us/sample - loss: 6.8409 - val_loss: 1.3725\n",
      "Epoch 15/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8275\n",
      "Epoch 15: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 20s 642us/sample - loss: 6.8275 - val_loss: 1.3742\n",
      "Epoch 16/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8312\n",
      "Epoch 16: val_loss did not improve from 1.36767\n",
      "31351/31351 [==============================] - 22s 705us/sample - loss: 6.8312 - val_loss: 1.3697\n",
      "Epoch 17/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8228\n",
      "Epoch 17: val_loss improved from 1.36767 to 1.36619, saving model to ./checkpoints/unknown_person_p29_22.h5\n",
      "31351/31351 [==============================] - 22s 698us/sample - loss: 6.8228 - val_loss: 1.3662\n",
      "Epoch 18/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.7912\n",
      "Epoch 18: val_loss improved from 1.36619 to 1.36473, saving model to ./checkpoints/unknown_person_p29_22.h5\n",
      "31351/31351 [==============================] - 22s 704us/sample - loss: 6.7912 - val_loss: 1.3647\n",
      "Epoch 19/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8003\n",
      "Epoch 19: val_loss did not improve from 1.36473\n",
      "31351/31351 [==============================] - 22s 693us/sample - loss: 6.8003 - val_loss: 1.3716\n",
      "Epoch 20/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 6.8025\n",
      "Epoch 20: val_loss did not improve from 1.36473\n",
      "31351/31351 [==============================] - 19s 618us/sample - loss: 6.8025 - val_loss: 1.3676\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:57:54.886358: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_35_6/lstm_cell_257/bias/Assign' id:121185 op device:{requested: '', assigned: ''} def:{{{node lstm_35_6/lstm_cell_257/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_35_6/lstm_cell_257/bias, lstm_35_6/lstm_cell_257/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:58:00.843179: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_42/lstm_cell_222/bias/m/Assign' id:122176 op device:{requested: '', assigned: ''} def:{{{node lstm_42/lstm_cell_222/bias/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_42/lstm_cell_222/bias/m, lstm_42/lstm_cell_222/bias/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31351 samples, validate on 3490 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:58:09.686446: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:58:40.719715: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_10/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3509"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:59:03.330047: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.36486, saving model to ./checkpoints/unknown_person_baseline_2_p29_22.h5\n",
      "31351/31351 [==============================] - 35s 1ms/sample - loss: 1.3509 - val_loss: 1.3649\n",
      "Epoch 2/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3560\n",
      "Epoch 2: val_loss did not improve from 1.36486\n",
      "31351/31351 [==============================] - 22s 699us/sample - loss: 1.3560 - val_loss: 1.3673\n",
      "Epoch 3/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3818\n",
      "Epoch 3: val_loss did not improve from 1.36486\n",
      "31351/31351 [==============================] - 22s 695us/sample - loss: 1.3818 - val_loss: 1.3773\n",
      "Epoch 4/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3615\n",
      "Epoch 4: val_loss did not improve from 1.36486\n",
      "31351/31351 [==============================] - 22s 703us/sample - loss: 1.3615 - val_loss: 1.3761\n",
      "Epoch 5/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3563\n",
      "Epoch 5: val_loss did not improve from 1.36486\n",
      "31351/31351 [==============================] - 22s 691us/sample - loss: 1.3563 - val_loss: 1.3718\n",
      "Epoch 6/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3561\n",
      "Epoch 6: val_loss did not improve from 1.36486\n",
      "31351/31351 [==============================] - 19s 615us/sample - loss: 1.3561 - val_loss: 1.3701\n",
      "Epoch 7/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3541\n",
      "Epoch 7: val_loss did not improve from 1.36486\n",
      "31351/31351 [==============================] - 19s 614us/sample - loss: 1.3541 - val_loss: 1.3649\n",
      "Epoch 8/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3563\n",
      "Epoch 8: val_loss improved from 1.36486 to 1.36384, saving model to ./checkpoints/unknown_person_baseline_2_p29_22.h5\n",
      "31351/31351 [==============================] - 19s 616us/sample - loss: 1.3563 - val_loss: 1.3638\n",
      "Epoch 9/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3499\n",
      "Epoch 9: val_loss did not improve from 1.36384\n",
      "31351/31351 [==============================] - 19s 612us/sample - loss: 1.3499 - val_loss: 1.3712\n",
      "Epoch 10/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3512\n",
      "Epoch 10: val_loss improved from 1.36384 to 1.36300, saving model to ./checkpoints/unknown_person_baseline_2_p29_22.h5\n",
      "31351/31351 [==============================] - 19s 618us/sample - loss: 1.3512 - val_loss: 1.3630\n",
      "Epoch 11/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3516\n",
      "Epoch 11: val_loss did not improve from 1.36300\n",
      "31351/31351 [==============================] - 19s 613us/sample - loss: 1.3516 - val_loss: 1.3690\n",
      "Epoch 12/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3496\n",
      "Epoch 12: val_loss did not improve from 1.36300\n",
      "31351/31351 [==============================] - 19s 613us/sample - loss: 1.3496 - val_loss: 1.3634\n",
      "Epoch 13/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3484\n",
      "Epoch 13: val_loss did not improve from 1.36300\n",
      "31351/31351 [==============================] - 19s 622us/sample - loss: 1.3484 - val_loss: 1.3632\n",
      "Epoch 14/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3491\n",
      "Epoch 14: val_loss did not improve from 1.36300\n",
      "31351/31351 [==============================] - 19s 619us/sample - loss: 1.3491 - val_loss: 1.3667\n",
      "Epoch 15/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3465\n",
      "Epoch 15: val_loss did not improve from 1.36300\n",
      "31351/31351 [==============================] - 19s 605us/sample - loss: 1.3465 - val_loss: 1.3704\n",
      "Epoch 16/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3486\n",
      "Epoch 16: val_loss did not improve from 1.36300\n",
      "31351/31351 [==============================] - 19s 608us/sample - loss: 1.3486 - val_loss: 1.3639\n",
      "Epoch 17/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3474\n",
      "Epoch 17: val_loss improved from 1.36300 to 1.36186, saving model to ./checkpoints/unknown_person_baseline_2_p29_22.h5\n",
      "31351/31351 [==============================] - 19s 613us/sample - loss: 1.3474 - val_loss: 1.3619\n",
      "Epoch 18/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3443\n",
      "Epoch 18: val_loss did not improve from 1.36186\n",
      "31351/31351 [==============================] - 19s 609us/sample - loss: 1.3443 - val_loss: 1.3694\n",
      "Epoch 19/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3464\n",
      "Epoch 19: val_loss did not improve from 1.36186\n",
      "31351/31351 [==============================] - 20s 649us/sample - loss: 1.3464 - val_loss: 1.3629\n",
      "Epoch 20/20\n",
      "31351/31351 [==============================] - ETA: 0s - loss: 1.3430\n",
      "Epoch 20: val_loss improved from 1.36186 to 1.36175, saving model to ./checkpoints/unknown_person_baseline_2_p29_22.h5\n",
      "31351/31351 [==============================] - 19s 610us/sample - loss: 1.3430 - val_loss: 1.3618\n"
     ]
    }
   ],
   "source": [
    "person_nums = [1,2,4,5,6,8,9,10,11,12,13,17,19,21,22,25,26,27,28,29]\n",
    "## Build the baseline model for emotion recognition with dropout layers\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, SimpleRNN, LSTM, Conv2D, Flatten, MaxPooling2D, GRU, AveragePooling2D, Dropout, Lambda\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "def individual_model(features_list):\n",
    "    input_layers = []\n",
    "    hidden_layers = []\n",
    "    combined_feature = np.empty((len(features_list[0]),0))\n",
    "    for i, feature in enumerate(features_list):\n",
    "        \n",
    "        if len(feature.shape) == 3:\n",
    "            input_i = Input(shape=(feature.shape[1], feature.shape[2]))\n",
    "            input_layers.append(input_i)\n",
    "\n",
    "            hidden_i = input_i[:,:,:,None]\n",
    "            hidden_i = Conv2D(32, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(16, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(8, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(4, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Flatten()(hidden_i)\n",
    "\n",
    "            hidden_layers.append(hidden_i)\n",
    "        elif feature.shape[1] <20:\n",
    "            combined_feature = np.hstack((combined_feature, feature))\n",
    "            \n",
    "        else:  # For series features\n",
    "            input_i = Input(shape=(feature.shape[1],))\n",
    "            input_layers.append(input_i)\n",
    "            hidden_i = Lambda(lambda x: x[:, :, None])(input_i)  # Add a new dimension\n",
    "            hidden_i = LSTM(4)(hidden_i)\n",
    "            hidden_layers.append(hidden_i)\n",
    "    input_i = Input(shape=(combined_feature.shape[1],))\n",
    "    input_layers.append(input_i)\n",
    "    dense_num = np.max((1, int(combined_feature.shape[1]/2)))\n",
    "    hidden_i = Dense(dense_num, activation='relu')(input_i)\n",
    "    hidden_layers.append(hidden_i)\n",
    "    print(combined_feature.shape)\n",
    "    concat_layer = concatenate(hidden_layers)\n",
    "    h = Dropout(0.2)(concat_layer)\n",
    "    h = Dense(64, activation='relu')(h)\n",
    "    h = Dense(32, activation='relu')(h)\n",
    "    output_layer = Dense(2)(h)\n",
    "    model = Model(inputs=input_layers, outputs=output_layer)\n",
    "    model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "    return model\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.callbacks import Callback\n",
    "import numpy as np\n",
    "\n",
    "class PruningCallback(tf.keras.callbacks.Callback):\n",
    "    def __init__(self, initial_pruning_factor=0.1, final_pruning_factor=0.5, start_epoch=0, end_epoch=None, frequency=1):\n",
    "        super(PruningCallback, self).__init__()\n",
    "        self.initial_pruning_factor = initial_pruning_factor\n",
    "        self.final_pruning_factor = final_pruning_factor\n",
    "        self.start_epoch = start_epoch\n",
    "        self.end_epoch = end_epoch if end_epoch is not None else np.inf\n",
    "        self.frequency = frequency\n",
    "        self.pruned_weights = {}\n",
    "        self.layer_importance = {}\n",
    "\n",
    "    def get_pruning_factor(self, epoch):\n",
    "        if epoch < self.start_epoch:\n",
    "            return 0\n",
    "        if epoch > self.end_epoch:\n",
    "            return self.final_pruning_factor\n",
    "        return self.initial_pruning_factor + (self.final_pruning_factor - self.initial_pruning_factor) * (epoch - self.start_epoch) / (self.end_epoch - self.start_epoch)\n",
    "\n",
    "    def on_train_begin(self, logs=None):\n",
    "        total_weight_magnitude = 0\n",
    "        for layer in self.model.layers:\n",
    "            if hasattr(layer, 'get_weights'):\n",
    "                weights = layer.get_weights()\n",
    "                layer_norm = sum(np.linalg.norm(w) for w in weights)\n",
    "                total_weight_magnitude += layer_norm\n",
    "                self.layer_importance[layer.name] = layer_norm\n",
    "    \n",
    "        # Normalize the layer importance values so they sum up to 1\n",
    "        for layer_name in self.layer_importance:\n",
    "            self.layer_importance[layer_name] /= total_weight_magnitude\n",
    "    # def on_train_begin(self, logs=None):\n",
    "    #     total_weight_magnitude = sum([np.linalg.norm(layer.get_weights()) for layer in self.model.layers if hasattr(layer, 'get_weights')])\n",
    "    #     for layer in self.model.layers:\n",
    "    #         if hasattr(layer, 'get_weights'):\n",
    "    #             self.layer_importance[layer.name] = np.linalg.norm(layer.get_weights()) / total_weight_magnitude\n",
    "\n",
    "    def get_layer_pruning_factor(self, layer_name, global_pruning_factor):\n",
    "        if layer_name in self.layer_importance:\n",
    "            importance = self.layer_importance[layer_name]\n",
    "            adjusted_pruning_factor = global_pruning_factor * (1 - importance)\n",
    "            return min(adjusted_pruning_factor, 1)  # Ensure the pruning factor is not greater than 1\n",
    "        return global_pruning_factor\n",
    "    def prune_weights(self, layer, global_pruning_factor):\n",
    "        \n",
    "        weights = layer.get_weights()\n",
    "        layer_name = layer.name\n",
    "        pruning_factor = self.get_layer_pruning_factor(layer_name, global_pruning_factor)\n",
    "\n",
    "        if layer_name not in self.pruned_weights:\n",
    "            self.pruned_weights[layer_name] = [np.zeros_like(w, dtype=bool) for w in weights]\n",
    "        \n",
    "        for i in range(len(weights)):\n",
    "            weight = weights[i]\n",
    "            # print(weight.shape)\n",
    "            # print(weight.size)\n",
    "            if weight.ndim > 1:  # Only prune dense or convolutional layers\n",
    "                unpruned_weights = np.logical_not(self.pruned_weights[layer_name][i])\n",
    "                num_unpruned = np.sum(unpruned_weights)\n",
    "                num_pruning = min(num_unpruned, int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i]))\n",
    "                num_pruning = int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i])\n",
    "                if num_pruning > 0:\n",
    "                    unpruned_flat_indices = np.flatnonzero(unpruned_weights)\n",
    "                    abs_unpruned_weights = np.abs(weight[unpruned_weights])\n",
    "                    pruning_flat_indices = np.argpartition(abs_unpruned_weights, num_pruning)[:num_pruning]\n",
    "                    \n",
    "                    indices = np.unravel_index(pruning_flat_indices, weight.shape)\n",
    "                    self.pruned_weights[layer_name][i][indices] = True\n",
    "\n",
    "                weights[i] = weights[i]*(~self.pruned_weights[layer_name][i])\n",
    "                \n",
    "        layer.set_weights(weights)\n",
    "\n",
    "    def on_epoch_end(self, epoch, logs=None):\n",
    "        if (epoch - self.start_epoch) % self.frequency != 0:\n",
    "            return\n",
    "\n",
    "        pruning_factor = self.get_pruning_factor(epoch)\n",
    "        for layer in self.model.layers:\n",
    "            if isinstance(layer, (tf.keras.layers.Dense, tf.keras.layers.Conv2D)):\n",
    "                self.prune_weights(layer, pruning_factor)\n",
    "from feature_emotion import feature_extract, split_data, label_unique_tuples, split_data_unknown\n",
    "gts, sensor_nums, walk_nums, trace_nums, people_nums, spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features = feature_extract(person_nums)\n",
    "\n",
    "walk_nums_all = np.squeeze(walk_nums)\n",
    "trace_nums_all = np.squeeze(trace_nums)\n",
    "people_nums_all = np.squeeze(people_nums)\n",
    "\n",
    "## 0: train, 1: validation 2: test\n",
    "\n",
    "test_person_id = [29]\n",
    "flag_tr_val_te = split_data_unknown(test_person_id, walk_nums_all, trace_nums_all, people_nums_all, person_nums, rand_seed = 42)\n",
    "## Data Normalization before training ans testing\n",
    "import tensorflow as tf\n",
    "tf.compat.v1.disable_v2_behavior()\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, LSTM\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "scalers = []\n",
    "X_train_normalized = []\n",
    "X_val_normalized = []\n",
    "X_test_normalized = []\n",
    "train_idx = np.where(flag_tr_val_te ==0)[0]\n",
    "np.random.shuffle(train_idx)\n",
    "val_idx = np.where(flag_tr_val_te ==1)[0]\n",
    "test_idx = np.where(flag_tr_val_te ==2)[0]\n",
    "\n",
    "for i, feature in enumerate([spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features]):\n",
    "    scaler = StandardScaler()\n",
    "    if len(feature.shape)==2:\n",
    "        X_train_i = feature[train_idx,:]\n",
    "        X_val_i = feature[val_idx,:]\n",
    "        X_test_i = feature[test_idx,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i)\n",
    "        scalers.append(scaler)\n",
    "    else:\n",
    "        X_train_i = feature[train_idx,:,:]\n",
    "        X_val_i = feature[val_idx,:,:]\n",
    "        X_test_i = feature[test_idx,:,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i.reshape(X_train_i.shape[0], -1)).reshape(X_train_i.shape)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i.reshape(X_val_i.shape[0], -1)).reshape(X_val_i.shape)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i.reshape(X_test_i.shape[0], -1)).reshape(X_test_i.shape)\n",
    "        scalers.append(scaler)\n",
    "    X_train_normalized.append(X_train_normalized_i)\n",
    "    X_val_normalized.append(X_val_normalized_i)\n",
    "    X_test_normalized.append(X_test_normalized_i)\n",
    "y_train = gts[train_idx,:]\n",
    "y_val = gts[val_idx,:]\n",
    "y_test = gts[test_idx,:]\n",
    "X_train_normalized_new = []\n",
    "combined_feature = np.empty((len(X_train_normalized[0]),0))\n",
    "for feature in X_train_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_train_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_train_normalized_new.append(feature)\n",
    "X_train_normalized_new.append(combined_feature)\n",
    "\n",
    "X_val_normalized_new = []\n",
    "combined_feature = np.empty((len(X_val_normalized[0]),0))\n",
    "for feature in X_val_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_val_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_val_normalized_new.append(feature)\n",
    "X_val_normalized_new.append(combined_feature)\n",
    "\n",
    "X_test_normalized_new = []\n",
    "combined_feature = np.empty((len(X_test_normalized[0]),0))\n",
    "for feature in X_test_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_test_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_test_normalized_new.append(feature)\n",
    "X_test_normalized_new.append(combined_feature)\n",
    "\n",
    "model = individual_model(X_train_normalized)\n",
    "model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "num_epochs = 50\n",
    "\n",
    "\n",
    "# Gradually prune weights in dense and convolutional layers from 10% to 50% over the course of training, starting from epoch 0.\n",
    "\n",
    "\n",
    "rates = [0.4, 0.5, 0.6]\n",
    "idx = 20\n",
    "for r in rates:\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=0.01, final_pruning_factor=r, start_epoch=5, end_epoch=20, frequency=1)\n",
    "    model.fit(X_train_normalized_new, y_train, epochs=num_epochs, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import tensorflow as tf\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    from tensorflow.keras.models import Model\n",
    "    layers = model.layers\n",
    "    second_last_layer_output = layers[-4].output\n",
    "    feature_extractor_model = Model(inputs=model.input, outputs=second_last_layer_output)\n",
    "    train_features = feature_extractor_model.predict(X_train_normalized_new)\n",
    "    test_features = feature_extractor_model.predict(X_test_normalized_new)\n",
    "    \n",
    "    p_train = people_nums[train_idx,:]\n",
    "    p_val = people_nums[val_idx,:]\n",
    "    p_test = people_nums[test_idx,:]\n",
    "    ## Calculate the distance between test person and training person\n",
    "    def euclidean_distance(a, b):\n",
    "        return np.sqrt(np.sum((a - b) ** 2, axis=1))\n",
    "    \n",
    "    distance_dict = {}\n",
    "    for ii in range(len(person_nums)):\n",
    "        if person_nums[ii] == test_person_id[0]:\n",
    "            continue\n",
    "        else:\n",
    "            \n",
    "            ind = np.where(p_train ==person_nums[ii])[0]\n",
    "            tmp_train_features = train_features[ind, :]\n",
    "            distances = np.array([euclidean_distance(train_sample, test_features) for train_sample in tmp_train_features])\n",
    "            print(distances.shape)\n",
    "            average_distances = np.mean(distances, axis=1)\n",
    "    \n",
    "            # Step 4: Find the overall average distance\n",
    "            overall_average_distance = np.mean(average_distances)\n",
    "            distance_dict[person_nums[ii]] = overall_average_distance\n",
    "    \n",
    "    \n",
    "    def normalize_to_weights(distance_dict):\n",
    "        distances = np.array(list(distance_dict.values()))\n",
    "        # Handle the case where a distance is zero to avoid division by zero\n",
    "        distances = np.clip(distances, a_min=1e-10, a_max=None)\n",
    "        weights = 1 / distances\n",
    "        normalized_weights = weights\n",
    "        # normalized_weights = weights / sum(weights)\n",
    "        # print(sum(weights))\n",
    "        # print(sum(normalized_weights))\n",
    "        # Assign the normalized weights back to the dictionary\n",
    "        normalized_weight_dict = dict(zip(distance_dict.keys(), normalized_weights))\n",
    "        return normalized_weight_dict\n",
    "    def scale_dict_values(my_dict):\n",
    "        scaled_dict = my_dict.copy()\n",
    "        min_val = min(scaled_dict.values())\n",
    "        max_val = max(scaled_dict.values())\n",
    "        \n",
    "        for key in scaled_dict:\n",
    "            scaled_dict[key] = 1 + 9 * (scaled_dict[key] - min_val) / (max_val - min_val)\n",
    "        \n",
    "        return scaled_dict\n",
    "    weights_dict = normalize_to_weights(distance_dict)\n",
    "    weights_dict = scale_dict_values(weights_dict)\n",
    "    print(weights_dict)\n",
    "    \n",
    "    w_train = np.zeros_like(p_train)\n",
    "    for i in range(len(w_train)):\n",
    "        w_train[i] = weights_dict[int(p_train[i])]\n",
    "    \n",
    "    w_train = np.squeeze(w_train)\n",
    "    \n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,sample_weight= w_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    model_name = './checkpoints/unknown_person_baseline_2_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    idx += 1\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f71b59e4-6581-4ea8-994d-a02a6654ab6b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
