{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c77f8da1-2837-4bf7-b3f4-dfcaa7ab42f6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-08T17:59:18.035239Z",
     "iopub.status.busy": "2023-11-08T17:59:18.035104Z",
     "iopub.status.idle": "2023-11-08T17:59:18.122088Z",
     "shell.execute_reply": "2023-11-08T17:59:18.121488Z"
    }
   },
   "outputs": [],
   "source": [
    "import scipy.io\n",
    "import numpy as np\n",
    "import random\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3fe25376-b856-4296-ba02-5e3771ff9451",
   "metadata": {
    "collapsed": true,
    "execution": {
     "iopub.execute_input": "2023-11-08T17:59:18.124871Z",
     "iopub.status.busy": "2023-11-08T17:59:18.124689Z",
     "iopub.status.idle": "2023-11-08T19:47:14.664000Z",
     "shell.execute_reply": "2023-11-08T19:47:14.663463Z"
    },
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 12:59:18.302501: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/usr/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1, this may cause problems\n",
      "  _warn((\"h5py is running against HDF5 {0} when it was built against {1}, \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "35019\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "non-resource variables are not supported in the long term\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:00:41.405918: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.417268: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.417501: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.421579: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.421767: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.421931: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.494841: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.495041: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.495206: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:41.495345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:2d:00.0, compute capability: 8.6\n",
      "2023-11-08 13:00:41.495586: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:00:42.407587: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:42.407870: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:42.408073: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:42.408308: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:42.408503: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 13:00:42.408653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:2d:00.0, compute capability: 8.6\n",
      "2023-11-08 13:00:42.408691: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n",
      "2023-11-08 13:00:42.430254: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled\n",
      "2023-11-08 13:00:42.644372: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_21/lstm_cell_21/bias/Assign' id:3510 op device:{requested: '', assigned: ''} def:{{{node lstm_21/lstm_cell_21/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_21/lstm_cell_21/bias, lstm_21/lstm_cell_21/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 13:00:42.774572: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_1' id:3634 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_1}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 0 0 0...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 13:00:42.807302: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_2' id:3635 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_2}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 1 1 1...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "(31504, 95)\n",
      "Train on 31504 samples, validate on 3515 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:00:47.159666: W tensorflow/c/c_api.cc:304] Operation '{name:'training/Adam/conv2d_1/bias/v/Assign' id:17012 op device:{requested: '', assigned: ''} def:{{{node training/Adam/conv2d_1/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](training/Adam/conv2d_1/bias/v, training/Adam/conv2d_1/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:00:50.924716: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n",
      "2023-11-08 13:00:53.029944: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "2023-11-08 13:00:53.043590: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8902\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31504/31504 [==============================] - ETA: 0s - loss: 3.1051"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2335: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates = self.state_updates\n",
      "2023-11-08 13:01:15.764910: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_1/mul' id:6477 op device:{requested: '', assigned: ''} def:{{{node loss_1/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_1/mul/x, loss_1/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.92500, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 30s 949us/sample - loss: 3.1051 - val_loss: 1.9250\n",
      "Epoch 2/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.7777\n",
      "Epoch 2: val_loss improved from 1.92500 to 1.64635, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 21s 663us/sample - loss: 1.7777 - val_loss: 1.6464\n",
      "Epoch 3/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.5981\n",
      "Epoch 3: val_loss improved from 1.64635 to 1.59922, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 704us/sample - loss: 1.5981 - val_loss: 1.5992\n",
      "Epoch 4/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.5509\n",
      "Epoch 4: val_loss improved from 1.59922 to 1.57211, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 649us/sample - loss: 1.5509 - val_loss: 1.5721\n",
      "Epoch 5/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.5278\n",
      "Epoch 5: val_loss improved from 1.57211 to 1.56032, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 603us/sample - loss: 1.5278 - val_loss: 1.5603\n",
      "Epoch 6/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.5077\n",
      "Epoch 6: val_loss improved from 1.56032 to 1.54508, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 683us/sample - loss: 1.5077 - val_loss: 1.5451\n",
      "Epoch 7/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4968\n",
      "Epoch 7: val_loss improved from 1.54508 to 1.53546, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 705us/sample - loss: 1.4968 - val_loss: 1.5355\n",
      "Epoch 8/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4940\n",
      "Epoch 8: val_loss improved from 1.53546 to 1.53067, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 702us/sample - loss: 1.4940 - val_loss: 1.5307\n",
      "Epoch 9/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4860\n",
      "Epoch 9: val_loss improved from 1.53067 to 1.52682, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 21s 676us/sample - loss: 1.4860 - val_loss: 1.5268\n",
      "Epoch 10/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4805\n",
      "Epoch 10: val_loss improved from 1.52682 to 1.52657, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 622us/sample - loss: 1.4805 - val_loss: 1.5266\n",
      "Epoch 11/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4816\n",
      "Epoch 11: val_loss improved from 1.52657 to 1.52420, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 622us/sample - loss: 1.4816 - val_loss: 1.5242\n",
      "Epoch 12/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4744\n",
      "Epoch 12: val_loss improved from 1.52420 to 1.51859, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 630us/sample - loss: 1.4744 - val_loss: 1.5186\n",
      "Epoch 13/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4813\n",
      "Epoch 13: val_loss improved from 1.51859 to 1.51240, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 609us/sample - loss: 1.4813 - val_loss: 1.5124\n",
      "Epoch 14/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4721\n",
      "Epoch 14: val_loss improved from 1.51240 to 1.50757, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 614us/sample - loss: 1.4721 - val_loss: 1.5076\n",
      "Epoch 15/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4629\n",
      "Epoch 15: val_loss did not improve from 1.50757\n",
      "31504/31504 [==============================] - 19s 600us/sample - loss: 1.4629 - val_loss: 1.5109\n",
      "Epoch 16/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4653\n",
      "Epoch 16: val_loss improved from 1.50757 to 1.49536, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 607us/sample - loss: 1.4653 - val_loss: 1.4954\n",
      "Epoch 17/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4986\n",
      "Epoch 17: val_loss did not improve from 1.49536\n",
      "31504/31504 [==============================] - 19s 607us/sample - loss: 1.4986 - val_loss: 1.4972\n",
      "Epoch 18/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4720\n",
      "Epoch 18: val_loss did not improve from 1.49536\n",
      "31504/31504 [==============================] - 19s 614us/sample - loss: 1.4720 - val_loss: 1.5032\n",
      "Epoch 19/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4746\n",
      "Epoch 19: val_loss did not improve from 1.49536\n",
      "31504/31504 [==============================] - 19s 608us/sample - loss: 1.4746 - val_loss: 1.5034\n",
      "Epoch 20/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4635\n",
      "Epoch 20: val_loss improved from 1.49536 to 1.49426, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 612us/sample - loss: 1.4635 - val_loss: 1.4943\n",
      "Epoch 21/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.5380\n",
      "Epoch 21: val_loss did not improve from 1.49426\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 1.5380 - val_loss: 1.5296\n",
      "Epoch 22/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.6656\n",
      "Epoch 22: val_loss did not improve from 1.49426\n",
      "31504/31504 [==============================] - 19s 614us/sample - loss: 1.6656 - val_loss: 1.5318\n",
      "Epoch 23/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4959\n",
      "Epoch 23: val_loss did not improve from 1.49426\n",
      "31504/31504 [==============================] - 19s 618us/sample - loss: 1.4959 - val_loss: 1.5308\n",
      "Epoch 24/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4577\n",
      "Epoch 24: val_loss did not improve from 1.49426\n",
      "31504/31504 [==============================] - 19s 617us/sample - loss: 1.4577 - val_loss: 1.5015\n",
      "Epoch 25/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4440\n",
      "Epoch 25: val_loss improved from 1.49426 to 1.49308, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 1.4440 - val_loss: 1.4931\n",
      "Epoch 26/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4421\n",
      "Epoch 26: val_loss improved from 1.49308 to 1.48748, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 617us/sample - loss: 1.4421 - val_loss: 1.4875\n",
      "Epoch 27/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4381\n",
      "Epoch 27: val_loss improved from 1.48748 to 1.48349, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 624us/sample - loss: 1.4381 - val_loss: 1.4835\n",
      "Epoch 28/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4368\n",
      "Epoch 28: val_loss did not improve from 1.48349\n",
      "31504/31504 [==============================] - 19s 619us/sample - loss: 1.4368 - val_loss: 1.4868\n",
      "Epoch 29/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4326\n",
      "Epoch 29: val_loss did not improve from 1.48349\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 1.4326 - val_loss: 1.4855\n",
      "Epoch 30/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4270\n",
      "Epoch 30: val_loss improved from 1.48349 to 1.47622, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 624us/sample - loss: 1.4270 - val_loss: 1.4762\n",
      "Epoch 31/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4266\n",
      "Epoch 31: val_loss improved from 1.47622 to 1.47551, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 689us/sample - loss: 1.4266 - val_loss: 1.4755\n",
      "Epoch 32/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4238\n",
      "Epoch 32: val_loss did not improve from 1.47551\n",
      "31504/31504 [==============================] - 22s 701us/sample - loss: 1.4238 - val_loss: 1.4812\n",
      "Epoch 33/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4232\n",
      "Epoch 33: val_loss improved from 1.47551 to 1.46824, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 623us/sample - loss: 1.4232 - val_loss: 1.4682\n",
      "Epoch 34/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4187\n",
      "Epoch 34: val_loss improved from 1.46824 to 1.46458, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 609us/sample - loss: 1.4187 - val_loss: 1.4646\n",
      "Epoch 35/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4195\n",
      "Epoch 35: val_loss did not improve from 1.46458\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 1.4195 - val_loss: 1.4670\n",
      "Epoch 36/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4167\n",
      "Epoch 36: val_loss improved from 1.46458 to 1.46425, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 642us/sample - loss: 1.4167 - val_loss: 1.4643\n",
      "Epoch 37/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4160\n",
      "Epoch 37: val_loss improved from 1.46425 to 1.46207, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 703us/sample - loss: 1.4160 - val_loss: 1.4621\n",
      "Epoch 38/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4150\n",
      "Epoch 38: val_loss improved from 1.46207 to 1.45662, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 709us/sample - loss: 1.4150 - val_loss: 1.4566\n",
      "Epoch 39/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4149\n",
      "Epoch 39: val_loss improved from 1.45662 to 1.45649, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 641us/sample - loss: 1.4149 - val_loss: 1.4565\n",
      "Epoch 40/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4132\n",
      "Epoch 40: val_loss did not improve from 1.45649\n",
      "31504/31504 [==============================] - 22s 700us/sample - loss: 1.4132 - val_loss: 1.4618\n",
      "Epoch 41/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4136\n",
      "Epoch 41: val_loss did not improve from 1.45649\n",
      "31504/31504 [==============================] - 22s 701us/sample - loss: 1.4136 - val_loss: 1.4605\n",
      "Epoch 42/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4086\n",
      "Epoch 42: val_loss improved from 1.45649 to 1.44859, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 705us/sample - loss: 1.4086 - val_loss: 1.4486\n",
      "Epoch 43/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4068\n",
      "Epoch 43: val_loss did not improve from 1.44859\n",
      "31504/31504 [==============================] - 22s 697us/sample - loss: 1.4068 - val_loss: 1.4518\n",
      "Epoch 44/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4071\n",
      "Epoch 44: val_loss did not improve from 1.44859\n",
      "31504/31504 [==============================] - 22s 696us/sample - loss: 1.4071 - val_loss: 1.4600\n",
      "Epoch 45/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4038\n",
      "Epoch 45: val_loss did not improve from 1.44859\n",
      "31504/31504 [==============================] - 19s 594us/sample - loss: 1.4038 - val_loss: 1.4534\n",
      "Epoch 46/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4031\n",
      "Epoch 46: val_loss did not improve from 1.44859\n",
      "31504/31504 [==============================] - 20s 625us/sample - loss: 1.4031 - val_loss: 1.4540\n",
      "Epoch 47/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4011\n",
      "Epoch 47: val_loss did not improve from 1.44859\n",
      "31504/31504 [==============================] - 20s 619us/sample - loss: 1.4011 - val_loss: 1.4494\n",
      "Epoch 48/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4007\n",
      "Epoch 48: val_loss improved from 1.44859 to 1.44589, saving model to ./checkpoints/unknown_person_baseline_p10_20.h5\n",
      "31504/31504 [==============================] - 21s 670us/sample - loss: 1.4007 - val_loss: 1.4459\n",
      "Epoch 49/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3995\n",
      "Epoch 49: val_loss did not improve from 1.44589\n",
      "31504/31504 [==============================] - 22s 694us/sample - loss: 1.3995 - val_loss: 1.4480\n",
      "Epoch 50/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3969\n",
      "Epoch 50: val_loss did not improve from 1.44589\n",
      "31504/31504 [==============================] - 20s 636us/sample - loss: 1.3969 - val_loss: 1.4544\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:17:57.589663: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_10_1/lstm_cell_47/kernel/Assign' id:20240 op device:{requested: '', assigned: ''} def:{{{node lstm_10_1/lstm_cell_47/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_10_1/lstm_cell_47/kernel, lstm_10_1/lstm_cell_47/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 13:17:59.341902: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_33_1/lstm_cell_70/kernel/v/Assign' id:26390 op device:{requested: '', assigned: ''} def:{{{node lstm_33_1/lstm_cell_70/kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_33_1/lstm_cell_70/kernel/v, lstm_33_1/lstm_cell_70/kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates=self.state_updates,\n",
      "2023-11-08 13:18:00.727304: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_1/cond/Merge' id:24591 op device:{requested: '', assigned: ''} def:{{{node dropout_4_1/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_1/cond/Identity, dropout_4_1/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1982)\n",
      "(1514, 1982)\n",
      "(1644, 1982)\n",
      "(1764, 1982)\n",
      "(1836, 1982)\n",
      "(1699, 1982)\n",
      "(1369, 1982)\n",
      "(1582, 1982)\n",
      "(1764, 1982)\n",
      "(1562, 1982)\n",
      "(1920, 1982)\n",
      "(1667, 1982)\n",
      "(1776, 1982)\n",
      "(1872, 1982)\n",
      "(1704, 1982)\n",
      "(1812, 1982)\n",
      "(970, 1982)\n",
      "(1668, 1982)\n",
      "(1896, 1982)\n",
      "{1: 6.995399723270789, 2: 3.5235803771672667, 4: 9.304206165241782, 5: 7.99312927688163, 6: 6.241542240794003, 8: 9.07954876115181, 9: 4.759445512255858, 11: 6.448346849780378, 12: 9.304934608372742, 13: 7.888368069645497, 17: 9.255056048552317, 19: 8.583908532879903, 21: 10.0, 22: 1.0, 25: 7.978918697432832, 26: 6.869624515278501, 27: 3.4890288150724387, 28: 7.039231017425231, 29: 3.054225465025822}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_2792296/3198890485.py:300: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)\n",
      "  w_train[i] = weights_dict[int(p_train[i])]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31504 samples, validate on 3515 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:21:56.278667: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_5/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31504/31504 [==============================] - ETA: 0s - loss: 10.1530\n",
      "Epoch 1: val_loss improved from inf to 1.47561, saving model to ./checkpoints/unknown_person_p10_20.h5\n",
      "31504/31504 [==============================] - 26s 816us/sample - loss: 10.1530 - val_loss: 1.4756\n",
      "Epoch 2/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 10.0788\n",
      "Epoch 2: val_loss improved from 1.47561 to 1.45864, saving model to ./checkpoints/unknown_person_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 629us/sample - loss: 10.0788 - val_loss: 1.4586\n",
      "Epoch 3/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 10.0652\n",
      "Epoch 3: val_loss improved from 1.45864 to 1.44732, saving model to ./checkpoints/unknown_person_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 625us/sample - loss: 10.0652 - val_loss: 1.4473\n",
      "Epoch 4/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 10.0250\n",
      "Epoch 4: val_loss did not improve from 1.44732\n",
      "31504/31504 [==============================] - 19s 619us/sample - loss: 10.0250 - val_loss: 1.4586\n",
      "Epoch 5/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 10.0039\n",
      "Epoch 5: val_loss did not improve from 1.44732\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 10.0039 - val_loss: 1.4501\n",
      "Epoch 6/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.9595\n",
      "Epoch 6: val_loss did not improve from 1.44732\n",
      "31504/31504 [==============================] - 20s 624us/sample - loss: 9.9595 - val_loss: 1.4718\n",
      "Epoch 7/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.9494\n",
      "Epoch 7: val_loss did not improve from 1.44732\n",
      "31504/31504 [==============================] - 20s 626us/sample - loss: 9.9494 - val_loss: 1.4606\n",
      "Epoch 8/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.9230\n",
      "Epoch 8: val_loss improved from 1.44732 to 1.44337, saving model to ./checkpoints/unknown_person_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 632us/sample - loss: 9.9230 - val_loss: 1.4434\n",
      "Epoch 9/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8911\n",
      "Epoch 9: val_loss did not improve from 1.44337\n",
      "31504/31504 [==============================] - 19s 617us/sample - loss: 9.8911 - val_loss: 1.4492\n",
      "Epoch 10/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8897\n",
      "Epoch 10: val_loss did not improve from 1.44337\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 9.8897 - val_loss: 1.4475\n",
      "Epoch 11/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8734\n",
      "Epoch 11: val_loss did not improve from 1.44337\n",
      "31504/31504 [==============================] - 19s 619us/sample - loss: 9.8734 - val_loss: 1.4499\n",
      "Epoch 12/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8508\n",
      "Epoch 12: val_loss improved from 1.44337 to 1.43923, saving model to ./checkpoints/unknown_person_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 632us/sample - loss: 9.8508 - val_loss: 1.4392\n",
      "Epoch 13/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8608\n",
      "Epoch 13: val_loss did not improve from 1.43923\n",
      "31504/31504 [==============================] - 20s 621us/sample - loss: 9.8608 - val_loss: 1.4536\n",
      "Epoch 14/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8453\n",
      "Epoch 14: val_loss did not improve from 1.43923\n",
      "31504/31504 [==============================] - 20s 633us/sample - loss: 9.8453 - val_loss: 1.4536\n",
      "Epoch 15/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8223\n",
      "Epoch 15: val_loss improved from 1.43923 to 1.43840, saving model to ./checkpoints/unknown_person_p10_20.h5\n",
      "31504/31504 [==============================] - 20s 622us/sample - loss: 9.8223 - val_loss: 1.4384\n",
      "Epoch 16/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8321\n",
      "Epoch 16: val_loss did not improve from 1.43840\n",
      "31504/31504 [==============================] - 19s 618us/sample - loss: 9.8321 - val_loss: 1.4404\n",
      "Epoch 17/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8054\n",
      "Epoch 17: val_loss did not improve from 1.43840\n",
      "31504/31504 [==============================] - 20s 623us/sample - loss: 9.8054 - val_loss: 1.4506\n",
      "Epoch 18/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.7825\n",
      "Epoch 18: val_loss did not improve from 1.43840\n",
      "31504/31504 [==============================] - 20s 627us/sample - loss: 9.7825 - val_loss: 1.4565\n",
      "Epoch 19/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.7703\n",
      "Epoch 19: val_loss did not improve from 1.43840\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 9.7703 - val_loss: 1.4487\n",
      "Epoch 20/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.7679\n",
      "Epoch 20: val_loss improved from 1.43840 to 1.43602, saving model to ./checkpoints/unknown_person_p10_20.h5\n",
      "31504/31504 [==============================] - 21s 658us/sample - loss: 9.7679 - val_loss: 1.4360\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:28:38.117611: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_38/lstm_cell_74/bias/Assign' id:38067 op device:{requested: '', assigned: ''} def:{{{node lstm_38/lstm_cell_74/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_38/lstm_cell_74/bias, lstm_38/lstm_cell_74/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 13:28:40.565845: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_18_2/lstm_cell_92/kernel/m/Assign' id:44920 op device:{requested: '', assigned: ''} def:{{{node lstm_18_2/lstm_cell_92/kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_18_2/lstm_cell_92/kernel/m, lstm_18_2/lstm_cell_92/kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31504 samples, validate on 3515 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:28:45.677385: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:28:58.345967: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_6/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3999"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:29:18.969182: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.45328, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 27s 853us/sample - loss: 1.3999 - val_loss: 1.4533\n",
      "Epoch 2/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3983\n",
      "Epoch 2: val_loss improved from 1.45328 to 1.44636, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 21s 682us/sample - loss: 1.3983 - val_loss: 1.4464\n",
      "Epoch 3/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3985\n",
      "Epoch 3: val_loss improved from 1.44636 to 1.44231, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 21s 674us/sample - loss: 1.3985 - val_loss: 1.4423\n",
      "Epoch 4/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3972\n",
      "Epoch 4: val_loss did not improve from 1.44231\n",
      "31504/31504 [==============================] - 19s 611us/sample - loss: 1.3972 - val_loss: 1.4441\n",
      "Epoch 5/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3947\n",
      "Epoch 5: val_loss did not improve from 1.44231\n",
      "31504/31504 [==============================] - 19s 612us/sample - loss: 1.3947 - val_loss: 1.4474\n",
      "Epoch 6/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3943\n",
      "Epoch 6: val_loss did not improve from 1.44231\n",
      "31504/31504 [==============================] - 19s 608us/sample - loss: 1.3943 - val_loss: 1.4482\n",
      "Epoch 7/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3917\n",
      "Epoch 7: val_loss improved from 1.44231 to 1.43869, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 605us/sample - loss: 1.3917 - val_loss: 1.4387\n",
      "Epoch 8/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3889\n",
      "Epoch 8: val_loss improved from 1.43869 to 1.43852, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.3889 - val_loss: 1.4385\n",
      "Epoch 9/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3868\n",
      "Epoch 9: val_loss improved from 1.43852 to 1.43683, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 19s 617us/sample - loss: 1.3868 - val_loss: 1.4368\n",
      "Epoch 10/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3888\n",
      "Epoch 10: val_loss did not improve from 1.43683\n",
      "31504/31504 [==============================] - 19s 601us/sample - loss: 1.3888 - val_loss: 1.4385\n",
      "Epoch 11/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3871\n",
      "Epoch 11: val_loss did not improve from 1.43683\n",
      "31504/31504 [==============================] - 19s 602us/sample - loss: 1.3871 - val_loss: 1.4479\n",
      "Epoch 12/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3870\n",
      "Epoch 12: val_loss did not improve from 1.43683\n",
      "31504/31504 [==============================] - 19s 598us/sample - loss: 1.3870 - val_loss: 1.4395\n",
      "Epoch 13/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3852\n",
      "Epoch 13: val_loss did not improve from 1.43683\n",
      "31504/31504 [==============================] - 21s 656us/sample - loss: 1.3852 - val_loss: 1.4418\n",
      "Epoch 14/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3830\n",
      "Epoch 14: val_loss improved from 1.43683 to 1.43470, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 690us/sample - loss: 1.3830 - val_loss: 1.4347\n",
      "Epoch 15/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3824\n",
      "Epoch 15: val_loss did not improve from 1.43470\n",
      "31504/31504 [==============================] - 22s 685us/sample - loss: 1.3824 - val_loss: 1.4365\n",
      "Epoch 16/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3815\n",
      "Epoch 16: val_loss improved from 1.43470 to 1.43210, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 699us/sample - loss: 1.3815 - val_loss: 1.4321\n",
      "Epoch 17/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3820\n",
      "Epoch 17: val_loss did not improve from 1.43210\n",
      "31504/31504 [==============================] - 21s 652us/sample - loss: 1.3820 - val_loss: 1.4365\n",
      "Epoch 18/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3832\n",
      "Epoch 18: val_loss did not improve from 1.43210\n",
      "31504/31504 [==============================] - 19s 611us/sample - loss: 1.3832 - val_loss: 1.4438\n",
      "Epoch 19/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3799\n",
      "Epoch 19: val_loss did not improve from 1.43210\n",
      "31504/31504 [==============================] - 19s 613us/sample - loss: 1.3799 - val_loss: 1.4350\n",
      "Epoch 20/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3757\n",
      "Epoch 20: val_loss improved from 1.43210 to 1.42981, saving model to ./checkpoints/unknown_person_baseline_2_p10_20.h5\n",
      "31504/31504 [==============================] - 22s 693us/sample - loss: 1.3757 - val_loss: 1.4298\n",
      "Train on 31504 samples, validate on 3515 samples\n",
      "Epoch 1/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3782\n",
      "Epoch 1: val_loss improved from inf to 1.43637, saving model to ./checkpoints/unknown_person_baseline_p10_21.h5\n",
      "31504/31504 [==============================] - 22s 691us/sample - loss: 1.3782 - val_loss: 1.4364\n",
      "Epoch 2/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3765\n",
      "Epoch 2: val_loss improved from 1.43637 to 1.42722, saving model to ./checkpoints/unknown_person_baseline_p10_21.h5\n",
      "31504/31504 [==============================] - 22s 692us/sample - loss: 1.3765 - val_loss: 1.4272\n",
      "Epoch 3/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3769\n",
      "Epoch 3: val_loss did not improve from 1.42722\n",
      "31504/31504 [==============================] - 22s 687us/sample - loss: 1.3769 - val_loss: 1.4281\n",
      "Epoch 4/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3734\n",
      "Epoch 4: val_loss did not improve from 1.42722\n",
      "31504/31504 [==============================] - 19s 613us/sample - loss: 1.3734 - val_loss: 1.4342\n",
      "Epoch 5/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3729\n",
      "Epoch 5: val_loss did not improve from 1.42722\n",
      "31504/31504 [==============================] - 19s 607us/sample - loss: 1.3729 - val_loss: 1.4332\n",
      "Epoch 6/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3689\n",
      "Epoch 6: val_loss did not improve from 1.42722\n",
      "31504/31504 [==============================] - 19s 609us/sample - loss: 1.3689 - val_loss: 1.4299\n",
      "Epoch 7/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3685\n",
      "Epoch 7: val_loss improved from 1.42722 to 1.42204, saving model to ./checkpoints/unknown_person_baseline_p10_21.h5\n",
      "31504/31504 [==============================] - 19s 618us/sample - loss: 1.3685 - val_loss: 1.4220\n",
      "Epoch 8/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3780\n",
      "Epoch 8: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.3780 - val_loss: 1.4312\n",
      "Epoch 9/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3924\n",
      "Epoch 9: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 607us/sample - loss: 1.3924 - val_loss: 1.4421\n",
      "Epoch 10/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3836\n",
      "Epoch 10: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.3836 - val_loss: 1.4334\n",
      "Epoch 11/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3854\n",
      "Epoch 11: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 610us/sample - loss: 1.3854 - val_loss: 1.4419\n",
      "Epoch 12/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3892\n",
      "Epoch 12: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 20s 638us/sample - loss: 1.3892 - val_loss: 1.4431\n",
      "Epoch 13/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4347\n",
      "Epoch 13: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 651us/sample - loss: 1.4347 - val_loss: 1.4442\n",
      "Epoch 14/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3842\n",
      "Epoch 14: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 684us/sample - loss: 1.3842 - val_loss: 1.4323\n",
      "Epoch 15/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3863\n",
      "Epoch 15: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 687us/sample - loss: 1.3863 - val_loss: 1.4352\n",
      "Epoch 16/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3901\n",
      "Epoch 16: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 20s 619us/sample - loss: 1.3901 - val_loss: 1.4364\n",
      "Epoch 17/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4060\n",
      "Epoch 17: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 659us/sample - loss: 1.4060 - val_loss: 1.4353\n",
      "Epoch 18/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3961\n",
      "Epoch 18: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 20s 624us/sample - loss: 1.3961 - val_loss: 1.4418\n",
      "Epoch 19/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4177\n",
      "Epoch 19: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 20s 623us/sample - loss: 1.4177 - val_loss: 1.4422\n",
      "Epoch 20/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4218\n",
      "Epoch 20: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 593us/sample - loss: 1.4218 - val_loss: 1.4449\n",
      "Epoch 21/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4712\n",
      "Epoch 21: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 597us/sample - loss: 1.4712 - val_loss: 1.4576\n",
      "Epoch 22/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4277\n",
      "Epoch 22: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 651us/sample - loss: 1.4277 - val_loss: 1.4522\n",
      "Epoch 23/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4147\n",
      "Epoch 23: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 691us/sample - loss: 1.4147 - val_loss: 1.4542\n",
      "Epoch 24/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4079\n",
      "Epoch 24: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 665us/sample - loss: 1.4079 - val_loss: 1.4534\n",
      "Epoch 25/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3987\n",
      "Epoch 25: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 687us/sample - loss: 1.3987 - val_loss: 1.4470\n",
      "Epoch 26/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4004\n",
      "Epoch 26: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 691us/sample - loss: 1.4004 - val_loss: 1.4454\n",
      "Epoch 27/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3952\n",
      "Epoch 27: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 20s 641us/sample - loss: 1.3952 - val_loss: 1.4469\n",
      "Epoch 28/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3972\n",
      "Epoch 28: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 656us/sample - loss: 1.3972 - val_loss: 1.4467\n",
      "Epoch 29/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3927\n",
      "Epoch 29: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 674us/sample - loss: 1.3927 - val_loss: 1.4515\n",
      "Epoch 30/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3902\n",
      "Epoch 30: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 602us/sample - loss: 1.3902 - val_loss: 1.4414\n",
      "Epoch 31/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3883\n",
      "Epoch 31: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 595us/sample - loss: 1.3883 - val_loss: 1.4444\n",
      "Epoch 32/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3860\n",
      "Epoch 32: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 600us/sample - loss: 1.3860 - val_loss: 1.4423\n",
      "Epoch 33/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3884\n",
      "Epoch 33: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 19s 601us/sample - loss: 1.3884 - val_loss: 1.4363\n",
      "Epoch 34/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3852\n",
      "Epoch 34: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 20s 639us/sample - loss: 1.3852 - val_loss: 1.4360\n",
      "Epoch 35/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3844\n",
      "Epoch 35: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 20s 623us/sample - loss: 1.3844 - val_loss: 1.4395\n",
      "Epoch 36/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3824\n",
      "Epoch 36: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 691us/sample - loss: 1.3824 - val_loss: 1.4434\n",
      "Epoch 37/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3808\n",
      "Epoch 37: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 692us/sample - loss: 1.3808 - val_loss: 1.4358\n",
      "Epoch 38/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3787\n",
      "Epoch 38: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 689us/sample - loss: 1.3787 - val_loss: 1.4382\n",
      "Epoch 39/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3791\n",
      "Epoch 39: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 696us/sample - loss: 1.3791 - val_loss: 1.4407\n",
      "Epoch 40/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3764\n",
      "Epoch 40: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 695us/sample - loss: 1.3764 - val_loss: 1.4388\n",
      "Epoch 41/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3783\n",
      "Epoch 41: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 694us/sample - loss: 1.3783 - val_loss: 1.4316\n",
      "Epoch 42/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3764\n",
      "Epoch 42: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 685us/sample - loss: 1.3764 - val_loss: 1.4331\n",
      "Epoch 43/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3742\n",
      "Epoch 43: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 688us/sample - loss: 1.3742 - val_loss: 1.4344\n",
      "Epoch 44/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3721\n",
      "Epoch 44: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 690us/sample - loss: 1.3721 - val_loss: 1.4414\n",
      "Epoch 45/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3726\n",
      "Epoch 45: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 689us/sample - loss: 1.3726 - val_loss: 1.4389\n",
      "Epoch 46/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3734\n",
      "Epoch 46: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 685us/sample - loss: 1.3734 - val_loss: 1.4344\n",
      "Epoch 47/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3692\n",
      "Epoch 47: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 687us/sample - loss: 1.3692 - val_loss: 1.4289\n",
      "Epoch 48/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3709\n",
      "Epoch 48: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 672us/sample - loss: 1.3709 - val_loss: 1.4270\n",
      "Epoch 49/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3679\n",
      "Epoch 49: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 21s 659us/sample - loss: 1.3679 - val_loss: 1.4322\n",
      "Epoch 50/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3679\n",
      "Epoch 50: val_loss did not improve from 1.42204\n",
      "31504/31504 [==============================] - 22s 686us/sample - loss: 1.3679 - val_loss: 1.4294\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:52:57.028401: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_2_3/lstm_cell_113/recurrent_kernel/Assign' id:57738 op device:{requested: '', assigned: ''} def:{{{node lstm_2_3/lstm_cell_113/recurrent_kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_2_3/lstm_cell_113/recurrent_kernel, lstm_2_3/lstm_cell_113/recurrent_kernel/Initializer/mul_1)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 13:53:00.258446: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_8_3/lstm_cell_119/bias/v/Assign' id:64783 op device:{requested: '', assigned: ''} def:{{{node lstm_8_3/lstm_cell_119/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_8_3/lstm_cell_119/bias/v, lstm_8_3/lstm_cell_119/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 13:53:03.348348: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_3/cond/Merge' id:63349 op device:{requested: '', assigned: ''} def:{{{node dropout_4_3/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_3/cond/Identity, dropout_4_3/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1982)\n",
      "(1514, 1982)\n",
      "(1644, 1982)\n",
      "(1764, 1982)\n",
      "(1836, 1982)\n",
      "(1699, 1982)\n",
      "(1369, 1982)\n",
      "(1582, 1982)\n",
      "(1764, 1982)\n",
      "(1562, 1982)\n",
      "(1920, 1982)\n",
      "(1667, 1982)\n",
      "(1776, 1982)\n",
      "(1872, 1982)\n",
      "(1704, 1982)\n",
      "(1812, 1982)\n",
      "(970, 1982)\n",
      "(1668, 1982)\n",
      "(1896, 1982)\n",
      "{1: 7.089187627394298, 2: 3.8096743539602427, 4: 9.070028787631163, 5: 7.921796344872364, 6: 5.978188760869108, 8: 9.202830716453168, 9: 5.173393906768152, 11: 6.198799330244836, 12: 9.17183285598908, 13: 7.511064446804571, 17: 9.080707939943949, 19: 8.207396598499127, 21: 10.0, 22: 1.0, 25: 7.6801982230186985, 26: 6.766830745020334, 27: 3.7417298309848395, 28: 6.495134628467948, 29: 3.000525490969722}\n",
      "Train on 31504 samples, validate on 3515 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 13:57:28.154161: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_7/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31504/31504 [==============================] - ETA: 0s - loss: 9.8580\n",
      "Epoch 1: val_loss improved from inf to 1.45978, saving model to ./checkpoints/unknown_person_p10_21.h5\n",
      "31504/31504 [==============================] - 32s 1ms/sample - loss: 9.8580 - val_loss: 1.4598\n",
      "Epoch 2/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.7792\n",
      "Epoch 2: val_loss improved from 1.45978 to 1.43144, saving model to ./checkpoints/unknown_person_p10_21.h5\n",
      "31504/31504 [==============================] - 22s 712us/sample - loss: 9.7792 - val_loss: 1.4314\n",
      "Epoch 3/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.7394\n",
      "Epoch 3: val_loss improved from 1.43144 to 1.42625, saving model to ./checkpoints/unknown_person_p10_21.h5\n",
      "31504/31504 [==============================] - 21s 669us/sample - loss: 9.7394 - val_loss: 1.4263\n",
      "Epoch 4/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6864\n",
      "Epoch 4: val_loss did not improve from 1.42625\n",
      "31504/31504 [==============================] - 21s 668us/sample - loss: 9.6864 - val_loss: 1.4508\n",
      "Epoch 5/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6877\n",
      "Epoch 5: val_loss did not improve from 1.42625\n",
      "31504/31504 [==============================] - 19s 611us/sample - loss: 9.6877 - val_loss: 1.4377\n",
      "Epoch 6/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6549\n",
      "Epoch 6: val_loss improved from 1.42625 to 1.42254, saving model to ./checkpoints/unknown_person_p10_21.h5\n",
      "31504/31504 [==============================] - 19s 619us/sample - loss: 9.6549 - val_loss: 1.4225\n",
      "Epoch 7/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6351\n",
      "Epoch 7: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 20s 647us/sample - loss: 9.6351 - val_loss: 1.4267\n",
      "Epoch 8/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6487\n",
      "Epoch 8: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 22s 703us/sample - loss: 9.6487 - val_loss: 1.4299\n",
      "Epoch 9/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6212\n",
      "Epoch 9: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 21s 659us/sample - loss: 9.6212 - val_loss: 1.4288\n",
      "Epoch 10/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6049\n",
      "Epoch 10: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 22s 699us/sample - loss: 9.6049 - val_loss: 1.4458\n",
      "Epoch 11/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5881\n",
      "Epoch 11: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 22s 701us/sample - loss: 9.5881 - val_loss: 1.4312\n",
      "Epoch 12/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5573\n",
      "Epoch 12: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 20s 644us/sample - loss: 9.5573 - val_loss: 1.4295\n",
      "Epoch 13/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5838\n",
      "Epoch 13: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 22s 701us/sample - loss: 9.5838 - val_loss: 1.4436\n",
      "Epoch 14/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5515\n",
      "Epoch 14: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 22s 712us/sample - loss: 9.5515 - val_loss: 1.4279\n",
      "Epoch 15/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5613\n",
      "Epoch 15: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 22s 705us/sample - loss: 9.5613 - val_loss: 1.4504\n",
      "Epoch 16/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5527\n",
      "Epoch 16: val_loss did not improve from 1.42254\n",
      "31504/31504 [==============================] - 22s 705us/sample - loss: 9.5527 - val_loss: 1.4257\n",
      "Epoch 17/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5121\n",
      "Epoch 17: val_loss improved from 1.42254 to 1.42049, saving model to ./checkpoints/unknown_person_p10_21.h5\n",
      "31504/31504 [==============================] - 22s 714us/sample - loss: 9.5121 - val_loss: 1.4205\n",
      "Epoch 18/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5259\n",
      "Epoch 18: val_loss did not improve from 1.42049\n",
      "31504/31504 [==============================] - 22s 708us/sample - loss: 9.5259 - val_loss: 1.4217\n",
      "Epoch 19/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4917\n",
      "Epoch 19: val_loss did not improve from 1.42049\n",
      "31504/31504 [==============================] - 22s 706us/sample - loss: 9.4917 - val_loss: 1.4262\n",
      "Epoch 20/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4988\n",
      "Epoch 20: val_loss did not improve from 1.42049\n",
      "31504/31504 [==============================] - 22s 705us/sample - loss: 9.4988 - val_loss: 1.4401\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:04:51.270923: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_10_4/lstm_cell_158/bias/Assign' id:78425 op device:{requested: '', assigned: ''} def:{{{node lstm_10_4/lstm_cell_158/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_10_4/lstm_cell_158/bias, lstm_10_4/lstm_cell_158/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 14:04:55.515957: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_29_4/lstm_cell_177/bias/v/Assign' id:84496 op device:{requested: '', assigned: ''} def:{{{node lstm_29_4/lstm_cell_177/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_29_4/lstm_cell_177/bias/v, lstm_29_4/lstm_cell_177/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31504 samples, validate on 3515 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:05:02.278193: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:05:24.418452: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_8/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3767"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:05:47.906401: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.42934, saving model to ./checkpoints/unknown_person_baseline_2_p10_21.h5\n",
      "31504/31504 [==============================] - 33s 1ms/sample - loss: 1.3767 - val_loss: 1.4293\n",
      "Epoch 2/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3704\n",
      "Epoch 2: val_loss improved from 1.42934 to 1.42549, saving model to ./checkpoints/unknown_person_baseline_2_p10_21.h5\n",
      "31504/31504 [==============================] - 21s 659us/sample - loss: 1.3704 - val_loss: 1.4255\n",
      "Epoch 3/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3731\n",
      "Epoch 3: val_loss did not improve from 1.42549\n",
      "31504/31504 [==============================] - 19s 598us/sample - loss: 1.3731 - val_loss: 1.4370\n",
      "Epoch 4/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3704\n",
      "Epoch 4: val_loss did not improve from 1.42549\n",
      "31504/31504 [==============================] - 19s 594us/sample - loss: 1.3704 - val_loss: 1.4302\n",
      "Epoch 5/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3705\n",
      "Epoch 5: val_loss did not improve from 1.42549\n",
      "31504/31504 [==============================] - 19s 595us/sample - loss: 1.3705 - val_loss: 1.4430\n",
      "Epoch 6/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3690\n",
      "Epoch 6: val_loss improved from 1.42549 to 1.42342, saving model to ./checkpoints/unknown_person_baseline_2_p10_21.h5\n",
      "31504/31504 [==============================] - 22s 694us/sample - loss: 1.3690 - val_loss: 1.4234\n",
      "Epoch 7/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3658\n",
      "Epoch 7: val_loss did not improve from 1.42342\n",
      "31504/31504 [==============================] - 21s 653us/sample - loss: 1.3658 - val_loss: 1.4290\n",
      "Epoch 8/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3641\n",
      "Epoch 8: val_loss did not improve from 1.42342\n",
      "31504/31504 [==============================] - 19s 608us/sample - loss: 1.3641 - val_loss: 1.4310\n",
      "Epoch 9/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3632\n",
      "Epoch 9: val_loss did not improve from 1.42342\n",
      "31504/31504 [==============================] - 19s 601us/sample - loss: 1.3632 - val_loss: 1.4292\n",
      "Epoch 10/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3640\n",
      "Epoch 10: val_loss did not improve from 1.42342\n",
      "31504/31504 [==============================] - 20s 643us/sample - loss: 1.3640 - val_loss: 1.4267\n",
      "Epoch 11/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3628\n",
      "Epoch 11: val_loss did not improve from 1.42342\n",
      "31504/31504 [==============================] - 20s 638us/sample - loss: 1.3628 - val_loss: 1.4298\n",
      "Epoch 12/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3608\n",
      "Epoch 12: val_loss did not improve from 1.42342\n",
      "31504/31504 [==============================] - 19s 609us/sample - loss: 1.3608 - val_loss: 1.4309\n",
      "Epoch 13/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3624\n",
      "Epoch 13: val_loss improved from 1.42342 to 1.41903, saving model to ./checkpoints/unknown_person_baseline_2_p10_21.h5\n",
      "31504/31504 [==============================] - 19s 615us/sample - loss: 1.3624 - val_loss: 1.4190\n",
      "Epoch 14/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3626\n",
      "Epoch 14: val_loss did not improve from 1.41903\n",
      "31504/31504 [==============================] - 20s 622us/sample - loss: 1.3626 - val_loss: 1.4233\n",
      "Epoch 15/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3583\n",
      "Epoch 15: val_loss did not improve from 1.41903\n",
      "31504/31504 [==============================] - 19s 613us/sample - loss: 1.3583 - val_loss: 1.4231\n",
      "Epoch 16/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3595\n",
      "Epoch 16: val_loss did not improve from 1.41903\n",
      "31504/31504 [==============================] - 20s 632us/sample - loss: 1.3595 - val_loss: 1.4191\n",
      "Epoch 17/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3586\n",
      "Epoch 17: val_loss did not improve from 1.41903\n",
      "31504/31504 [==============================] - 20s 625us/sample - loss: 1.3586 - val_loss: 1.4316\n",
      "Epoch 18/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3548\n",
      "Epoch 18: val_loss did not improve from 1.41903\n",
      "31504/31504 [==============================] - 19s 618us/sample - loss: 1.3548 - val_loss: 1.4234\n",
      "Epoch 19/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3558\n",
      "Epoch 19: val_loss improved from 1.41903 to 1.41786, saving model to ./checkpoints/unknown_person_baseline_2_p10_21.h5\n",
      "31504/31504 [==============================] - 19s 614us/sample - loss: 1.3558 - val_loss: 1.4179\n",
      "Epoch 20/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3561\n",
      "Epoch 20: val_loss did not improve from 1.41786\n",
      "31504/31504 [==============================] - 19s 615us/sample - loss: 1.3561 - val_loss: 1.4280\n",
      "Train on 31504 samples, validate on 3515 samples\n",
      "Epoch 1/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3546\n",
      "Epoch 1: val_loss improved from inf to 1.42303, saving model to ./checkpoints/unknown_person_baseline_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 619us/sample - loss: 1.3546 - val_loss: 1.4230\n",
      "Epoch 2/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3551\n",
      "Epoch 2: val_loss improved from 1.42303 to 1.42081, saving model to ./checkpoints/unknown_person_baseline_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 612us/sample - loss: 1.3551 - val_loss: 1.4208\n",
      "Epoch 3/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3538\n",
      "Epoch 3: val_loss did not improve from 1.42081\n",
      "31504/31504 [==============================] - 19s 609us/sample - loss: 1.3538 - val_loss: 1.4237\n",
      "Epoch 4/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3520\n",
      "Epoch 4: val_loss improved from 1.42081 to 1.41709, saving model to ./checkpoints/unknown_person_baseline_p10_22.h5\n",
      "31504/31504 [==============================] - 20s 627us/sample - loss: 1.3520 - val_loss: 1.4171\n",
      "Epoch 5/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3515\n",
      "Epoch 5: val_loss improved from 1.41709 to 1.41673, saving model to ./checkpoints/unknown_person_baseline_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 615us/sample - loss: 1.3515 - val_loss: 1.4167\n",
      "Epoch 6/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3472\n",
      "Epoch 6: val_loss improved from 1.41673 to 1.41651, saving model to ./checkpoints/unknown_person_baseline_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 617us/sample - loss: 1.3472 - val_loss: 1.4165\n",
      "Epoch 7/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3441\n",
      "Epoch 7: val_loss improved from 1.41651 to 1.41019, saving model to ./checkpoints/unknown_person_baseline_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 606us/sample - loss: 1.3441 - val_loss: 1.4102\n",
      "Epoch 8/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3553\n",
      "Epoch 8: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 617us/sample - loss: 1.3553 - val_loss: 1.4220\n",
      "Epoch 9/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4286\n",
      "Epoch 9: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 616us/sample - loss: 1.4286 - val_loss: 1.4277\n",
      "Epoch 10/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3922\n",
      "Epoch 10: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.3922 - val_loss: 1.4206\n",
      "Epoch 11/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3656\n",
      "Epoch 11: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 22s 687us/sample - loss: 1.3656 - val_loss: 1.4278\n",
      "Epoch 12/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3716\n",
      "Epoch 12: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 22s 693us/sample - loss: 1.3716 - val_loss: 1.4261\n",
      "Epoch 13/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3988\n",
      "Epoch 13: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 648us/sample - loss: 1.3988 - val_loss: 1.4331\n",
      "Epoch 14/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3821\n",
      "Epoch 14: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 21s 676us/sample - loss: 1.3821 - val_loss: 1.4285\n",
      "Epoch 15/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3926\n",
      "Epoch 15: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 21s 656us/sample - loss: 1.3926 - val_loss: 1.4311\n",
      "Epoch 16/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3920\n",
      "Epoch 16: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 22s 684us/sample - loss: 1.3920 - val_loss: 1.4275\n",
      "Epoch 17/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3992\n",
      "Epoch 17: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 1.3992 - val_loss: 1.4444\n",
      "Epoch 18/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4019\n",
      "Epoch 18: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 624us/sample - loss: 1.4019 - val_loss: 1.4451\n",
      "Epoch 19/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4020\n",
      "Epoch 19: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 641us/sample - loss: 1.4020 - val_loss: 1.4414\n",
      "Epoch 20/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4218\n",
      "Epoch 20: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 638us/sample - loss: 1.4218 - val_loss: 1.4375\n",
      "Epoch 21/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4195\n",
      "Epoch 21: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 619us/sample - loss: 1.4195 - val_loss: 1.4441\n",
      "Epoch 22/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4300\n",
      "Epoch 22: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 607us/sample - loss: 1.4300 - val_loss: 1.4476\n",
      "Epoch 23/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.5596\n",
      "Epoch 23: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 613us/sample - loss: 1.5596 - val_loss: 1.5215\n",
      "Epoch 24/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4866\n",
      "Epoch 24: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 607us/sample - loss: 1.4866 - val_loss: 1.4906\n",
      "Epoch 25/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4449\n",
      "Epoch 25: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 608us/sample - loss: 1.4449 - val_loss: 1.4709\n",
      "Epoch 26/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4249\n",
      "Epoch 26: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 607us/sample - loss: 1.4249 - val_loss: 1.4611\n",
      "Epoch 27/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4201\n",
      "Epoch 27: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 608us/sample - loss: 1.4201 - val_loss: 1.4580\n",
      "Epoch 28/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4210\n",
      "Epoch 28: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 609us/sample - loss: 1.4210 - val_loss: 1.4607\n",
      "Epoch 29/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4154\n",
      "Epoch 29: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 596us/sample - loss: 1.4154 - val_loss: 1.4602\n",
      "Epoch 30/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4151\n",
      "Epoch 30: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 605us/sample - loss: 1.4151 - val_loss: 1.4554\n",
      "Epoch 31/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4090\n",
      "Epoch 31: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.4090 - val_loss: 1.4576\n",
      "Epoch 32/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4087\n",
      "Epoch 32: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 602us/sample - loss: 1.4087 - val_loss: 1.4557\n",
      "Epoch 33/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4085\n",
      "Epoch 33: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 601us/sample - loss: 1.4085 - val_loss: 1.4516\n",
      "Epoch 34/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4026\n",
      "Epoch 34: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.4026 - val_loss: 1.4511\n",
      "Epoch 35/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4001\n",
      "Epoch 35: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.4001 - val_loss: 1.4492\n",
      "Epoch 36/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4053\n",
      "Epoch 36: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 613us/sample - loss: 1.4053 - val_loss: 1.4441\n",
      "Epoch 37/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4011\n",
      "Epoch 37: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 618us/sample - loss: 1.4011 - val_loss: 1.4419\n",
      "Epoch 38/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.4024\n",
      "Epoch 38: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 621us/sample - loss: 1.4024 - val_loss: 1.4448\n",
      "Epoch 39/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3969\n",
      "Epoch 39: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 619us/sample - loss: 1.3969 - val_loss: 1.4469\n",
      "Epoch 40/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3989\n",
      "Epoch 40: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 604us/sample - loss: 1.3989 - val_loss: 1.4558\n",
      "Epoch 41/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3963\n",
      "Epoch 41: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 603us/sample - loss: 1.3963 - val_loss: 1.4422\n",
      "Epoch 42/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3975\n",
      "Epoch 42: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 605us/sample - loss: 1.3975 - val_loss: 1.4422\n",
      "Epoch 43/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3945\n",
      "Epoch 43: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 21s 676us/sample - loss: 1.3945 - val_loss: 1.4357\n",
      "Epoch 44/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3918\n",
      "Epoch 44: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 22s 697us/sample - loss: 1.3918 - val_loss: 1.4517\n",
      "Epoch 45/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3923\n",
      "Epoch 45: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 21s 674us/sample - loss: 1.3923 - val_loss: 1.4401\n",
      "Epoch 46/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3892\n",
      "Epoch 46: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 617us/sample - loss: 1.3892 - val_loss: 1.4313\n",
      "Epoch 47/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3897\n",
      "Epoch 47: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 614us/sample - loss: 1.3897 - val_loss: 1.4347\n",
      "Epoch 48/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3871\n",
      "Epoch 48: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 613us/sample - loss: 1.3871 - val_loss: 1.4295\n",
      "Epoch 49/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3873\n",
      "Epoch 49: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 19s 613us/sample - loss: 1.3873 - val_loss: 1.4395\n",
      "Epoch 50/50\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3845\n",
      "Epoch 50: val_loss did not improve from 1.41019\n",
      "31504/31504 [==============================] - 20s 626us/sample - loss: 1.3845 - val_loss: 1.4372\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:28:37.155560: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_12_5/lstm_cell_197/recurrent_kernel/Assign' id:98096 op device:{requested: '', assigned: ''} def:{{{node lstm_12_5/lstm_cell_197/recurrent_kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_12_5/lstm_cell_197/recurrent_kernel, lstm_12_5/lstm_cell_197/recurrent_kernel/Initializer/mul_1)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 14:28:42.166389: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_1_5/lstm_cell_186/bias/m/Assign' id:102793 op device:{requested: '', assigned: ''} def:{{{node lstm_1_5/lstm_cell_186/bias/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_1_5/lstm_cell_186/bias/m, lstm_1_5/lstm_cell_186/bias/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 14:28:47.002652: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_5/cond/Merge' id:102107 op device:{requested: '', assigned: ''} def:{{{node dropout_4_5/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_5/cond/Identity, dropout_4_5/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1982)\n",
      "(1514, 1982)\n",
      "(1644, 1982)\n",
      "(1764, 1982)\n",
      "(1836, 1982)\n",
      "(1699, 1982)\n",
      "(1369, 1982)\n",
      "(1582, 1982)\n",
      "(1764, 1982)\n",
      "(1562, 1982)\n",
      "(1920, 1982)\n",
      "(1667, 1982)\n",
      "(1776, 1982)\n",
      "(1872, 1982)\n",
      "(1704, 1982)\n",
      "(1812, 1982)\n",
      "(970, 1982)\n",
      "(1668, 1982)\n",
      "(1896, 1982)\n",
      "{1: 6.8908538596174385, 2: 3.9609144045258042, 4: 9.084037539603091, 5: 7.657317452848175, 6: 5.586247895971201, 8: 9.256889712226267, 9: 5.468395256135258, 11: 5.95205852269418, 12: 9.294221059940256, 13: 7.347484991575504, 17: 9.220024110692972, 19: 8.03493012550215, 21: 10.0, 22: 1.0, 25: 7.735393106118476, 26: 6.845895211090081, 27: 3.5830943145443963, 28: 6.647945541847388, 29: 2.4819798340074746}\n",
      "Train on 31504 samples, validate on 3515 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:32:29.942613: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_9/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6811\n",
      "Epoch 1: val_loss improved from inf to 1.45876, saving model to ./checkpoints/unknown_person_p10_22.h5\n",
      "31504/31504 [==============================] - 34s 1ms/sample - loss: 9.6811 - val_loss: 1.4588\n",
      "Epoch 2/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.6224\n",
      "Epoch 2: val_loss improved from 1.45876 to 1.42854, saving model to ./checkpoints/unknown_person_p10_22.h5\n",
      "31504/31504 [==============================] - 20s 632us/sample - loss: 9.6224 - val_loss: 1.4285\n",
      "Epoch 3/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.7682\n",
      "Epoch 3: val_loss did not improve from 1.42854\n",
      "31504/31504 [==============================] - 20s 621us/sample - loss: 9.7682 - val_loss: 1.4498\n",
      "Epoch 4/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.5798\n",
      "Epoch 4: val_loss improved from 1.42854 to 1.41959, saving model to ./checkpoints/unknown_person_p10_22.h5\n",
      "31504/31504 [==============================] - 20s 619us/sample - loss: 9.5798 - val_loss: 1.4196\n",
      "Epoch 5/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4969\n",
      "Epoch 5: val_loss did not improve from 1.41959\n",
      "31504/31504 [==============================] - 19s 616us/sample - loss: 9.4969 - val_loss: 1.4355\n",
      "Epoch 6/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4889\n",
      "Epoch 6: val_loss did not improve from 1.41959\n",
      "31504/31504 [==============================] - 19s 615us/sample - loss: 9.4889 - val_loss: 1.4282\n",
      "Epoch 7/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4756\n",
      "Epoch 7: val_loss did not improve from 1.41959\n",
      "31504/31504 [==============================] - 20s 622us/sample - loss: 9.4756 - val_loss: 1.4294\n",
      "Epoch 8/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4640\n",
      "Epoch 8: val_loss did not improve from 1.41959\n",
      "31504/31504 [==============================] - 22s 688us/sample - loss: 9.4640 - val_loss: 1.4251\n",
      "Epoch 9/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4367\n",
      "Epoch 9: val_loss did not improve from 1.41959\n",
      "31504/31504 [==============================] - 22s 704us/sample - loss: 9.4367 - val_loss: 1.4236\n",
      "Epoch 10/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4239\n",
      "Epoch 10: val_loss did not improve from 1.41959\n",
      "31504/31504 [==============================] - 22s 704us/sample - loss: 9.4239 - val_loss: 1.4294\n",
      "Epoch 11/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3996\n",
      "Epoch 11: val_loss did not improve from 1.41959\n",
      "31504/31504 [==============================] - 22s 700us/sample - loss: 9.3996 - val_loss: 1.4213\n",
      "Epoch 12/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.4152\n",
      "Epoch 12: val_loss improved from 1.41959 to 1.41871, saving model to ./checkpoints/unknown_person_p10_22.h5\n",
      "31504/31504 [==============================] - 22s 709us/sample - loss: 9.4152 - val_loss: 1.4187\n",
      "Epoch 13/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3932\n",
      "Epoch 13: val_loss did not improve from 1.41871\n",
      "31504/31504 [==============================] - 22s 704us/sample - loss: 9.3932 - val_loss: 1.4291\n",
      "Epoch 14/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3885\n",
      "Epoch 14: val_loss did not improve from 1.41871\n",
      "31504/31504 [==============================] - 22s 703us/sample - loss: 9.3885 - val_loss: 1.4386\n",
      "Epoch 15/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3845\n",
      "Epoch 15: val_loss did not improve from 1.41871\n",
      "31504/31504 [==============================] - 21s 677us/sample - loss: 9.3845 - val_loss: 1.4345\n",
      "Epoch 16/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3681\n",
      "Epoch 16: val_loss did not improve from 1.41871\n",
      "31504/31504 [==============================] - 20s 620us/sample - loss: 9.3681 - val_loss: 1.4202\n",
      "Epoch 17/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3678\n",
      "Epoch 17: val_loss improved from 1.41871 to 1.41534, saving model to ./checkpoints/unknown_person_p10_22.h5\n",
      "31504/31504 [==============================] - 20s 627us/sample - loss: 9.3678 - val_loss: 1.4153\n",
      "Epoch 18/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3663\n",
      "Epoch 18: val_loss did not improve from 1.41534\n",
      "31504/31504 [==============================] - 19s 606us/sample - loss: 9.3663 - val_loss: 1.4288\n",
      "Epoch 19/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3734\n",
      "Epoch 19: val_loss improved from 1.41534 to 1.41526, saving model to ./checkpoints/unknown_person_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 611us/sample - loss: 9.3734 - val_loss: 1.4153\n",
      "Epoch 20/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 9.3650\n",
      "Epoch 20: val_loss did not improve from 1.41526\n",
      "31504/31504 [==============================] - 19s 605us/sample - loss: 9.3650 - val_loss: 1.4278\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:39:37.358244: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_25_6/lstm_cell_247/bias/Assign' id:119585 op device:{requested: '', assigned: ''} def:{{{node lstm_25_6/lstm_cell_247/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_25_6/lstm_cell_247/bias, lstm_25_6/lstm_cell_247/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 14:39:43.506026: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_24_6/lstm_cell_246/kernel/m/Assign' id:122526 op device:{requested: '', assigned: ''} def:{{{node lstm_24_6/lstm_cell_246/kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_24_6/lstm_cell_246/kernel/m, lstm_24_6/lstm_cell_246/kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31504 samples, validate on 3515 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:39:52.750128: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:40:25.113069: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_10/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3537"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 14:40:45.452475: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.42045, saving model to ./checkpoints/unknown_person_baseline_2_p10_22.h5\n",
      "31504/31504 [==============================] - 33s 1ms/sample - loss: 1.3537 - val_loss: 1.4204\n",
      "Epoch 2/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3485\n",
      "Epoch 2: val_loss improved from 1.42045 to 1.41262, saving model to ./checkpoints/unknown_person_baseline_2_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 605us/sample - loss: 1.3485 - val_loss: 1.4126\n",
      "Epoch 3/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3879\n",
      "Epoch 3: val_loss did not improve from 1.41262\n",
      "31504/31504 [==============================] - 19s 601us/sample - loss: 1.3879 - val_loss: 1.4224\n",
      "Epoch 4/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3703\n",
      "Epoch 4: val_loss did not improve from 1.41262\n",
      "31504/31504 [==============================] - 19s 601us/sample - loss: 1.3703 - val_loss: 1.4163\n",
      "Epoch 5/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3552\n",
      "Epoch 5: val_loss did not improve from 1.41262\n",
      "31504/31504 [==============================] - 19s 605us/sample - loss: 1.3552 - val_loss: 1.4185\n",
      "Epoch 6/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3515\n",
      "Epoch 6: val_loss did not improve from 1.41262\n",
      "31504/31504 [==============================] - 19s 608us/sample - loss: 1.3515 - val_loss: 1.4192\n",
      "Epoch 7/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3521\n",
      "Epoch 7: val_loss did not improve from 1.41262\n",
      "31504/31504 [==============================] - 20s 638us/sample - loss: 1.3521 - val_loss: 1.4222\n",
      "Epoch 8/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3504\n",
      "Epoch 8: val_loss did not improve from 1.41262\n",
      "31504/31504 [==============================] - 22s 696us/sample - loss: 1.3504 - val_loss: 1.4143\n",
      "Epoch 9/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3486\n",
      "Epoch 9: val_loss improved from 1.41262 to 1.41223, saving model to ./checkpoints/unknown_person_baseline_2_p10_22.h5\n",
      "31504/31504 [==============================] - 20s 646us/sample - loss: 1.3486 - val_loss: 1.4122\n",
      "Epoch 10/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3448\n",
      "Epoch 10: val_loss improved from 1.41223 to 1.41189, saving model to ./checkpoints/unknown_person_baseline_2_p10_22.h5\n",
      "31504/31504 [==============================] - 22s 691us/sample - loss: 1.3448 - val_loss: 1.4119\n",
      "Epoch 11/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3465\n",
      "Epoch 11: val_loss did not improve from 1.41189\n",
      "31504/31504 [==============================] - 22s 697us/sample - loss: 1.3465 - val_loss: 1.4135\n",
      "Epoch 12/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3461\n",
      "Epoch 12: val_loss did not improve from 1.41189\n",
      "31504/31504 [==============================] - 21s 678us/sample - loss: 1.3461 - val_loss: 1.4195\n",
      "Epoch 13/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3429\n",
      "Epoch 13: val_loss did not improve from 1.41189\n",
      "31504/31504 [==============================] - 20s 645us/sample - loss: 1.3429 - val_loss: 1.4174\n",
      "Epoch 14/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3459\n",
      "Epoch 14: val_loss did not improve from 1.41189\n",
      "31504/31504 [==============================] - 21s 676us/sample - loss: 1.3459 - val_loss: 1.4144\n",
      "Epoch 15/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3433\n",
      "Epoch 15: val_loss did not improve from 1.41189\n",
      "31504/31504 [==============================] - 19s 596us/sample - loss: 1.3433 - val_loss: 1.4158\n",
      "Epoch 16/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3407\n",
      "Epoch 16: val_loss did not improve from 1.41189\n",
      "31504/31504 [==============================] - 19s 599us/sample - loss: 1.3407 - val_loss: 1.4123\n",
      "Epoch 17/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3437\n",
      "Epoch 17: val_loss improved from 1.41189 to 1.40644, saving model to ./checkpoints/unknown_person_baseline_2_p10_22.h5\n",
      "31504/31504 [==============================] - 19s 602us/sample - loss: 1.3437 - val_loss: 1.4064\n",
      "Epoch 18/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3386\n",
      "Epoch 18: val_loss did not improve from 1.40644\n",
      "31504/31504 [==============================] - 19s 599us/sample - loss: 1.3386 - val_loss: 1.4101\n",
      "Epoch 19/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3416\n",
      "Epoch 19: val_loss did not improve from 1.40644\n",
      "31504/31504 [==============================] - 20s 624us/sample - loss: 1.3416 - val_loss: 1.4150\n",
      "Epoch 20/20\n",
      "31504/31504 [==============================] - ETA: 0s - loss: 1.3406\n",
      "Epoch 20: val_loss did not improve from 1.40644\n",
      "31504/31504 [==============================] - 18s 585us/sample - loss: 1.3406 - val_loss: 1.4148\n"
     ]
    }
   ],
   "source": [
    "person_nums = [1,2,4,5,6,8,9,10,11,12,13,17,19,21,22,25,26,27,28,29]\n",
    "## Build the baseline model for emotion recognition with dropout layers\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, SimpleRNN, LSTM, Conv2D, Flatten, MaxPooling2D, GRU, AveragePooling2D, Dropout, Lambda\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "def individual_model(features_list):\n",
    "    input_layers = []\n",
    "    hidden_layers = []\n",
    "    combined_feature = np.empty((len(features_list[0]),0))\n",
    "    for i, feature in enumerate(features_list):\n",
    "        \n",
    "        if len(feature.shape) == 3:\n",
    "            input_i = Input(shape=(feature.shape[1], feature.shape[2]))\n",
    "            input_layers.append(input_i)\n",
    "\n",
    "            hidden_i = input_i[:,:,:,None]\n",
    "            hidden_i = Conv2D(32, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(16, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(8, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(4, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Flatten()(hidden_i)\n",
    "\n",
    "            hidden_layers.append(hidden_i)\n",
    "        elif feature.shape[1] <20:\n",
    "            combined_feature = np.hstack((combined_feature, feature))\n",
    "            \n",
    "        else:  # For series features\n",
    "            input_i = Input(shape=(feature.shape[1],))\n",
    "            input_layers.append(input_i)\n",
    "            hidden_i = Lambda(lambda x: x[:, :, None])(input_i)  # Add a new dimension\n",
    "            hidden_i = LSTM(4)(hidden_i)\n",
    "            hidden_layers.append(hidden_i)\n",
    "    input_i = Input(shape=(combined_feature.shape[1],))\n",
    "    input_layers.append(input_i)\n",
    "    dense_num = np.max((1, int(combined_feature.shape[1]/2)))\n",
    "    hidden_i = Dense(dense_num, activation='relu')(input_i)\n",
    "    hidden_layers.append(hidden_i)\n",
    "    print(combined_feature.shape)\n",
    "    concat_layer = concatenate(hidden_layers)\n",
    "    h = Dropout(0.2)(concat_layer)\n",
    "    h = Dense(64, activation='relu')(h)\n",
    "    h = Dense(32, activation='relu')(h)\n",
    "    output_layer = Dense(2)(h)\n",
    "    model = Model(inputs=input_layers, outputs=output_layer)\n",
    "    model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "    return model\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.callbacks import Callback\n",
    "import numpy as np\n",
    "\n",
    "class PruningCallback(tf.keras.callbacks.Callback):\n",
    "    def __init__(self, initial_pruning_factor=0.1, final_pruning_factor=0.5, start_epoch=0, end_epoch=None, frequency=1):\n",
    "        super(PruningCallback, self).__init__()\n",
    "        self.initial_pruning_factor = initial_pruning_factor\n",
    "        self.final_pruning_factor = final_pruning_factor\n",
    "        self.start_epoch = start_epoch\n",
    "        self.end_epoch = end_epoch if end_epoch is not None else np.inf\n",
    "        self.frequency = frequency\n",
    "        self.pruned_weights = {}\n",
    "        self.layer_importance = {}\n",
    "\n",
    "    def get_pruning_factor(self, epoch):\n",
    "        if epoch < self.start_epoch:\n",
    "            return 0\n",
    "        if epoch > self.end_epoch:\n",
    "            return self.final_pruning_factor\n",
    "        return self.initial_pruning_factor + (self.final_pruning_factor - self.initial_pruning_factor) * (epoch - self.start_epoch) / (self.end_epoch - self.start_epoch)\n",
    "\n",
    "    def on_train_begin(self, logs=None):\n",
    "        total_weight_magnitude = 0\n",
    "        for layer in self.model.layers:\n",
    "            if hasattr(layer, 'get_weights'):\n",
    "                weights = layer.get_weights()\n",
    "                layer_norm = sum(np.linalg.norm(w) for w in weights)\n",
    "                total_weight_magnitude += layer_norm\n",
    "                self.layer_importance[layer.name] = layer_norm\n",
    "    \n",
    "        # Normalize the layer importance values so they sum up to 1\n",
    "        for layer_name in self.layer_importance:\n",
    "            self.layer_importance[layer_name] /= total_weight_magnitude\n",
    "    # def on_train_begin(self, logs=None):\n",
    "    #     total_weight_magnitude = sum([np.linalg.norm(layer.get_weights()) for layer in self.model.layers if hasattr(layer, 'get_weights')])\n",
    "    #     for layer in self.model.layers:\n",
    "    #         if hasattr(layer, 'get_weights'):\n",
    "    #             self.layer_importance[layer.name] = np.linalg.norm(layer.get_weights()) / total_weight_magnitude\n",
    "\n",
    "    def get_layer_pruning_factor(self, layer_name, global_pruning_factor):\n",
    "        if layer_name in self.layer_importance:\n",
    "            importance = self.layer_importance[layer_name]\n",
    "            adjusted_pruning_factor = global_pruning_factor * (1 - importance)\n",
    "            return min(adjusted_pruning_factor, 1)  # Ensure the pruning factor is not greater than 1\n",
    "        return global_pruning_factor\n",
    "    def prune_weights(self, layer, global_pruning_factor):\n",
    "        \n",
    "        weights = layer.get_weights()\n",
    "        layer_name = layer.name\n",
    "        pruning_factor = self.get_layer_pruning_factor(layer_name, global_pruning_factor)\n",
    "\n",
    "        if layer_name not in self.pruned_weights:\n",
    "            self.pruned_weights[layer_name] = [np.zeros_like(w, dtype=bool) for w in weights]\n",
    "        \n",
    "        for i in range(len(weights)):\n",
    "            weight = weights[i]\n",
    "            # print(weight.shape)\n",
    "            # print(weight.size)\n",
    "            if weight.ndim > 1:  # Only prune dense or convolutional layers\n",
    "                unpruned_weights = np.logical_not(self.pruned_weights[layer_name][i])\n",
    "                num_unpruned = np.sum(unpruned_weights)\n",
    "                num_pruning = min(num_unpruned, int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i]))\n",
    "                num_pruning = int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i])\n",
    "                if num_pruning > 0:\n",
    "                    unpruned_flat_indices = np.flatnonzero(unpruned_weights)\n",
    "                    abs_unpruned_weights = np.abs(weight[unpruned_weights])\n",
    "                    pruning_flat_indices = np.argpartition(abs_unpruned_weights, num_pruning)[:num_pruning]\n",
    "                    \n",
    "                    indices = np.unravel_index(pruning_flat_indices, weight.shape)\n",
    "                    self.pruned_weights[layer_name][i][indices] = True\n",
    "\n",
    "                weights[i] = weights[i]*(~self.pruned_weights[layer_name][i])\n",
    "                \n",
    "        layer.set_weights(weights)\n",
    "\n",
    "    def on_epoch_end(self, epoch, logs=None):\n",
    "        if (epoch - self.start_epoch) % self.frequency != 0:\n",
    "            return\n",
    "\n",
    "        pruning_factor = self.get_pruning_factor(epoch)\n",
    "        for layer in self.model.layers:\n",
    "            if isinstance(layer, (tf.keras.layers.Dense, tf.keras.layers.Conv2D)):\n",
    "                self.prune_weights(layer, pruning_factor)\n",
    "from feature_emotion import feature_extract, split_data, label_unique_tuples, split_data_unknown\n",
    "gts, sensor_nums, walk_nums, trace_nums, people_nums, spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features = feature_extract(person_nums)\n",
    "\n",
    "walk_nums_all = np.squeeze(walk_nums)\n",
    "trace_nums_all = np.squeeze(trace_nums)\n",
    "people_nums_all = np.squeeze(people_nums)\n",
    "\n",
    "## 0: train, 1: validation 2: test\n",
    "\n",
    "test_person_id = [10]\n",
    "flag_tr_val_te = split_data_unknown(test_person_id, walk_nums_all, trace_nums_all, people_nums_all, person_nums, rand_seed = 42)\n",
    "## Data Normalization before training ans testing\n",
    "import tensorflow as tf\n",
    "tf.compat.v1.disable_v2_behavior()\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, LSTM\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "scalers = []\n",
    "X_train_normalized = []\n",
    "X_val_normalized = []\n",
    "X_test_normalized = []\n",
    "train_idx = np.where(flag_tr_val_te ==0)[0]\n",
    "np.random.shuffle(train_idx)\n",
    "val_idx = np.where(flag_tr_val_te ==1)[0]\n",
    "test_idx = np.where(flag_tr_val_te ==2)[0]\n",
    "\n",
    "for i, feature in enumerate([spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features]):\n",
    "    scaler = StandardScaler()\n",
    "    if len(feature.shape)==2:\n",
    "        X_train_i = feature[train_idx,:]\n",
    "        X_val_i = feature[val_idx,:]\n",
    "        X_test_i = feature[test_idx,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i)\n",
    "        scalers.append(scaler)\n",
    "    else:\n",
    "        X_train_i = feature[train_idx,:,:]\n",
    "        X_val_i = feature[val_idx,:,:]\n",
    "        X_test_i = feature[test_idx,:,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i.reshape(X_train_i.shape[0], -1)).reshape(X_train_i.shape)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i.reshape(X_val_i.shape[0], -1)).reshape(X_val_i.shape)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i.reshape(X_test_i.shape[0], -1)).reshape(X_test_i.shape)\n",
    "        scalers.append(scaler)\n",
    "    X_train_normalized.append(X_train_normalized_i)\n",
    "    X_val_normalized.append(X_val_normalized_i)\n",
    "    X_test_normalized.append(X_test_normalized_i)\n",
    "y_train = gts[train_idx,:]\n",
    "y_val = gts[val_idx,:]\n",
    "y_test = gts[test_idx,:]\n",
    "X_train_normalized_new = []\n",
    "combined_feature = np.empty((len(X_train_normalized[0]),0))\n",
    "for feature in X_train_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_train_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_train_normalized_new.append(feature)\n",
    "X_train_normalized_new.append(combined_feature)\n",
    "\n",
    "X_val_normalized_new = []\n",
    "combined_feature = np.empty((len(X_val_normalized[0]),0))\n",
    "for feature in X_val_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_val_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_val_normalized_new.append(feature)\n",
    "X_val_normalized_new.append(combined_feature)\n",
    "\n",
    "X_test_normalized_new = []\n",
    "combined_feature = np.empty((len(X_test_normalized[0]),0))\n",
    "for feature in X_test_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_test_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_test_normalized_new.append(feature)\n",
    "X_test_normalized_new.append(combined_feature)\n",
    "\n",
    "model = individual_model(X_train_normalized)\n",
    "model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "num_epochs = 50\n",
    "\n",
    "\n",
    "# Gradually prune weights in dense and convolutional layers from 10% to 50% over the course of training, starting from epoch 0.\n",
    "\n",
    "\n",
    "rates = [0.4, 0.5, 0.6]\n",
    "idx = 20\n",
    "for r in rates:\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=0.01, final_pruning_factor=r, start_epoch=5, end_epoch=20, frequency=1)\n",
    "    model.fit(X_train_normalized_new, y_train, epochs=num_epochs, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import tensorflow as tf\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    from tensorflow.keras.models import Model\n",
    "    layers = model.layers\n",
    "    second_last_layer_output = layers[-4].output\n",
    "    feature_extractor_model = Model(inputs=model.input, outputs=second_last_layer_output)\n",
    "    train_features = feature_extractor_model.predict(X_train_normalized_new)\n",
    "    test_features = feature_extractor_model.predict(X_test_normalized_new)\n",
    "    \n",
    "    p_train = people_nums[train_idx,:]\n",
    "    p_val = people_nums[val_idx,:]\n",
    "    p_test = people_nums[test_idx,:]\n",
    "    ## Calculate the distance between test person and training person\n",
    "    def euclidean_distance(a, b):\n",
    "        return np.sqrt(np.sum((a - b) ** 2, axis=1))\n",
    "    \n",
    "    distance_dict = {}\n",
    "    for ii in range(len(person_nums)):\n",
    "        if person_nums[ii] == test_person_id[0]:\n",
    "            continue\n",
    "        else:\n",
    "            \n",
    "            ind = np.where(p_train ==person_nums[ii])[0]\n",
    "            tmp_train_features = train_features[ind, :]\n",
    "            distances = np.array([euclidean_distance(train_sample, test_features) for train_sample in tmp_train_features])\n",
    "            print(distances.shape)\n",
    "            average_distances = np.mean(distances, axis=1)\n",
    "    \n",
    "            # Step 4: Find the overall average distance\n",
    "            overall_average_distance = np.mean(average_distances)\n",
    "            distance_dict[person_nums[ii]] = overall_average_distance\n",
    "    \n",
    "    \n",
    "    def normalize_to_weights(distance_dict):\n",
    "        distances = np.array(list(distance_dict.values()))\n",
    "        # Handle the case where a distance is zero to avoid division by zero\n",
    "        distances = np.clip(distances, a_min=1e-10, a_max=None)\n",
    "        weights = 1 / distances\n",
    "        normalized_weights = weights\n",
    "        # normalized_weights = weights / sum(weights)\n",
    "        # print(sum(weights))\n",
    "        # print(sum(normalized_weights))\n",
    "        # Assign the normalized weights back to the dictionary\n",
    "        normalized_weight_dict = dict(zip(distance_dict.keys(), normalized_weights))\n",
    "        return normalized_weight_dict\n",
    "    def scale_dict_values(my_dict):\n",
    "        scaled_dict = my_dict.copy()\n",
    "        min_val = min(scaled_dict.values())\n",
    "        max_val = max(scaled_dict.values())\n",
    "        \n",
    "        for key in scaled_dict:\n",
    "            scaled_dict[key] = 1 + 9 * (scaled_dict[key] - min_val) / (max_val - min_val)\n",
    "        \n",
    "        return scaled_dict\n",
    "    weights_dict = normalize_to_weights(distance_dict)\n",
    "    weights_dict = scale_dict_values(weights_dict)\n",
    "    print(weights_dict)\n",
    "    \n",
    "    w_train = np.zeros_like(p_train)\n",
    "    for i in range(len(w_train)):\n",
    "        w_train[i] = weights_dict[int(p_train[i])]\n",
    "    \n",
    "    w_train = np.squeeze(w_train)\n",
    "    \n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,sample_weight= w_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    model_name = './checkpoints/unknown_person_baseline_2_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    idx += 1\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "0508e9a1-9544-41f8-af41-e3d3b02a8d80",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-08T19:47:14.665987Z",
     "iopub.status.busy": "2023-11-08T19:47:14.665840Z",
     "iopub.status.idle": "2023-11-08T19:47:14.670360Z",
     "shell.execute_reply": "2023-11-08T19:47:14.669883Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "37001"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "35408 + 1593"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f71b59e4-6581-4ea8-994d-a02a6654ab6b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
