{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c77f8da1-2837-4bf7-b3f4-dfcaa7ab42f6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-09T03:06:00.952742Z",
     "iopub.status.busy": "2023-11-09T03:06:00.952625Z",
     "iopub.status.idle": "2023-11-09T03:06:01.038999Z",
     "shell.execute_reply": "2023-11-09T03:06:01.038420Z"
    }
   },
   "outputs": [],
   "source": [
    "import scipy.io\n",
    "import numpy as np\n",
    "import random\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3fe25376-b856-4296-ba02-5e3771ff9451",
   "metadata": {
    "collapsed": true,
    "execution": {
     "iopub.execute_input": "2023-11-09T03:06:01.041575Z",
     "iopub.status.busy": "2023-11-09T03:06:01.041422Z",
     "iopub.status.idle": "2023-11-09T04:56:55.275788Z",
     "shell.execute_reply": "2023-11-09T04:56:55.275196Z"
    },
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:06:01.219354: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/usr/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1, this may cause problems\n",
      "  _warn((\"h5py is running against HDF5 {0} when it was built against {1}, \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "35082\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "non-resource variables are not supported in the long term\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:07:24.429675: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.441281: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.441527: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.444938: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.445129: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.445299: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.521814: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.522021: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.522187: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:24.522329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:2d:00.0, compute capability: 8.6\n",
      "2023-11-08 22:07:24.522611: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:07:25.444138: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:25.444393: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:25.444577: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:25.444789: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:25.444963: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 22:07:25.445096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:2d:00.0, compute capability: 8.6\n",
      "2023-11-08 22:07:25.445129: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n",
      "2023-11-08 22:07:25.466883: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled\n",
      "2023-11-08 22:07:25.681763: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_14/lstm_cell_14/bias/Assign' id:2355 op device:{requested: '', assigned: ''} def:{{{node lstm_14/lstm_cell_14/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_14/lstm_cell_14/bias, lstm_14/lstm_cell_14/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:07:25.813081: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_1' id:3634 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_1}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 0 0 0...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:07:25.846447: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_2' id:3635 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_2}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 1 1 1...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "(31569, 95)\n",
      "Train on 31569 samples, validate on 3513 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:07:30.264166: W tensorflow/c/c_api.cc:304] Operation '{name:'training/Adam/conv2d_1/bias/v/Assign' id:17012 op device:{requested: '', assigned: ''} def:{{{node training/Adam/conv2d_1/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](training/Adam/conv2d_1/bias/v, training/Adam/conv2d_1/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:07:34.037522: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n",
      "2023-11-08 22:07:36.265726: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8902\n",
      "2023-11-08 22:07:36.478438: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31569/31569 [==============================] - ETA: 0s - loss: 2.6639"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2335: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates = self.state_updates\n",
      "2023-11-08 22:07:56.704168: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_1/mul' id:6477 op device:{requested: '', assigned: ''} def:{{{node loss_1/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_1/mul/x, loss_1/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.86051, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 28s 874us/sample - loss: 2.6639 - val_loss: 1.8605\n",
      "Epoch 2/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.6907\n",
      "Epoch 2: val_loss improved from 1.86051 to 1.52455, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 650us/sample - loss: 1.6907 - val_loss: 1.5246\n",
      "Epoch 3/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.5419\n",
      "Epoch 3: val_loss improved from 1.52455 to 1.46897, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 656us/sample - loss: 1.5419 - val_loss: 1.4690\n",
      "Epoch 4/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4972\n",
      "Epoch 4: val_loss improved from 1.46897 to 1.44595, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 20s 649us/sample - loss: 1.4972 - val_loss: 1.4460\n",
      "Epoch 5/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4752\n",
      "Epoch 5: val_loss improved from 1.44595 to 1.42304, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 20s 637us/sample - loss: 1.4752 - val_loss: 1.4230\n",
      "Epoch 6/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4630\n",
      "Epoch 6: val_loss improved from 1.42304 to 1.41367, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 704us/sample - loss: 1.4630 - val_loss: 1.4137\n",
      "Epoch 7/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4533\n",
      "Epoch 7: val_loss improved from 1.41367 to 1.40214, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 678us/sample - loss: 1.4533 - val_loss: 1.4021\n",
      "Epoch 8/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4480\n",
      "Epoch 8: val_loss improved from 1.40214 to 1.39800, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 704us/sample - loss: 1.4480 - val_loss: 1.3980\n",
      "Epoch 9/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4467\n",
      "Epoch 9: val_loss improved from 1.39800 to 1.39320, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 707us/sample - loss: 1.4467 - val_loss: 1.3932\n",
      "Epoch 10/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4449\n",
      "Epoch 10: val_loss improved from 1.39320 to 1.38838, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 695us/sample - loss: 1.4449 - val_loss: 1.3884\n",
      "Epoch 11/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4371\n",
      "Epoch 11: val_loss improved from 1.38838 to 1.38572, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 20s 643us/sample - loss: 1.4371 - val_loss: 1.3857\n",
      "Epoch 12/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4381\n",
      "Epoch 12: val_loss improved from 1.38572 to 1.38061, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 673us/sample - loss: 1.4381 - val_loss: 1.3806\n",
      "Epoch 13/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4312\n",
      "Epoch 13: val_loss improved from 1.38061 to 1.37975, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 661us/sample - loss: 1.4312 - val_loss: 1.3797\n",
      "Epoch 14/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4389\n",
      "Epoch 14: val_loss improved from 1.37975 to 1.37699, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 654us/sample - loss: 1.4389 - val_loss: 1.3770\n",
      "Epoch 15/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4681\n",
      "Epoch 15: val_loss did not improve from 1.37699\n",
      "31569/31569 [==============================] - 20s 623us/sample - loss: 1.4681 - val_loss: 1.3946\n",
      "Epoch 16/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4272\n",
      "Epoch 16: val_loss improved from 1.37699 to 1.37467, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 692us/sample - loss: 1.4272 - val_loss: 1.3747\n",
      "Epoch 17/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4321\n",
      "Epoch 17: val_loss did not improve from 1.37467\n",
      "31569/31569 [==============================] - 20s 635us/sample - loss: 1.4321 - val_loss: 1.3797\n",
      "Epoch 18/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4358\n",
      "Epoch 18: val_loss did not improve from 1.37467\n",
      "31569/31569 [==============================] - 20s 618us/sample - loss: 1.4358 - val_loss: 1.3799\n",
      "Epoch 19/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4255\n",
      "Epoch 19: val_loss improved from 1.37467 to 1.36931, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 20s 619us/sample - loss: 1.4255 - val_loss: 1.3693\n",
      "Epoch 20/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4241\n",
      "Epoch 20: val_loss did not improve from 1.36931\n",
      "31569/31569 [==============================] - 21s 651us/sample - loss: 1.4241 - val_loss: 1.3723\n",
      "Epoch 21/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4215\n",
      "Epoch 21: val_loss did not improve from 1.36931\n",
      "31569/31569 [==============================] - 21s 671us/sample - loss: 1.4215 - val_loss: 1.3733\n",
      "Epoch 22/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4167\n",
      "Epoch 22: val_loss improved from 1.36931 to 1.36208, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 664us/sample - loss: 1.4167 - val_loss: 1.3621\n",
      "Epoch 23/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4078\n",
      "Epoch 23: val_loss did not improve from 1.36208\n",
      "31569/31569 [==============================] - 22s 699us/sample - loss: 1.4078 - val_loss: 1.3646\n",
      "Epoch 24/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4060\n",
      "Epoch 24: val_loss improved from 1.36208 to 1.35953, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 709us/sample - loss: 1.4060 - val_loss: 1.3595\n",
      "Epoch 25/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4041\n",
      "Epoch 25: val_loss improved from 1.35953 to 1.35416, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 707us/sample - loss: 1.4041 - val_loss: 1.3542\n",
      "Epoch 26/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3990\n",
      "Epoch 26: val_loss did not improve from 1.35416\n",
      "31569/31569 [==============================] - 22s 704us/sample - loss: 1.3990 - val_loss: 1.3544\n",
      "Epoch 27/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3908\n",
      "Epoch 27: val_loss improved from 1.35416 to 1.35300, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 706us/sample - loss: 1.3908 - val_loss: 1.3530\n",
      "Epoch 28/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3918\n",
      "Epoch 28: val_loss improved from 1.35300 to 1.35081, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 671us/sample - loss: 1.3918 - val_loss: 1.3508\n",
      "Epoch 29/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3873\n",
      "Epoch 29: val_loss improved from 1.35081 to 1.34722, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 659us/sample - loss: 1.3873 - val_loss: 1.3472\n",
      "Epoch 30/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3870\n",
      "Epoch 30: val_loss did not improve from 1.34722\n",
      "31569/31569 [==============================] - 21s 674us/sample - loss: 1.3870 - val_loss: 1.3476\n",
      "Epoch 31/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3831\n",
      "Epoch 31: val_loss did not improve from 1.34722\n",
      "31569/31569 [==============================] - 20s 622us/sample - loss: 1.3831 - val_loss: 1.3487\n",
      "Epoch 32/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3829\n",
      "Epoch 32: val_loss improved from 1.34722 to 1.34155, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 660us/sample - loss: 1.3829 - val_loss: 1.3416\n",
      "Epoch 33/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3777\n",
      "Epoch 33: val_loss did not improve from 1.34155\n",
      "31569/31569 [==============================] - 22s 708us/sample - loss: 1.3777 - val_loss: 1.3465\n",
      "Epoch 34/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3774\n",
      "Epoch 34: val_loss improved from 1.34155 to 1.33877, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 700us/sample - loss: 1.3774 - val_loss: 1.3388\n",
      "Epoch 35/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3762\n",
      "Epoch 35: val_loss did not improve from 1.33877\n",
      "31569/31569 [==============================] - 22s 704us/sample - loss: 1.3762 - val_loss: 1.3481\n",
      "Epoch 36/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3731\n",
      "Epoch 36: val_loss improved from 1.33877 to 1.33795, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 703us/sample - loss: 1.3731 - val_loss: 1.3379\n",
      "Epoch 37/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3724\n",
      "Epoch 37: val_loss did not improve from 1.33795\n",
      "31569/31569 [==============================] - 20s 632us/sample - loss: 1.3724 - val_loss: 1.3447\n",
      "Epoch 38/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3703\n",
      "Epoch 38: val_loss improved from 1.33795 to 1.33265, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 689us/sample - loss: 1.3703 - val_loss: 1.3326\n",
      "Epoch 39/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3694\n",
      "Epoch 39: val_loss improved from 1.33265 to 1.33118, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 705us/sample - loss: 1.3694 - val_loss: 1.3312\n",
      "Epoch 40/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3664\n",
      "Epoch 40: val_loss improved from 1.33118 to 1.33114, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 650us/sample - loss: 1.3664 - val_loss: 1.3311\n",
      "Epoch 41/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3666\n",
      "Epoch 41: val_loss did not improve from 1.33114\n",
      "31569/31569 [==============================] - 22s 681us/sample - loss: 1.3666 - val_loss: 1.3368\n",
      "Epoch 42/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3648\n",
      "Epoch 42: val_loss did not improve from 1.33114\n",
      "31569/31569 [==============================] - 22s 700us/sample - loss: 1.3648 - val_loss: 1.3342\n",
      "Epoch 43/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3625\n",
      "Epoch 43: val_loss improved from 1.33114 to 1.32673, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 20s 643us/sample - loss: 1.3625 - val_loss: 1.3267\n",
      "Epoch 44/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3590\n",
      "Epoch 44: val_loss did not improve from 1.32673\n",
      "31569/31569 [==============================] - 22s 698us/sample - loss: 1.3590 - val_loss: 1.3360\n",
      "Epoch 45/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3563\n",
      "Epoch 45: val_loss did not improve from 1.32673\n",
      "31569/31569 [==============================] - 22s 682us/sample - loss: 1.3563 - val_loss: 1.3269\n",
      "Epoch 46/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3557\n",
      "Epoch 46: val_loss improved from 1.32673 to 1.32618, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 683us/sample - loss: 1.3557 - val_loss: 1.3262\n",
      "Epoch 47/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3559\n",
      "Epoch 47: val_loss improved from 1.32618 to 1.32119, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 703us/sample - loss: 1.3559 - val_loss: 1.3212\n",
      "Epoch 48/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3550\n",
      "Epoch 48: val_loss did not improve from 1.32119\n",
      "31569/31569 [==============================] - 22s 691us/sample - loss: 1.3550 - val_loss: 1.3249\n",
      "Epoch 49/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3535\n",
      "Epoch 49: val_loss improved from 1.32119 to 1.32077, saving model to ./checkpoints/unknown_person_baseline_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 705us/sample - loss: 1.3535 - val_loss: 1.3208\n",
      "Epoch 50/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3533\n",
      "Epoch 50: val_loss did not improve from 1.32077\n",
      "31569/31569 [==============================] - 21s 676us/sample - loss: 1.3533 - val_loss: 1.3274\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:25:26.139251: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_16_1/lstm_cell_53/kernel/Assign' id:21200 op device:{requested: '', assigned: ''} def:{{{node lstm_16_1/lstm_cell_53/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_16_1/lstm_cell_53/kernel, lstm_16_1/lstm_cell_53/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:25:27.839148: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_10_1/lstm_cell_47/kernel/v/Assign' id:26045 op device:{requested: '', assigned: ''} def:{{{node lstm_10_1/lstm_cell_47/kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_10_1/lstm_cell_47/kernel/v, lstm_10_1/lstm_cell_47/kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates=self.state_updates,\n",
      "2023-11-08 22:25:29.171492: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_1/cond/Merge' id:24591 op device:{requested: '', assigned: ''} def:{{{node dropout_4_1/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_1/cond/Identity, dropout_4_1/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1919)\n",
      "(1514, 1919)\n",
      "(1644, 1919)\n",
      "(1764, 1919)\n",
      "(1836, 1919)\n",
      "(1699, 1919)\n",
      "(1369, 1919)\n",
      "(1766, 1919)\n",
      "(1631, 1919)\n",
      "(1692, 1919)\n",
      "(1550, 1919)\n",
      "(1920, 1919)\n",
      "(1788, 1919)\n",
      "(1872, 1919)\n",
      "(1692, 1919)\n",
      "(1824, 1919)\n",
      "(971, 1919)\n",
      "(1656, 1919)\n",
      "(1896, 1919)\n",
      "{1: 5.404374119232078, 2: 4.05845060603224, 4: 10.0, 5: 5.1321692199859665, 6: 6.30025354581061, 8: 8.093308692940209, 9: 5.878705479936242, 10: 6.773093607280134, 11: 6.722755594262169, 12: 8.048091321696877, 13: 5.643297652774192, 17: 8.531794158306393, 21: 7.229539197577508, 22: 1.0, 25: 7.042394471328031, 26: 4.355882732782855, 27: 4.755434485675179, 28: 5.10629244257964, 29: 2.6370698768076473}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_2793692/738665897.py:300: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)\n",
      "  w_train[i] = weights_dict[int(p_train[i])]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31569 samples, validate on 3513 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:29:25.125785: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_5/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31569/31569 [==============================] - ETA: 0s - loss: 8.3814\n",
      "Epoch 1: val_loss improved from inf to 1.33834, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 25s 807us/sample - loss: 8.3814 - val_loss: 1.3383\n",
      "Epoch 2/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.3313\n",
      "Epoch 2: val_loss improved from 1.33834 to 1.33351, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 658us/sample - loss: 8.3313 - val_loss: 1.3335\n",
      "Epoch 3/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2979\n",
      "Epoch 3: val_loss improved from 1.33351 to 1.32952, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 19s 610us/sample - loss: 8.2979 - val_loss: 1.3295\n",
      "Epoch 4/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2445\n",
      "Epoch 4: val_loss improved from 1.32952 to 1.32385, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 19s 613us/sample - loss: 8.2445 - val_loss: 1.3238\n",
      "Epoch 5/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2182\n",
      "Epoch 5: val_loss improved from 1.32385 to 1.32134, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 19s 617us/sample - loss: 8.2182 - val_loss: 1.3213\n",
      "Epoch 6/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1895\n",
      "Epoch 6: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 19s 603us/sample - loss: 8.1895 - val_loss: 1.3330\n",
      "Epoch 7/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1932\n",
      "Epoch 7: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 20s 620us/sample - loss: 8.1932 - val_loss: 1.3369\n",
      "Epoch 8/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1785\n",
      "Epoch 8: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 22s 696us/sample - loss: 8.1785 - val_loss: 1.3255\n",
      "Epoch 9/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1697\n",
      "Epoch 9: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 21s 676us/sample - loss: 8.1697 - val_loss: 1.3244\n",
      "Epoch 10/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1410\n",
      "Epoch 10: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 20s 626us/sample - loss: 8.1410 - val_loss: 1.3234\n",
      "Epoch 11/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1425\n",
      "Epoch 11: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 20s 634us/sample - loss: 8.1425 - val_loss: 1.3298\n",
      "Epoch 12/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1369\n",
      "Epoch 12: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 21s 668us/sample - loss: 8.1369 - val_loss: 1.3252\n",
      "Epoch 13/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1283\n",
      "Epoch 13: val_loss did not improve from 1.32134\n",
      "31569/31569 [==============================] - 22s 692us/sample - loss: 8.1283 - val_loss: 1.3257\n",
      "Epoch 14/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0890\n",
      "Epoch 14: val_loss improved from 1.32134 to 1.32018, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 656us/sample - loss: 8.0890 - val_loss: 1.3202\n",
      "Epoch 15/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0971\n",
      "Epoch 15: val_loss improved from 1.32018 to 1.31971, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 19s 599us/sample - loss: 8.0971 - val_loss: 1.3197\n",
      "Epoch 16/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0926\n",
      "Epoch 16: val_loss did not improve from 1.31971\n",
      "31569/31569 [==============================] - 21s 677us/sample - loss: 8.0926 - val_loss: 1.3228\n",
      "Epoch 17/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0870\n",
      "Epoch 17: val_loss did not improve from 1.31971\n",
      "31569/31569 [==============================] - 22s 685us/sample - loss: 8.0870 - val_loss: 1.3289\n",
      "Epoch 18/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0646\n",
      "Epoch 18: val_loss improved from 1.31971 to 1.31832, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 691us/sample - loss: 8.0646 - val_loss: 1.3183\n",
      "Epoch 19/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0558\n",
      "Epoch 19: val_loss improved from 1.31832 to 1.31763, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 676us/sample - loss: 8.0558 - val_loss: 1.3176\n",
      "Epoch 20/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0674\n",
      "Epoch 20: val_loss improved from 1.31763 to 1.31481, saving model to ./checkpoints/unknown_person_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 690us/sample - loss: 8.0674 - val_loss: 1.3148\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:36:23.373637: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_9_2/lstm_cell_83/kernel/Assign' id:39478 op device:{requested: '', assigned: ''} def:{{{node lstm_9_2/lstm_cell_83/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_9_2/lstm_cell_83/kernel, lstm_9_2/lstm_cell_83/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 22:36:25.651889: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_13_2/lstm_cell_87/recurrent_kernel/v/Assign' id:45493 op device:{requested: '', assigned: ''} def:{{{node lstm_13_2/lstm_cell_87/recurrent_kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_13_2/lstm_cell_87/recurrent_kernel/v, lstm_13_2/lstm_cell_87/recurrent_kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31569 samples, validate on 3513 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:36:30.583963: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:36:42.519979: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_6/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3518"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 22:37:02.662218: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.32313, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 26s 827us/sample - loss: 1.3518 - val_loss: 1.3231\n",
      "Epoch 2/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3499\n",
      "Epoch 2: val_loss improved from 1.32313 to 1.32102, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 19s 603us/sample - loss: 1.3499 - val_loss: 1.3210\n",
      "Epoch 3/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3463\n",
      "Epoch 3: val_loss did not improve from 1.32102\n",
      "31569/31569 [==============================] - 19s 609us/sample - loss: 1.3463 - val_loss: 1.3218\n",
      "Epoch 4/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3466\n",
      "Epoch 4: val_loss improved from 1.32102 to 1.31896, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 673us/sample - loss: 1.3466 - val_loss: 1.3190\n",
      "Epoch 5/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3444\n",
      "Epoch 5: val_loss did not improve from 1.31896\n",
      "31569/31569 [==============================] - 19s 614us/sample - loss: 1.3444 - val_loss: 1.3208\n",
      "Epoch 6/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3430\n",
      "Epoch 6: val_loss did not improve from 1.31896\n",
      "31569/31569 [==============================] - 22s 685us/sample - loss: 1.3430 - val_loss: 1.3245\n",
      "Epoch 7/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3443\n",
      "Epoch 7: val_loss did not improve from 1.31896\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.3443 - val_loss: 1.3202\n",
      "Epoch 8/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3439\n",
      "Epoch 8: val_loss improved from 1.31896 to 1.31868, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 670us/sample - loss: 1.3439 - val_loss: 1.3187\n",
      "Epoch 9/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3389\n",
      "Epoch 9: val_loss improved from 1.31868 to 1.31625, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 20s 625us/sample - loss: 1.3389 - val_loss: 1.3162\n",
      "Epoch 10/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3412\n",
      "Epoch 10: val_loss did not improve from 1.31625\n",
      "31569/31569 [==============================] - 19s 608us/sample - loss: 1.3412 - val_loss: 1.3164\n",
      "Epoch 11/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3368\n",
      "Epoch 11: val_loss did not improve from 1.31625\n",
      "31569/31569 [==============================] - 19s 608us/sample - loss: 1.3368 - val_loss: 1.3185\n",
      "Epoch 12/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3390\n",
      "Epoch 12: val_loss improved from 1.31625 to 1.31421, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 22s 692us/sample - loss: 1.3390 - val_loss: 1.3142\n",
      "Epoch 13/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3383\n",
      "Epoch 13: val_loss did not improve from 1.31421\n",
      "31569/31569 [==============================] - 22s 689us/sample - loss: 1.3383 - val_loss: 1.3176\n",
      "Epoch 14/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3346\n",
      "Epoch 14: val_loss improved from 1.31421 to 1.31294, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 20s 639us/sample - loss: 1.3346 - val_loss: 1.3129\n",
      "Epoch 15/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3333\n",
      "Epoch 15: val_loss did not improve from 1.31294\n",
      "31569/31569 [==============================] - 19s 613us/sample - loss: 1.3333 - val_loss: 1.3186\n",
      "Epoch 16/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3335\n",
      "Epoch 16: val_loss improved from 1.31294 to 1.31229, saving model to ./checkpoints/unknown_person_baseline_2_p19_20.h5\n",
      "31569/31569 [==============================] - 21s 666us/sample - loss: 1.3335 - val_loss: 1.3123\n",
      "Epoch 17/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3292\n",
      "Epoch 17: val_loss did not improve from 1.31229\n",
      "31569/31569 [==============================] - 19s 610us/sample - loss: 1.3292 - val_loss: 1.3159\n",
      "Epoch 18/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3316\n",
      "Epoch 18: val_loss did not improve from 1.31229\n",
      "31569/31569 [==============================] - 19s 611us/sample - loss: 1.3316 - val_loss: 1.3136\n",
      "Epoch 19/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3298\n",
      "Epoch 19: val_loss did not improve from 1.31229\n",
      "31569/31569 [==============================] - 19s 610us/sample - loss: 1.3298 - val_loss: 1.3165\n",
      "Epoch 20/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3299\n",
      "Epoch 20: val_loss did not improve from 1.31229\n",
      "31569/31569 [==============================] - 21s 657us/sample - loss: 1.3299 - val_loss: 1.3143\n",
      "Train on 31569 samples, validate on 3513 samples\n",
      "Epoch 1/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3274\n",
      "Epoch 1: val_loss improved from inf to 1.31560, saving model to ./checkpoints/unknown_person_baseline_p19_21.h5\n",
      "31569/31569 [==============================] - 22s 688us/sample - loss: 1.3274 - val_loss: 1.3156\n",
      "Epoch 2/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3277\n",
      "Epoch 2: val_loss improved from 1.31560 to 1.31148, saving model to ./checkpoints/unknown_person_baseline_p19_21.h5\n",
      "31569/31569 [==============================] - 20s 620us/sample - loss: 1.3277 - val_loss: 1.3115\n",
      "Epoch 3/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3233\n",
      "Epoch 3: val_loss improved from 1.31148 to 1.30851, saving model to ./checkpoints/unknown_person_baseline_p19_21.h5\n",
      "31569/31569 [==============================] - 21s 660us/sample - loss: 1.3233 - val_loss: 1.3085\n",
      "Epoch 4/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3254\n",
      "Epoch 4: val_loss did not improve from 1.30851\n",
      "31569/31569 [==============================] - 22s 685us/sample - loss: 1.3254 - val_loss: 1.3185\n",
      "Epoch 5/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3205\n",
      "Epoch 5: val_loss improved from 1.30851 to 1.30769, saving model to ./checkpoints/unknown_person_baseline_p19_21.h5\n",
      "31569/31569 [==============================] - 22s 685us/sample - loss: 1.3205 - val_loss: 1.3077\n",
      "Epoch 6/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3206\n",
      "Epoch 6: val_loss did not improve from 1.30769\n",
      "31569/31569 [==============================] - 20s 640us/sample - loss: 1.3206 - val_loss: 1.3083\n",
      "Epoch 7/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3182\n",
      "Epoch 7: val_loss improved from 1.30769 to 1.30757, saving model to ./checkpoints/unknown_person_baseline_p19_21.h5\n",
      "31569/31569 [==============================] - 19s 609us/sample - loss: 1.3182 - val_loss: 1.3076\n",
      "Epoch 8/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3333\n",
      "Epoch 8: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 681us/sample - loss: 1.3333 - val_loss: 1.3180\n",
      "Epoch 9/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3478\n",
      "Epoch 9: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 19s 600us/sample - loss: 1.3478 - val_loss: 1.3156\n",
      "Epoch 10/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3361\n",
      "Epoch 10: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 19s 598us/sample - loss: 1.3361 - val_loss: 1.3132\n",
      "Epoch 11/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3342\n",
      "Epoch 11: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 670us/sample - loss: 1.3342 - val_loss: 1.3129\n",
      "Epoch 12/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3294\n",
      "Epoch 12: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 683us/sample - loss: 1.3294 - val_loss: 1.3146\n",
      "Epoch 13/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3404\n",
      "Epoch 13: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 685us/sample - loss: 1.3404 - val_loss: 1.3172\n",
      "Epoch 14/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3425\n",
      "Epoch 14: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 674us/sample - loss: 1.3425 - val_loss: 1.3162\n",
      "Epoch 15/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3432\n",
      "Epoch 15: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 659us/sample - loss: 1.3432 - val_loss: 1.3132\n",
      "Epoch 16/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3449\n",
      "Epoch 16: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 671us/sample - loss: 1.3449 - val_loss: 1.3167\n",
      "Epoch 17/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3575\n",
      "Epoch 17: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 691us/sample - loss: 1.3575 - val_loss: 1.3218\n",
      "Epoch 18/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3549\n",
      "Epoch 18: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 20s 634us/sample - loss: 1.3549 - val_loss: 1.3117\n",
      "Epoch 19/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3504\n",
      "Epoch 19: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 20s 636us/sample - loss: 1.3504 - val_loss: 1.3126\n",
      "Epoch 20/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3559\n",
      "Epoch 20: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 20s 642us/sample - loss: 1.3559 - val_loss: 1.3157\n",
      "Epoch 21/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3539\n",
      "Epoch 21: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 675us/sample - loss: 1.3539 - val_loss: 1.3206\n",
      "Epoch 22/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3720\n",
      "Epoch 22: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 20s 646us/sample - loss: 1.3720 - val_loss: 1.3271\n",
      "Epoch 23/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3626\n",
      "Epoch 23: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 686us/sample - loss: 1.3626 - val_loss: 1.3266\n",
      "Epoch 24/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3566\n",
      "Epoch 24: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 691us/sample - loss: 1.3566 - val_loss: 1.3248\n",
      "Epoch 25/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3529\n",
      "Epoch 25: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 20s 643us/sample - loss: 1.3529 - val_loss: 1.3246\n",
      "Epoch 26/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3480\n",
      "Epoch 26: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 678us/sample - loss: 1.3480 - val_loss: 1.3243\n",
      "Epoch 27/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3501\n",
      "Epoch 27: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 688us/sample - loss: 1.3501 - val_loss: 1.3212\n",
      "Epoch 28/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3457\n",
      "Epoch 28: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 692us/sample - loss: 1.3457 - val_loss: 1.3258\n",
      "Epoch 29/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3426\n",
      "Epoch 29: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 689us/sample - loss: 1.3426 - val_loss: 1.3259\n",
      "Epoch 30/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3372\n",
      "Epoch 30: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 19s 603us/sample - loss: 1.3372 - val_loss: 1.3207\n",
      "Epoch 31/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3401\n",
      "Epoch 31: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 19s 594us/sample - loss: 1.3401 - val_loss: 1.3158\n",
      "Epoch 32/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3374\n",
      "Epoch 32: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 20s 646us/sample - loss: 1.3374 - val_loss: 1.3171\n",
      "Epoch 33/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3372\n",
      "Epoch 33: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 689us/sample - loss: 1.3372 - val_loss: 1.3160\n",
      "Epoch 34/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3361\n",
      "Epoch 34: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 696us/sample - loss: 1.3361 - val_loss: 1.3134\n",
      "Epoch 35/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3343\n",
      "Epoch 35: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 684us/sample - loss: 1.3343 - val_loss: 1.3207\n",
      "Epoch 36/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3337\n",
      "Epoch 36: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.3337 - val_loss: 1.3150\n",
      "Epoch 37/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3301\n",
      "Epoch 37: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.3301 - val_loss: 1.3133\n",
      "Epoch 38/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3290\n",
      "Epoch 38: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 19s 613us/sample - loss: 1.3290 - val_loss: 1.3119\n",
      "Epoch 39/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3276\n",
      "Epoch 39: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 652us/sample - loss: 1.3276 - val_loss: 1.3159\n",
      "Epoch 40/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3266\n",
      "Epoch 40: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 690us/sample - loss: 1.3266 - val_loss: 1.3171\n",
      "Epoch 41/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3272\n",
      "Epoch 41: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 672us/sample - loss: 1.3272 - val_loss: 1.3149\n",
      "Epoch 42/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3266\n",
      "Epoch 42: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 692us/sample - loss: 1.3266 - val_loss: 1.3174\n",
      "Epoch 43/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3270\n",
      "Epoch 43: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.3270 - val_loss: 1.3123\n",
      "Epoch 44/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3210\n",
      "Epoch 44: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 20s 645us/sample - loss: 1.3210 - val_loss: 1.3181\n",
      "Epoch 45/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3239\n",
      "Epoch 45: val_loss did not improve from 1.30757\n",
      "31569/31569 [==============================] - 21s 653us/sample - loss: 1.3239 - val_loss: 1.3150\n",
      "Epoch 46/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3221\n",
      "Epoch 46: val_loss improved from 1.30757 to 1.30520, saving model to ./checkpoints/unknown_person_baseline_p19_21.h5\n",
      "31569/31569 [==============================] - 19s 595us/sample - loss: 1.3221 - val_loss: 1.3052\n",
      "Epoch 47/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3221\n",
      "Epoch 47: val_loss did not improve from 1.30520\n",
      "31569/31569 [==============================] - 21s 655us/sample - loss: 1.3221 - val_loss: 1.3123\n",
      "Epoch 48/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3208\n",
      "Epoch 48: val_loss did not improve from 1.30520\n",
      "31569/31569 [==============================] - 19s 616us/sample - loss: 1.3208 - val_loss: 1.3137\n",
      "Epoch 49/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3199\n",
      "Epoch 49: val_loss did not improve from 1.30520\n",
      "31569/31569 [==============================] - 21s 676us/sample - loss: 1.3199 - val_loss: 1.3080\n",
      "Epoch 50/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3214\n",
      "Epoch 50: val_loss did not improve from 1.30520\n",
      "31569/31569 [==============================] - 21s 662us/sample - loss: 1.3214 - val_loss: 1.3100\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:00:57.227116: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_39/lstm_cell_111/kernel/Assign' id:57398 op device:{requested: '', assigned: ''} def:{{{node lstm_39/lstm_cell_111/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_39/lstm_cell_111/kernel, lstm_39/lstm_cell_111/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:01:00.485073: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_19_3/lstm_cell_130/bias/m/Assign' id:64305 op device:{requested: '', assigned: ''} def:{{{node lstm_19_3/lstm_cell_130/bias/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_19_3/lstm_cell_130/bias/m, lstm_19_3/lstm_cell_130/bias/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:01:03.603099: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_3/cond/Merge' id:63349 op device:{requested: '', assigned: ''} def:{{{node dropout_4_3/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_3/cond/Identity, dropout_4_3/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1919)\n",
      "(1514, 1919)\n",
      "(1644, 1919)\n",
      "(1764, 1919)\n",
      "(1836, 1919)\n",
      "(1699, 1919)\n",
      "(1369, 1919)\n",
      "(1766, 1919)\n",
      "(1631, 1919)\n",
      "(1692, 1919)\n",
      "(1550, 1919)\n",
      "(1920, 1919)\n",
      "(1788, 1919)\n",
      "(1872, 1919)\n",
      "(1692, 1919)\n",
      "(1824, 1919)\n",
      "(971, 1919)\n",
      "(1656, 1919)\n",
      "(1896, 1919)\n",
      "{1: 5.098257038123192, 2: 3.8994081231046107, 4: 10.0, 5: 5.6545855183540015, 6: 6.70942539901818, 8: 7.722812898086568, 9: 5.855784246783422, 10: 6.535241435066094, 11: 6.307422962799383, 12: 8.012191077077564, 13: 6.389319261533441, 17: 8.546040559239067, 21: 7.262175456980359, 22: 1.0, 25: 7.244537398127275, 26: 5.214451972116879, 27: 4.596500272039268, 28: 5.64009987911852, 29: 3.2438907347091295}\n",
      "Train on 31569 samples, validate on 3513 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:05:36.593935: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_7/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31569/31569 [==============================] - ETA: 0s - loss: 8.4193\n",
      "Epoch 1: val_loss improved from inf to 1.32020, saving model to ./checkpoints/unknown_person_p19_21.h5\n",
      "31569/31569 [==============================] - 28s 898us/sample - loss: 8.4193 - val_loss: 1.3202\n",
      "Epoch 2/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.3737\n",
      "Epoch 2: val_loss improved from 1.32020 to 1.31237, saving model to ./checkpoints/unknown_person_p19_21.h5\n",
      "31569/31569 [==============================] - 20s 623us/sample - loss: 8.3737 - val_loss: 1.3124\n",
      "Epoch 3/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.3542\n",
      "Epoch 3: val_loss did not improve from 1.31237\n",
      "31569/31569 [==============================] - 22s 681us/sample - loss: 8.3542 - val_loss: 1.3267\n",
      "Epoch 4/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2552\n",
      "Epoch 4: val_loss did not improve from 1.31237\n",
      "31569/31569 [==============================] - 22s 699us/sample - loss: 8.2552 - val_loss: 1.3192\n",
      "Epoch 5/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2582\n",
      "Epoch 5: val_loss improved from 1.31237 to 1.30931, saving model to ./checkpoints/unknown_person_p19_21.h5\n",
      "31569/31569 [==============================] - 22s 697us/sample - loss: 8.2582 - val_loss: 1.3093\n",
      "Epoch 6/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2248\n",
      "Epoch 6: val_loss did not improve from 1.30931\n",
      "31569/31569 [==============================] - 22s 703us/sample - loss: 8.2248 - val_loss: 1.3171\n",
      "Epoch 7/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2035\n",
      "Epoch 7: val_loss did not improve from 1.30931\n",
      "31569/31569 [==============================] - 20s 628us/sample - loss: 8.2035 - val_loss: 1.3116\n",
      "Epoch 8/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1895\n",
      "Epoch 8: val_loss did not improve from 1.30931\n",
      "31569/31569 [==============================] - 22s 688us/sample - loss: 8.1895 - val_loss: 1.3109\n",
      "Epoch 9/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1987\n",
      "Epoch 9: val_loss did not improve from 1.30931\n",
      "31569/31569 [==============================] - 20s 646us/sample - loss: 8.1987 - val_loss: 1.3107\n",
      "Epoch 10/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1813\n",
      "Epoch 10: val_loss did not improve from 1.30931\n",
      "31569/31569 [==============================] - 22s 698us/sample - loss: 8.1813 - val_loss: 1.3099\n",
      "Epoch 11/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1673\n",
      "Epoch 11: val_loss did not improve from 1.30931\n",
      "31569/31569 [==============================] - 20s 633us/sample - loss: 8.1673 - val_loss: 1.3120\n",
      "Epoch 12/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1466\n",
      "Epoch 12: val_loss improved from 1.30931 to 1.30498, saving model to ./checkpoints/unknown_person_p19_21.h5\n",
      "31569/31569 [==============================] - 19s 616us/sample - loss: 8.1466 - val_loss: 1.3050\n",
      "Epoch 13/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1348\n",
      "Epoch 13: val_loss did not improve from 1.30498\n",
      "31569/31569 [==============================] - 22s 681us/sample - loss: 8.1348 - val_loss: 1.3118\n",
      "Epoch 14/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1256\n",
      "Epoch 14: val_loss improved from 1.30498 to 1.30390, saving model to ./checkpoints/unknown_person_p19_21.h5\n",
      "31569/31569 [==============================] - 20s 646us/sample - loss: 8.1256 - val_loss: 1.3039\n",
      "Epoch 15/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1179\n",
      "Epoch 15: val_loss did not improve from 1.30390\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 8.1179 - val_loss: 1.3063\n",
      "Epoch 16/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1089\n",
      "Epoch 16: val_loss did not improve from 1.30390\n",
      "31569/31569 [==============================] - 22s 701us/sample - loss: 8.1089 - val_loss: 1.3100\n",
      "Epoch 17/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1041\n",
      "Epoch 17: val_loss did not improve from 1.30390\n",
      "31569/31569 [==============================] - 21s 657us/sample - loss: 8.1041 - val_loss: 1.3144\n",
      "Epoch 18/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0916\n",
      "Epoch 18: val_loss did not improve from 1.30390\n",
      "31569/31569 [==============================] - 20s 640us/sample - loss: 8.0916 - val_loss: 1.3070\n",
      "Epoch 19/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0911\n",
      "Epoch 19: val_loss improved from 1.30390 to 1.30071, saving model to ./checkpoints/unknown_person_p19_21.h5\n",
      "31569/31569 [==============================] - 20s 637us/sample - loss: 8.0911 - val_loss: 1.3007\n",
      "Epoch 20/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0863\n",
      "Epoch 20: val_loss did not improve from 1.30071\n",
      "31569/31569 [==============================] - 19s 616us/sample - loss: 8.0863 - val_loss: 1.3095\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:12:44.436069: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_12_4/lstm_cell_160/kernel/Assign' id:78716 op device:{requested: '', assigned: ''} def:{{{node lstm_12_4/lstm_cell_160/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_12_4/lstm_cell_160/kernel, lstm_12_4/lstm_cell_160/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:12:48.579384: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_12_4/lstm_cell_160/kernel/m/Assign' id:83588 op device:{requested: '', assigned: ''} def:{{{node lstm_12_4/lstm_cell_160/kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_12_4/lstm_cell_160/kernel/m, lstm_12_4/lstm_cell_160/kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31569 samples, validate on 3513 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:12:55.134215: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:13:16.500445: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_8/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3206"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:13:39.411806: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.30647, saving model to ./checkpoints/unknown_person_baseline_2_p19_21.h5\n",
      "31569/31569 [==============================] - 32s 1ms/sample - loss: 1.3206 - val_loss: 1.3065\n",
      "Epoch 2/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3188\n",
      "Epoch 2: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 602us/sample - loss: 1.3188 - val_loss: 1.3096\n",
      "Epoch 3/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3195\n",
      "Epoch 3: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 610us/sample - loss: 1.3195 - val_loss: 1.3163\n",
      "Epoch 4/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3155\n",
      "Epoch 4: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 610us/sample - loss: 1.3155 - val_loss: 1.3075\n",
      "Epoch 5/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3141\n",
      "Epoch 5: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 613us/sample - loss: 1.3141 - val_loss: 1.3081\n",
      "Epoch 6/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3133\n",
      "Epoch 6: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 615us/sample - loss: 1.3133 - val_loss: 1.3080\n",
      "Epoch 7/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3118\n",
      "Epoch 7: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 613us/sample - loss: 1.3118 - val_loss: 1.3080\n",
      "Epoch 8/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3089\n",
      "Epoch 8: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 611us/sample - loss: 1.3089 - val_loss: 1.3084\n",
      "Epoch 9/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3072\n",
      "Epoch 9: val_loss did not improve from 1.30647\n",
      "31569/31569 [==============================] - 19s 612us/sample - loss: 1.3072 - val_loss: 1.3097\n",
      "Epoch 10/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3064\n",
      "Epoch 10: val_loss improved from 1.30647 to 1.30285, saving model to ./checkpoints/unknown_person_baseline_2_p19_21.h5\n",
      "31569/31569 [==============================] - 19s 609us/sample - loss: 1.3064 - val_loss: 1.3029\n",
      "Epoch 11/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3054\n",
      "Epoch 11: val_loss did not improve from 1.30285\n",
      "31569/31569 [==============================] - 21s 659us/sample - loss: 1.3054 - val_loss: 1.3044\n",
      "Epoch 12/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3045\n",
      "Epoch 12: val_loss did not improve from 1.30285\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.3045 - val_loss: 1.3031\n",
      "Epoch 13/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3031\n",
      "Epoch 13: val_loss did not improve from 1.30285\n",
      "31569/31569 [==============================] - 20s 645us/sample - loss: 1.3031 - val_loss: 1.3056\n",
      "Epoch 14/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3032\n",
      "Epoch 14: val_loss did not improve from 1.30285\n",
      "31569/31569 [==============================] - 20s 621us/sample - loss: 1.3032 - val_loss: 1.3041\n",
      "Epoch 15/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3023\n",
      "Epoch 15: val_loss did not improve from 1.30285\n",
      "31569/31569 [==============================] - 20s 648us/sample - loss: 1.3023 - val_loss: 1.3029\n",
      "Epoch 16/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3006\n",
      "Epoch 16: val_loss did not improve from 1.30285\n",
      "31569/31569 [==============================] - 22s 695us/sample - loss: 1.3006 - val_loss: 1.3033\n",
      "Epoch 17/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3002\n",
      "Epoch 17: val_loss improved from 1.30285 to 1.30282, saving model to ./checkpoints/unknown_person_baseline_2_p19_21.h5\n",
      "31569/31569 [==============================] - 21s 656us/sample - loss: 1.3002 - val_loss: 1.3028\n",
      "Epoch 18/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2976\n",
      "Epoch 18: val_loss did not improve from 1.30282\n",
      "31569/31569 [==============================] - 19s 599us/sample - loss: 1.2976 - val_loss: 1.3030\n",
      "Epoch 19/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3007\n",
      "Epoch 19: val_loss improved from 1.30282 to 1.29833, saving model to ./checkpoints/unknown_person_baseline_2_p19_21.h5\n",
      "31569/31569 [==============================] - 19s 615us/sample - loss: 1.3007 - val_loss: 1.2983\n",
      "Epoch 20/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2982\n",
      "Epoch 20: val_loss did not improve from 1.29833\n",
      "31569/31569 [==============================] - 19s 605us/sample - loss: 1.2982 - val_loss: 1.2996\n",
      "Train on 31569 samples, validate on 3513 samples\n",
      "Epoch 1/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2967\n",
      "Epoch 1: val_loss improved from inf to 1.29897, saving model to ./checkpoints/unknown_person_baseline_p19_22.h5\n",
      "31569/31569 [==============================] - 21s 671us/sample - loss: 1.2967 - val_loss: 1.2990\n",
      "Epoch 2/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2962\n",
      "Epoch 2: val_loss did not improve from 1.29897\n",
      "31569/31569 [==============================] - 20s 630us/sample - loss: 1.2962 - val_loss: 1.3057\n",
      "Epoch 3/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2946\n",
      "Epoch 3: val_loss improved from 1.29897 to 1.29706, saving model to ./checkpoints/unknown_person_baseline_p19_22.h5\n",
      "31569/31569 [==============================] - 19s 617us/sample - loss: 1.2946 - val_loss: 1.2971\n",
      "Epoch 4/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2916\n",
      "Epoch 4: val_loss did not improve from 1.29706\n",
      "31569/31569 [==============================] - 19s 602us/sample - loss: 1.2916 - val_loss: 1.3005\n",
      "Epoch 5/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2935\n",
      "Epoch 5: val_loss did not improve from 1.29706\n",
      "31569/31569 [==============================] - 20s 637us/sample - loss: 1.2935 - val_loss: 1.3025\n",
      "Epoch 6/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2892\n",
      "Epoch 6: val_loss improved from 1.29706 to 1.29457, saving model to ./checkpoints/unknown_person_baseline_p19_22.h5\n",
      "31569/31569 [==============================] - 23s 713us/sample - loss: 1.2892 - val_loss: 1.2946\n",
      "Epoch 7/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2878\n",
      "Epoch 7: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.2878 - val_loss: 1.2993\n",
      "Epoch 8/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2977\n",
      "Epoch 8: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 669us/sample - loss: 1.2977 - val_loss: 1.2973\n",
      "Epoch 9/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3004\n",
      "Epoch 9: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 664us/sample - loss: 1.3004 - val_loss: 1.2956\n",
      "Epoch 10/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3339\n",
      "Epoch 10: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 699us/sample - loss: 1.3339 - val_loss: 1.3088\n",
      "Epoch 11/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3201\n",
      "Epoch 11: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 699us/sample - loss: 1.3201 - val_loss: 1.3125\n",
      "Epoch 12/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3236\n",
      "Epoch 12: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.3236 - val_loss: 1.3088\n",
      "Epoch 13/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3112\n",
      "Epoch 13: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 20s 646us/sample - loss: 1.3112 - val_loss: 1.3053\n",
      "Epoch 14/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3167\n",
      "Epoch 14: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 19s 600us/sample - loss: 1.3167 - val_loss: 1.3102\n",
      "Epoch 15/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3089\n",
      "Epoch 15: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 668us/sample - loss: 1.3089 - val_loss: 1.3022\n",
      "Epoch 16/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3193\n",
      "Epoch 16: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 694us/sample - loss: 1.3193 - val_loss: 1.3073\n",
      "Epoch 17/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3198\n",
      "Epoch 17: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 652us/sample - loss: 1.3198 - val_loss: 1.3054\n",
      "Epoch 18/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3185\n",
      "Epoch 18: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 695us/sample - loss: 1.3185 - val_loss: 1.3070\n",
      "Epoch 19/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3308\n",
      "Epoch 19: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 684us/sample - loss: 1.3308 - val_loss: 1.3108\n",
      "Epoch 20/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3359\n",
      "Epoch 20: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 19s 614us/sample - loss: 1.3359 - val_loss: 1.3229\n",
      "Epoch 21/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4131\n",
      "Epoch 21: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 657us/sample - loss: 1.4131 - val_loss: 1.3275\n",
      "Epoch 22/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3674\n",
      "Epoch 22: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 20s 634us/sample - loss: 1.3674 - val_loss: 1.3295\n",
      "Epoch 23/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3645\n",
      "Epoch 23: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 695us/sample - loss: 1.3645 - val_loss: 1.3340\n",
      "Epoch 24/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3563\n",
      "Epoch 24: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 694us/sample - loss: 1.3563 - val_loss: 1.3312\n",
      "Epoch 25/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3670\n",
      "Epoch 25: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 654us/sample - loss: 1.3670 - val_loss: 1.3365\n",
      "Epoch 26/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.4165\n",
      "Epoch 26: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.4165 - val_loss: 1.3499\n",
      "Epoch 27/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3797\n",
      "Epoch 27: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 690us/sample - loss: 1.3797 - val_loss: 1.3364\n",
      "Epoch 28/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3691\n",
      "Epoch 28: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 691us/sample - loss: 1.3691 - val_loss: 1.3420\n",
      "Epoch 29/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3609\n",
      "Epoch 29: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 1.3609 - val_loss: 1.3351\n",
      "Epoch 30/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3595\n",
      "Epoch 30: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 653us/sample - loss: 1.3595 - val_loss: 1.3367\n",
      "Epoch 31/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3597\n",
      "Epoch 31: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 661us/sample - loss: 1.3597 - val_loss: 1.3380\n",
      "Epoch 32/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3584\n",
      "Epoch 32: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 689us/sample - loss: 1.3584 - val_loss: 1.3330\n",
      "Epoch 33/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3605\n",
      "Epoch 33: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 672us/sample - loss: 1.3605 - val_loss: 1.3281\n",
      "Epoch 34/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3575\n",
      "Epoch 34: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 683us/sample - loss: 1.3575 - val_loss: 1.3334\n",
      "Epoch 35/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3562\n",
      "Epoch 35: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 671us/sample - loss: 1.3562 - val_loss: 1.3326\n",
      "Epoch 36/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3535\n",
      "Epoch 36: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 20s 621us/sample - loss: 1.3535 - val_loss: 1.3257\n",
      "Epoch 37/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3509\n",
      "Epoch 37: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 651us/sample - loss: 1.3509 - val_loss: 1.3327\n",
      "Epoch 38/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3511\n",
      "Epoch 38: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 690us/sample - loss: 1.3511 - val_loss: 1.3293\n",
      "Epoch 39/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3491\n",
      "Epoch 39: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 20s 648us/sample - loss: 1.3491 - val_loss: 1.3341\n",
      "Epoch 40/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3478\n",
      "Epoch 40: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 19s 606us/sample - loss: 1.3478 - val_loss: 1.3337\n",
      "Epoch 41/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3476\n",
      "Epoch 41: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 19s 606us/sample - loss: 1.3476 - val_loss: 1.3309\n",
      "Epoch 42/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3446\n",
      "Epoch 42: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 19s 603us/sample - loss: 1.3446 - val_loss: 1.3221\n",
      "Epoch 43/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3473\n",
      "Epoch 43: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 20s 639us/sample - loss: 1.3473 - val_loss: 1.3260\n",
      "Epoch 44/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3431\n",
      "Epoch 44: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 687us/sample - loss: 1.3431 - val_loss: 1.3258\n",
      "Epoch 45/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3419\n",
      "Epoch 45: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 21s 664us/sample - loss: 1.3419 - val_loss: 1.3250\n",
      "Epoch 46/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3436\n",
      "Epoch 46: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 681us/sample - loss: 1.3436 - val_loss: 1.3232\n",
      "Epoch 47/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3427\n",
      "Epoch 47: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 690us/sample - loss: 1.3427 - val_loss: 1.3327\n",
      "Epoch 48/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3417\n",
      "Epoch 48: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 22s 690us/sample - loss: 1.3417 - val_loss: 1.3273\n",
      "Epoch 49/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3416\n",
      "Epoch 49: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 20s 630us/sample - loss: 1.3416 - val_loss: 1.3265\n",
      "Epoch 50/50\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3386\n",
      "Epoch 50: val_loss did not improve from 1.29457\n",
      "31569/31569 [==============================] - 19s 599us/sample - loss: 1.3386 - val_loss: 1.3222\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:37:32.694253: W tensorflow/c/c_api.cc:304] Operation '{name:'conv2d_3_5/kernel/Assign' id:95970 op device:{requested: '', assigned: ''} def:{{{node conv2d_3_5/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](conv2d_3_5/kernel, conv2d_3_5/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:37:37.802056: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_12_5/lstm_cell_197/bias/m/Assign' id:102958 op device:{requested: '', assigned: ''} def:{{{node lstm_12_5/lstm_cell_197/bias/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_12_5/lstm_cell_197/bias/m, lstm_12_5/lstm_cell_197/bias/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:37:42.802578: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_5/cond/Merge' id:102107 op device:{requested: '', assigned: ''} def:{{{node dropout_4_5/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_5/cond/Identity, dropout_4_5/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1919)\n",
      "(1514, 1919)\n",
      "(1644, 1919)\n",
      "(1764, 1919)\n",
      "(1836, 1919)\n",
      "(1699, 1919)\n",
      "(1369, 1919)\n",
      "(1766, 1919)\n",
      "(1631, 1919)\n",
      "(1692, 1919)\n",
      "(1550, 1919)\n",
      "(1920, 1919)\n",
      "(1788, 1919)\n",
      "(1872, 1919)\n",
      "(1692, 1919)\n",
      "(1824, 1919)\n",
      "(971, 1919)\n",
      "(1656, 1919)\n",
      "(1896, 1919)\n",
      "{1: 5.047500016658489, 2: 3.9833586951528006, 4: 10.0, 5: 5.637435167789565, 6: 6.590277439249996, 8: 7.650403889459175, 9: 5.837968835648747, 10: 6.496084202877254, 11: 6.2530471884152306, 12: 8.066306048364329, 13: 6.250864575599556, 17: 8.535826624053666, 21: 7.19822743151695, 22: 1.0, 25: 7.285153182700842, 26: 5.30433657302959, 27: 4.508983309596447, 28: 5.418761983152831, 29: 2.981829796531457}\n",
      "Train on 31569 samples, validate on 3513 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:41:56.433012: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_9/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2032\n",
      "Epoch 1: val_loss improved from inf to 1.33679, saving model to ./checkpoints/unknown_person_p19_22.h5\n",
      "31569/31569 [==============================] - 31s 992us/sample - loss: 8.2032 - val_loss: 1.3368\n",
      "Epoch 2/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1915\n",
      "Epoch 2: val_loss improved from 1.33679 to 1.30602, saving model to ./checkpoints/unknown_person_p19_22.h5\n",
      "31569/31569 [==============================] - 19s 603us/sample - loss: 8.1915 - val_loss: 1.3060\n",
      "Epoch 3/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.2228\n",
      "Epoch 3: val_loss did not improve from 1.30602\n",
      "31569/31569 [==============================] - 19s 603us/sample - loss: 8.2228 - val_loss: 1.3243\n",
      "Epoch 4/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.1023\n",
      "Epoch 4: val_loss did not improve from 1.30602\n",
      "31569/31569 [==============================] - 20s 647us/sample - loss: 8.1023 - val_loss: 1.3087\n",
      "Epoch 5/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0736\n",
      "Epoch 5: val_loss did not improve from 1.30602\n",
      "31569/31569 [==============================] - 22s 699us/sample - loss: 8.0736 - val_loss: 1.3088\n",
      "Epoch 6/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0813\n",
      "Epoch 6: val_loss did not improve from 1.30602\n",
      "31569/31569 [==============================] - 21s 677us/sample - loss: 8.0813 - val_loss: 1.3097\n",
      "Epoch 7/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0477\n",
      "Epoch 7: val_loss improved from 1.30602 to 1.30544, saving model to ./checkpoints/unknown_person_p19_22.h5\n",
      "31569/31569 [==============================] - 21s 661us/sample - loss: 8.0477 - val_loss: 1.3054\n",
      "Epoch 8/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0283\n",
      "Epoch 8: val_loss did not improve from 1.30544\n",
      "31569/31569 [==============================] - 22s 696us/sample - loss: 8.0283 - val_loss: 1.3173\n",
      "Epoch 9/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0332\n",
      "Epoch 9: val_loss did not improve from 1.30544\n",
      "31569/31569 [==============================] - 21s 669us/sample - loss: 8.0332 - val_loss: 1.3086\n",
      "Epoch 10/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0144\n",
      "Epoch 10: val_loss improved from 1.30544 to 1.30457, saving model to ./checkpoints/unknown_person_p19_22.h5\n",
      "31569/31569 [==============================] - 21s 663us/sample - loss: 8.0144 - val_loss: 1.3046\n",
      "Epoch 11/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0205\n",
      "Epoch 11: val_loss did not improve from 1.30457\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 8.0205 - val_loss: 1.3057\n",
      "Epoch 12/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0086\n",
      "Epoch 12: val_loss improved from 1.30457 to 1.29816, saving model to ./checkpoints/unknown_person_p19_22.h5\n",
      "31569/31569 [==============================] - 20s 629us/sample - loss: 8.0086 - val_loss: 1.2982\n",
      "Epoch 13/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 8.0111\n",
      "Epoch 13: val_loss did not improve from 1.29816\n",
      "31569/31569 [==============================] - 19s 606us/sample - loss: 8.0111 - val_loss: 1.3134\n",
      "Epoch 14/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 7.9819\n",
      "Epoch 14: val_loss did not improve from 1.29816\n",
      "31569/31569 [==============================] - 22s 696us/sample - loss: 7.9819 - val_loss: 1.3037\n",
      "Epoch 15/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 7.9941\n",
      "Epoch 15: val_loss did not improve from 1.29816\n",
      "31569/31569 [==============================] - 22s 693us/sample - loss: 7.9941 - val_loss: 1.3023\n",
      "Epoch 16/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 7.9781\n",
      "Epoch 16: val_loss did not improve from 1.29816\n",
      "31569/31569 [==============================] - 20s 643us/sample - loss: 7.9781 - val_loss: 1.3017\n",
      "Epoch 17/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 7.9815\n",
      "Epoch 17: val_loss did not improve from 1.29816\n",
      "31569/31569 [==============================] - 21s 672us/sample - loss: 7.9815 - val_loss: 1.3011\n",
      "Epoch 18/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 7.9601\n",
      "Epoch 18: val_loss did not improve from 1.29816\n",
      "31569/31569 [==============================] - 22s 696us/sample - loss: 7.9601 - val_loss: 1.3042\n",
      "Epoch 19/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 7.9595\n",
      "Epoch 19: val_loss improved from 1.29816 to 1.29781, saving model to ./checkpoints/unknown_person_p19_22.h5\n",
      "31569/31569 [==============================] - 22s 701us/sample - loss: 7.9595 - val_loss: 1.2978\n",
      "Epoch 20/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 7.9468\n",
      "Epoch 20: val_loss did not improve from 1.29781\n",
      "31569/31569 [==============================] - 20s 619us/sample - loss: 7.9468 - val_loss: 1.3031\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:49:07.300509: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_16_6/lstm_cell_238/kernel/Assign' id:118114 op device:{requested: '', assigned: ''} def:{{{node lstm_16_6/lstm_cell_238/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_16_6/lstm_cell_238/kernel, lstm_16_6/lstm_cell_238/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 23:49:13.321828: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_11_6/lstm_cell_233/kernel/m/Assign' id:122331 op device:{requested: '', assigned: ''} def:{{{node lstm_11_6/lstm_cell_233/kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_11_6/lstm_cell_233/kernel/m, lstm_11_6/lstm_cell_233/kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31569 samples, validate on 3513 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:49:22.238605: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:49:53.912062: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_10/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2909"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 23:50:15.332149: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.29821, saving model to ./checkpoints/unknown_person_baseline_2_p19_22.h5\n",
      "31569/31569 [==============================] - 34s 1ms/sample - loss: 1.2909 - val_loss: 1.2982\n",
      "Epoch 2/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2886\n",
      "Epoch 2: val_loss did not improve from 1.29821\n",
      "31569/31569 [==============================] - 20s 640us/sample - loss: 1.2886 - val_loss: 1.3006\n",
      "Epoch 3/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.3010\n",
      "Epoch 3: val_loss did not improve from 1.29821\n",
      "31569/31569 [==============================] - 22s 691us/sample - loss: 1.3010 - val_loss: 1.3059\n",
      "Epoch 4/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2959\n",
      "Epoch 4: val_loss did not improve from 1.29821\n",
      "31569/31569 [==============================] - 22s 696us/sample - loss: 1.2959 - val_loss: 1.3021\n",
      "Epoch 5/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2898\n",
      "Epoch 5: val_loss did not improve from 1.29821\n",
      "31569/31569 [==============================] - 22s 686us/sample - loss: 1.2898 - val_loss: 1.3026\n",
      "Epoch 6/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2895\n",
      "Epoch 6: val_loss did not improve from 1.29821\n",
      "31569/31569 [==============================] - 19s 612us/sample - loss: 1.2895 - val_loss: 1.2995\n",
      "Epoch 7/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2888\n",
      "Epoch 7: val_loss did not improve from 1.29821\n",
      "31569/31569 [==============================] - 21s 670us/sample - loss: 1.2888 - val_loss: 1.3027\n",
      "Epoch 8/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2887\n",
      "Epoch 8: val_loss did not improve from 1.29821\n",
      "31569/31569 [==============================] - 19s 605us/sample - loss: 1.2887 - val_loss: 1.3033\n",
      "Epoch 9/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2854\n",
      "Epoch 9: val_loss improved from 1.29821 to 1.29579, saving model to ./checkpoints/unknown_person_baseline_2_p19_22.h5\n",
      "31569/31569 [==============================] - 19s 607us/sample - loss: 1.2854 - val_loss: 1.2958\n",
      "Epoch 10/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2853\n",
      "Epoch 10: val_loss did not improve from 1.29579\n",
      "31569/31569 [==============================] - 19s 601us/sample - loss: 1.2853 - val_loss: 1.3036\n",
      "Epoch 11/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2836\n",
      "Epoch 11: val_loss did not improve from 1.29579\n",
      "31569/31569 [==============================] - 20s 643us/sample - loss: 1.2836 - val_loss: 1.3003\n",
      "Epoch 12/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2867\n",
      "Epoch 12: val_loss improved from 1.29579 to 1.29443, saving model to ./checkpoints/unknown_person_baseline_2_p19_22.h5\n",
      "31569/31569 [==============================] - 22s 697us/sample - loss: 1.2867 - val_loss: 1.2944\n",
      "Epoch 13/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2831\n",
      "Epoch 13: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 20s 631us/sample - loss: 1.2831 - val_loss: 1.3000\n",
      "Epoch 14/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2824\n",
      "Epoch 14: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 20s 619us/sample - loss: 1.2824 - val_loss: 1.3032\n",
      "Epoch 15/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2837\n",
      "Epoch 15: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 19s 615us/sample - loss: 1.2837 - val_loss: 1.2985\n",
      "Epoch 16/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2819\n",
      "Epoch 16: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 19s 612us/sample - loss: 1.2819 - val_loss: 1.3001\n",
      "Epoch 17/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2818\n",
      "Epoch 17: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 21s 660us/sample - loss: 1.2818 - val_loss: 1.3031\n",
      "Epoch 18/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2834\n",
      "Epoch 18: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 22s 691us/sample - loss: 1.2834 - val_loss: 1.2979\n",
      "Epoch 19/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2805\n",
      "Epoch 19: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 22s 690us/sample - loss: 1.2805 - val_loss: 1.2992\n",
      "Epoch 20/20\n",
      "31569/31569 [==============================] - ETA: 0s - loss: 1.2809\n",
      "Epoch 20: val_loss did not improve from 1.29443\n",
      "31569/31569 [==============================] - 21s 655us/sample - loss: 1.2809 - val_loss: 1.2981\n"
     ]
    }
   ],
   "source": [
    "person_nums = [1,2,4,5,6,8,9,10,11,12,13,17,19,21,22,25,26,27,28,29]\n",
    "## Build the baseline model for emotion recognition with dropout layers\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, SimpleRNN, LSTM, Conv2D, Flatten, MaxPooling2D, GRU, AveragePooling2D, Dropout, Lambda\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "def individual_model(features_list):\n",
    "    input_layers = []\n",
    "    hidden_layers = []\n",
    "    combined_feature = np.empty((len(features_list[0]),0))\n",
    "    for i, feature in enumerate(features_list):\n",
    "        \n",
    "        if len(feature.shape) == 3:\n",
    "            input_i = Input(shape=(feature.shape[1], feature.shape[2]))\n",
    "            input_layers.append(input_i)\n",
    "\n",
    "            hidden_i = input_i[:,:,:,None]\n",
    "            hidden_i = Conv2D(32, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(16, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(8, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(4, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Flatten()(hidden_i)\n",
    "\n",
    "            hidden_layers.append(hidden_i)\n",
    "        elif feature.shape[1] <20:\n",
    "            combined_feature = np.hstack((combined_feature, feature))\n",
    "            \n",
    "        else:  # For series features\n",
    "            input_i = Input(shape=(feature.shape[1],))\n",
    "            input_layers.append(input_i)\n",
    "            hidden_i = Lambda(lambda x: x[:, :, None])(input_i)  # Add a new dimension\n",
    "            hidden_i = LSTM(4)(hidden_i)\n",
    "            hidden_layers.append(hidden_i)\n",
    "    input_i = Input(shape=(combined_feature.shape[1],))\n",
    "    input_layers.append(input_i)\n",
    "    dense_num = np.max((1, int(combined_feature.shape[1]/2)))\n",
    "    hidden_i = Dense(dense_num, activation='relu')(input_i)\n",
    "    hidden_layers.append(hidden_i)\n",
    "    print(combined_feature.shape)\n",
    "    concat_layer = concatenate(hidden_layers)\n",
    "    h = Dropout(0.2)(concat_layer)\n",
    "    h = Dense(64, activation='relu')(h)\n",
    "    h = Dense(32, activation='relu')(h)\n",
    "    output_layer = Dense(2)(h)\n",
    "    model = Model(inputs=input_layers, outputs=output_layer)\n",
    "    model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "    return model\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.callbacks import Callback\n",
    "import numpy as np\n",
    "\n",
    "class PruningCallback(tf.keras.callbacks.Callback):\n",
    "    def __init__(self, initial_pruning_factor=0.1, final_pruning_factor=0.5, start_epoch=0, end_epoch=None, frequency=1):\n",
    "        super(PruningCallback, self).__init__()\n",
    "        self.initial_pruning_factor = initial_pruning_factor\n",
    "        self.final_pruning_factor = final_pruning_factor\n",
    "        self.start_epoch = start_epoch\n",
    "        self.end_epoch = end_epoch if end_epoch is not None else np.inf\n",
    "        self.frequency = frequency\n",
    "        self.pruned_weights = {}\n",
    "        self.layer_importance = {}\n",
    "\n",
    "    def get_pruning_factor(self, epoch):\n",
    "        if epoch < self.start_epoch:\n",
    "            return 0\n",
    "        if epoch > self.end_epoch:\n",
    "            return self.final_pruning_factor\n",
    "        return self.initial_pruning_factor + (self.final_pruning_factor - self.initial_pruning_factor) * (epoch - self.start_epoch) / (self.end_epoch - self.start_epoch)\n",
    "\n",
    "    def on_train_begin(self, logs=None):\n",
    "        total_weight_magnitude = 0\n",
    "        for layer in self.model.layers:\n",
    "            if hasattr(layer, 'get_weights'):\n",
    "                weights = layer.get_weights()\n",
    "                layer_norm = sum(np.linalg.norm(w) for w in weights)\n",
    "                total_weight_magnitude += layer_norm\n",
    "                self.layer_importance[layer.name] = layer_norm\n",
    "    \n",
    "        # Normalize the layer importance values so they sum up to 1\n",
    "        for layer_name in self.layer_importance:\n",
    "            self.layer_importance[layer_name] /= total_weight_magnitude\n",
    "    # def on_train_begin(self, logs=None):\n",
    "    #     total_weight_magnitude = sum([np.linalg.norm(layer.get_weights()) for layer in self.model.layers if hasattr(layer, 'get_weights')])\n",
    "    #     for layer in self.model.layers:\n",
    "    #         if hasattr(layer, 'get_weights'):\n",
    "    #             self.layer_importance[layer.name] = np.linalg.norm(layer.get_weights()) / total_weight_magnitude\n",
    "\n",
    "    def get_layer_pruning_factor(self, layer_name, global_pruning_factor):\n",
    "        if layer_name in self.layer_importance:\n",
    "            importance = self.layer_importance[layer_name]\n",
    "            adjusted_pruning_factor = global_pruning_factor * (1 - importance)\n",
    "            return min(adjusted_pruning_factor, 1)  # Ensure the pruning factor is not greater than 1\n",
    "        return global_pruning_factor\n",
    "    def prune_weights(self, layer, global_pruning_factor):\n",
    "        \n",
    "        weights = layer.get_weights()\n",
    "        layer_name = layer.name\n",
    "        pruning_factor = self.get_layer_pruning_factor(layer_name, global_pruning_factor)\n",
    "\n",
    "        if layer_name not in self.pruned_weights:\n",
    "            self.pruned_weights[layer_name] = [np.zeros_like(w, dtype=bool) for w in weights]\n",
    "        \n",
    "        for i in range(len(weights)):\n",
    "            weight = weights[i]\n",
    "            # print(weight.shape)\n",
    "            # print(weight.size)\n",
    "            if weight.ndim > 1:  # Only prune dense or convolutional layers\n",
    "                unpruned_weights = np.logical_not(self.pruned_weights[layer_name][i])\n",
    "                num_unpruned = np.sum(unpruned_weights)\n",
    "                num_pruning = min(num_unpruned, int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i]))\n",
    "                num_pruning = int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i])\n",
    "                if num_pruning > 0:\n",
    "                    unpruned_flat_indices = np.flatnonzero(unpruned_weights)\n",
    "                    abs_unpruned_weights = np.abs(weight[unpruned_weights])\n",
    "                    pruning_flat_indices = np.argpartition(abs_unpruned_weights, num_pruning)[:num_pruning]\n",
    "                    \n",
    "                    indices = np.unravel_index(pruning_flat_indices, weight.shape)\n",
    "                    self.pruned_weights[layer_name][i][indices] = True\n",
    "\n",
    "                weights[i] = weights[i]*(~self.pruned_weights[layer_name][i])\n",
    "                \n",
    "        layer.set_weights(weights)\n",
    "\n",
    "    def on_epoch_end(self, epoch, logs=None):\n",
    "        if (epoch - self.start_epoch) % self.frequency != 0:\n",
    "            return\n",
    "\n",
    "        pruning_factor = self.get_pruning_factor(epoch)\n",
    "        for layer in self.model.layers:\n",
    "            if isinstance(layer, (tf.keras.layers.Dense, tf.keras.layers.Conv2D)):\n",
    "                self.prune_weights(layer, pruning_factor)\n",
    "from feature_emotion import feature_extract, split_data, label_unique_tuples, split_data_unknown\n",
    "gts, sensor_nums, walk_nums, trace_nums, people_nums, spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features = feature_extract(person_nums)\n",
    "\n",
    "walk_nums_all = np.squeeze(walk_nums)\n",
    "trace_nums_all = np.squeeze(trace_nums)\n",
    "people_nums_all = np.squeeze(people_nums)\n",
    "\n",
    "## 0: train, 1: validation 2: test\n",
    "\n",
    "test_person_id = [19]\n",
    "flag_tr_val_te = split_data_unknown(test_person_id, walk_nums_all, trace_nums_all, people_nums_all, person_nums, rand_seed = 42)\n",
    "## Data Normalization before training ans testing\n",
    "import tensorflow as tf\n",
    "tf.compat.v1.disable_v2_behavior()\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, LSTM\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "scalers = []\n",
    "X_train_normalized = []\n",
    "X_val_normalized = []\n",
    "X_test_normalized = []\n",
    "train_idx = np.where(flag_tr_val_te ==0)[0]\n",
    "np.random.shuffle(train_idx)\n",
    "val_idx = np.where(flag_tr_val_te ==1)[0]\n",
    "test_idx = np.where(flag_tr_val_te ==2)[0]\n",
    "\n",
    "for i, feature in enumerate([spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features]):\n",
    "    scaler = StandardScaler()\n",
    "    if len(feature.shape)==2:\n",
    "        X_train_i = feature[train_idx,:]\n",
    "        X_val_i = feature[val_idx,:]\n",
    "        X_test_i = feature[test_idx,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i)\n",
    "        scalers.append(scaler)\n",
    "    else:\n",
    "        X_train_i = feature[train_idx,:,:]\n",
    "        X_val_i = feature[val_idx,:,:]\n",
    "        X_test_i = feature[test_idx,:,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i.reshape(X_train_i.shape[0], -1)).reshape(X_train_i.shape)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i.reshape(X_val_i.shape[0], -1)).reshape(X_val_i.shape)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i.reshape(X_test_i.shape[0], -1)).reshape(X_test_i.shape)\n",
    "        scalers.append(scaler)\n",
    "    X_train_normalized.append(X_train_normalized_i)\n",
    "    X_val_normalized.append(X_val_normalized_i)\n",
    "    X_test_normalized.append(X_test_normalized_i)\n",
    "y_train = gts[train_idx,:]\n",
    "y_val = gts[val_idx,:]\n",
    "y_test = gts[test_idx,:]\n",
    "X_train_normalized_new = []\n",
    "combined_feature = np.empty((len(X_train_normalized[0]),0))\n",
    "for feature in X_train_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_train_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_train_normalized_new.append(feature)\n",
    "X_train_normalized_new.append(combined_feature)\n",
    "\n",
    "X_val_normalized_new = []\n",
    "combined_feature = np.empty((len(X_val_normalized[0]),0))\n",
    "for feature in X_val_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_val_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_val_normalized_new.append(feature)\n",
    "X_val_normalized_new.append(combined_feature)\n",
    "\n",
    "X_test_normalized_new = []\n",
    "combined_feature = np.empty((len(X_test_normalized[0]),0))\n",
    "for feature in X_test_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_test_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_test_normalized_new.append(feature)\n",
    "X_test_normalized_new.append(combined_feature)\n",
    "\n",
    "model = individual_model(X_train_normalized)\n",
    "model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "num_epochs = 50\n",
    "\n",
    "\n",
    "# Gradually prune weights in dense and convolutional layers from 10% to 50% over the course of training, starting from epoch 0.\n",
    "\n",
    "\n",
    "rates = [0.4, 0.5, 0.6]\n",
    "idx = 20\n",
    "for r in rates:\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=0.01, final_pruning_factor=r, start_epoch=5, end_epoch=20, frequency=1)\n",
    "    model.fit(X_train_normalized_new, y_train, epochs=num_epochs, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import tensorflow as tf\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    from tensorflow.keras.models import Model\n",
    "    layers = model.layers\n",
    "    second_last_layer_output = layers[-4].output\n",
    "    feature_extractor_model = Model(inputs=model.input, outputs=second_last_layer_output)\n",
    "    train_features = feature_extractor_model.predict(X_train_normalized_new)\n",
    "    test_features = feature_extractor_model.predict(X_test_normalized_new)\n",
    "    \n",
    "    p_train = people_nums[train_idx,:]\n",
    "    p_val = people_nums[val_idx,:]\n",
    "    p_test = people_nums[test_idx,:]\n",
    "    ## Calculate the distance between test person and training person\n",
    "    def euclidean_distance(a, b):\n",
    "        return np.sqrt(np.sum((a - b) ** 2, axis=1))\n",
    "    \n",
    "    distance_dict = {}\n",
    "    for ii in range(len(person_nums)):\n",
    "        if person_nums[ii] == test_person_id[0]:\n",
    "            continue\n",
    "        else:\n",
    "            \n",
    "            ind = np.where(p_train ==person_nums[ii])[0]\n",
    "            tmp_train_features = train_features[ind, :]\n",
    "            distances = np.array([euclidean_distance(train_sample, test_features) for train_sample in tmp_train_features])\n",
    "            print(distances.shape)\n",
    "            average_distances = np.mean(distances, axis=1)\n",
    "    \n",
    "            # Step 4: Find the overall average distance\n",
    "            overall_average_distance = np.mean(average_distances)\n",
    "            distance_dict[person_nums[ii]] = overall_average_distance\n",
    "    \n",
    "    \n",
    "    def normalize_to_weights(distance_dict):\n",
    "        distances = np.array(list(distance_dict.values()))\n",
    "        # Handle the case where a distance is zero to avoid division by zero\n",
    "        distances = np.clip(distances, a_min=1e-10, a_max=None)\n",
    "        weights = 1 / distances\n",
    "        normalized_weights = weights\n",
    "        # normalized_weights = weights / sum(weights)\n",
    "        # print(sum(weights))\n",
    "        # print(sum(normalized_weights))\n",
    "        # Assign the normalized weights back to the dictionary\n",
    "        normalized_weight_dict = dict(zip(distance_dict.keys(), normalized_weights))\n",
    "        return normalized_weight_dict\n",
    "    def scale_dict_values(my_dict):\n",
    "        scaled_dict = my_dict.copy()\n",
    "        min_val = min(scaled_dict.values())\n",
    "        max_val = max(scaled_dict.values())\n",
    "        \n",
    "        for key in scaled_dict:\n",
    "            scaled_dict[key] = 1 + 9 * (scaled_dict[key] - min_val) / (max_val - min_val)\n",
    "        \n",
    "        return scaled_dict\n",
    "    weights_dict = normalize_to_weights(distance_dict)\n",
    "    weights_dict = scale_dict_values(weights_dict)\n",
    "    print(weights_dict)\n",
    "    \n",
    "    w_train = np.zeros_like(p_train)\n",
    "    for i in range(len(w_train)):\n",
    "        w_train[i] = weights_dict[int(p_train[i])]\n",
    "    \n",
    "    w_train = np.squeeze(w_train)\n",
    "    \n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,sample_weight= w_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    model_name = './checkpoints/unknown_person_baseline_2_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    idx += 1\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f71b59e4-6581-4ea8-994d-a02a6654ab6b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
