{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c77f8da1-2837-4bf7-b3f4-dfcaa7ab42f6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-08T06:32:54.938344Z",
     "iopub.status.busy": "2023-11-08T06:32:54.938026Z",
     "iopub.status.idle": "2023-11-08T06:32:55.062976Z",
     "shell.execute_reply": "2023-11-08T06:32:55.062262Z"
    }
   },
   "outputs": [],
   "source": [
    "import scipy.io\n",
    "import numpy as np\n",
    "import random\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3fe25376-b856-4296-ba02-5e3771ff9451",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-08T06:32:55.066094Z",
     "iopub.status.busy": "2023-11-08T06:32:55.065871Z",
     "iopub.status.idle": "2023-11-08T09:21:45.093384Z",
     "shell.execute_reply": "2023-11-08T09:21:45.092413Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 01:32:55.372631: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/usr/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1, this may cause problems\n",
      "  _warn((\"h5py is running against HDF5 {0} when it was built against {1}, \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "35213\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "non-resource variables are not supported in the long term\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 01:34:43.566479: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.579118: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.579361: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.583230: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.583470: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.583682: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.686869: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.687122: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.687335: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:43.687506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:41:00.0, compute capability: 8.6\n",
      "2023-11-08 01:34:43.688108: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 01:34:44.956889: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:44.957193: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:44.957406: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:44.957857: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:44.958071: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 01:34:44.958235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:41:00.0, compute capability: 8.6\n",
      "2023-11-08 01:34:44.958272: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n",
      "2023-11-08 01:34:44.990782: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled\n",
      "2023-11-08 01:34:45.249934: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_13/lstm_cell_13/bias/Assign' id:2190 op device:{requested: '', assigned: ''} def:{{{node lstm_13/lstm_cell_13/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_13/lstm_cell_13/bias, lstm_13/lstm_cell_13/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 01:34:45.456382: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_1' id:3634 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_1}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 0 0 0...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 01:34:45.492880: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_2' id:3635 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_2}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 1 1 1...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "(31674, 95)\n",
      "Train on 31674 samples, validate on 3539 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 01:34:51.825058: W tensorflow/c/c_api.cc:304] Operation '{name:'training/Adam/dense/kernel/v/Assign' id:17594 op device:{requested: '', assigned: ''} def:{{{node training/Adam/dense/kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](training/Adam/dense/kernel/v, training/Adam/dense/kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 01:34:58.716818: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n",
      "2023-11-08 01:35:03.150047: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "2023-11-08 01:35:03.166278: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8902\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31674/31674 [==============================] - ETA: 0s - loss: 3.4718"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2335: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates = self.state_updates\n",
      "2023-11-08 01:35:32.853592: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_1/mul' id:6477 op device:{requested: '', assigned: ''} def:{{{node loss_1/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_1/mul/x, loss_1/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 2.17385, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 43s 1ms/sample - loss: 3.4718 - val_loss: 2.1738\n",
      "Epoch 2/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.8243\n",
      "Epoch 2: val_loss improved from 2.17385 to 1.60727, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 30s 950us/sample - loss: 1.8243 - val_loss: 1.6073\n",
      "Epoch 3/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.5969\n",
      "Epoch 3: val_loss improved from 1.60727 to 1.51930, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.5969 - val_loss: 1.5193\n",
      "Epoch 4/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.5461\n",
      "Epoch 4: val_loss improved from 1.51930 to 1.49834, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.5461 - val_loss: 1.4983\n",
      "Epoch 5/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.5208\n",
      "Epoch 5: val_loss improved from 1.49834 to 1.47351, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 30s 962us/sample - loss: 1.5208 - val_loss: 1.4735\n",
      "Epoch 6/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.5059\n",
      "Epoch 6: val_loss improved from 1.47351 to 1.46585, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 973us/sample - loss: 1.5059 - val_loss: 1.4658\n",
      "Epoch 7/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4940\n",
      "Epoch 7: val_loss improved from 1.46585 to 1.44984, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.4940 - val_loss: 1.4498\n",
      "Epoch 8/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4890\n",
      "Epoch 8: val_loss improved from 1.44984 to 1.44564, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 964us/sample - loss: 1.4890 - val_loss: 1.4456\n",
      "Epoch 9/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4886\n",
      "Epoch 9: val_loss improved from 1.44564 to 1.44062, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 991us/sample - loss: 1.4886 - val_loss: 1.4406\n",
      "Epoch 10/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4776\n",
      "Epoch 10: val_loss improved from 1.44062 to 1.43667, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 30s 960us/sample - loss: 1.4776 - val_loss: 1.4367\n",
      "Epoch 11/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4763\n",
      "Epoch 11: val_loss improved from 1.43667 to 1.43361, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4763 - val_loss: 1.4336\n",
      "Epoch 12/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4718\n",
      "Epoch 12: val_loss improved from 1.43361 to 1.42599, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4718 - val_loss: 1.4260\n",
      "Epoch 13/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4810\n",
      "Epoch 13: val_loss did not improve from 1.42599\n",
      "31674/31674 [==============================] - 31s 987us/sample - loss: 1.4810 - val_loss: 1.4326\n",
      "Epoch 14/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4695\n",
      "Epoch 14: val_loss did not improve from 1.42599\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.4695 - val_loss: 1.4263\n",
      "Epoch 15/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4755\n",
      "Epoch 15: val_loss improved from 1.42599 to 1.42468, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 986us/sample - loss: 1.4755 - val_loss: 1.4247\n",
      "Epoch 16/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4663\n",
      "Epoch 16: val_loss improved from 1.42468 to 1.42360, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4663 - val_loss: 1.4236\n",
      "Epoch 17/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4634\n",
      "Epoch 17: val_loss improved from 1.42360 to 1.42296, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4634 - val_loss: 1.4230\n",
      "Epoch 18/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4594\n",
      "Epoch 18: val_loss improved from 1.42296 to 1.42145, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 977us/sample - loss: 1.4594 - val_loss: 1.4215\n",
      "Epoch 19/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4613\n",
      "Epoch 19: val_loss improved from 1.42145 to 1.41854, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 993us/sample - loss: 1.4613 - val_loss: 1.4185\n",
      "Epoch 20/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4601\n",
      "Epoch 20: val_loss did not improve from 1.41854\n",
      "31674/31674 [==============================] - 31s 965us/sample - loss: 1.4601 - val_loss: 1.4202\n",
      "Epoch 21/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4550\n",
      "Epoch 21: val_loss improved from 1.41854 to 1.41649, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4550 - val_loss: 1.4165\n",
      "Epoch 22/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.5230\n",
      "Epoch 22: val_loss did not improve from 1.41649\n",
      "31674/31674 [==============================] - 30s 943us/sample - loss: 1.5230 - val_loss: 1.4422\n",
      "Epoch 23/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4750\n",
      "Epoch 23: val_loss did not improve from 1.41649\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.4750 - val_loss: 1.4326\n",
      "Epoch 24/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4529\n",
      "Epoch 24: val_loss did not improve from 1.41649\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.4529 - val_loss: 1.4250\n",
      "Epoch 25/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4423\n",
      "Epoch 25: val_loss did not improve from 1.41649\n",
      "31674/31674 [==============================] - 31s 969us/sample - loss: 1.4423 - val_loss: 1.4167\n",
      "Epoch 26/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4350\n",
      "Epoch 26: val_loss improved from 1.41649 to 1.41533, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4350 - val_loss: 1.4153\n",
      "Epoch 27/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4303\n",
      "Epoch 27: val_loss improved from 1.41533 to 1.40752, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 974us/sample - loss: 1.4303 - val_loss: 1.4075\n",
      "Epoch 28/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4318\n",
      "Epoch 28: val_loss improved from 1.40752 to 1.40588, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 994us/sample - loss: 1.4318 - val_loss: 1.4059\n",
      "Epoch 29/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4287\n",
      "Epoch 29: val_loss did not improve from 1.40588\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.4287 - val_loss: 1.4098\n",
      "Epoch 30/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4272\n",
      "Epoch 30: val_loss did not improve from 1.40588\n",
      "31674/31674 [==============================] - 31s 994us/sample - loss: 1.4272 - val_loss: 1.4073\n",
      "Epoch 31/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4222\n",
      "Epoch 31: val_loss did not improve from 1.40588\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4222 - val_loss: 1.4074\n",
      "Epoch 32/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4235\n",
      "Epoch 32: val_loss improved from 1.40588 to 1.40435, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 993us/sample - loss: 1.4235 - val_loss: 1.4044\n",
      "Epoch 33/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4236\n",
      "Epoch 33: val_loss improved from 1.40435 to 1.40370, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.4236 - val_loss: 1.4037\n",
      "Epoch 34/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4172\n",
      "Epoch 34: val_loss improved from 1.40370 to 1.40128, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 974us/sample - loss: 1.4172 - val_loss: 1.4013\n",
      "Epoch 35/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4162\n",
      "Epoch 35: val_loss did not improve from 1.40128\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.4162 - val_loss: 1.4025\n",
      "Epoch 36/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4141\n",
      "Epoch 36: val_loss improved from 1.40128 to 1.39909, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1000us/sample - loss: 1.4141 - val_loss: 1.3991\n",
      "Epoch 37/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4114\n",
      "Epoch 37: val_loss did not improve from 1.39909\n",
      "31674/31674 [==============================] - 32s 998us/sample - loss: 1.4114 - val_loss: 1.4047\n",
      "Epoch 38/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4089\n",
      "Epoch 38: val_loss improved from 1.39909 to 1.39814, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 966us/sample - loss: 1.4089 - val_loss: 1.3981\n",
      "Epoch 39/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4080\n",
      "Epoch 39: val_loss did not improve from 1.39814\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.4080 - val_loss: 1.4012\n",
      "Epoch 40/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4057\n",
      "Epoch 40: val_loss improved from 1.39814 to 1.39147, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.4057 - val_loss: 1.3915\n",
      "Epoch 41/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4046\n",
      "Epoch 41: val_loss did not improve from 1.39147\n",
      "31674/31674 [==============================] - 29s 924us/sample - loss: 1.4046 - val_loss: 1.3967\n",
      "Epoch 42/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4037\n",
      "Epoch 42: val_loss did not improve from 1.39147\n",
      "31674/31674 [==============================] - 31s 992us/sample - loss: 1.4037 - val_loss: 1.3927\n",
      "Epoch 43/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3987\n",
      "Epoch 43: val_loss improved from 1.39147 to 1.38849, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3987 - val_loss: 1.3885\n",
      "Epoch 44/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3994\n",
      "Epoch 44: val_loss did not improve from 1.38849\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3994 - val_loss: 1.3910\n",
      "Epoch 45/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3980\n",
      "Epoch 45: val_loss improved from 1.38849 to 1.38790, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 998us/sample - loss: 1.3980 - val_loss: 1.3879\n",
      "Epoch 46/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3979\n",
      "Epoch 46: val_loss improved from 1.38790 to 1.38779, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 29s 925us/sample - loss: 1.3979 - val_loss: 1.3878\n",
      "Epoch 47/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3940\n",
      "Epoch 47: val_loss did not improve from 1.38779\n",
      "31674/31674 [==============================] - 31s 972us/sample - loss: 1.3940 - val_loss: 1.3897\n",
      "Epoch 48/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3911\n",
      "Epoch 48: val_loss improved from 1.38779 to 1.38451, saving model to ./checkpoints/unknown_person_baseline_p4_20.h5\n",
      "31674/31674 [==============================] - 29s 925us/sample - loss: 1.3911 - val_loss: 1.3845\n",
      "Epoch 49/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3908\n",
      "Epoch 49: val_loss did not improve from 1.38451\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3908 - val_loss: 1.3857\n",
      "Epoch 50/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3914\n",
      "Epoch 50: val_loss did not improve from 1.38451\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3914 - val_loss: 1.3867\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 02:01:33.208430: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_17_1/lstm_cell_54/recurrent_kernel/Assign' id:21380 op device:{requested: '', assigned: ''} def:{{{node lstm_17_1/lstm_cell_54/recurrent_kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_17_1/lstm_cell_54/recurrent_kernel, lstm_17_1/lstm_cell_54/recurrent_kernel/Initializer/mul_1)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 02:01:36.193210: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_2_1/lstm_cell_39/recurrent_kernel/m/Assign' id:25287 op device:{requested: '', assigned: ''} def:{{{node lstm_2_1/lstm_cell_39/recurrent_kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_2_1/lstm_cell_39/recurrent_kernel/m, lstm_2_1/lstm_cell_39/recurrent_kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates=self.state_updates,\n",
      "2023-11-08 02:01:38.701772: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_1/cond/Merge' id:24591 op device:{requested: '', assigned: ''} def:{{{node dropout_4_1/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_1/cond/Identity, dropout_4_1/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1788)\n",
      "(1514, 1788)\n",
      "(1752, 1788)\n",
      "(1872, 1788)\n",
      "(1735, 1788)\n",
      "(1285, 1788)\n",
      "(1838, 1788)\n",
      "(1594, 1788)\n",
      "(1788, 1788)\n",
      "(1538, 1788)\n",
      "(1920, 1788)\n",
      "(1679, 1788)\n",
      "(1800, 1788)\n",
      "(1860, 1788)\n",
      "(1692, 1788)\n",
      "(1824, 1788)\n",
      "(958, 1788)\n",
      "(1680, 1788)\n",
      "(1860, 1788)\n",
      "{1: 4.936073243114839, 2: 4.748312983018414, 5: 4.6863568902068025, 6: 5.890386390705625, 8: 8.549182814079467, 9: 6.9576874818685095, 10: 7.365917061530247, 11: 8.110580622143633, 12: 8.32640587751611, 13: 6.28725206781583, 17: 9.578639466977712, 19: 10.0, 21: 8.099092989997724, 22: 1.0, 25: 7.980461535412191, 26: 4.99247111424506, 27: 6.250605283974435, 28: 5.644909277977754, 29: 2.171049557306323}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_2790249/2921439139.py:300: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)\n",
      "  w_train[i] = weights_dict[int(p_train[i])]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31674 samples, validate on 3539 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 02:07:12.992643: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_5/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3766\n",
      "Epoch 1: val_loss improved from inf to 1.39444, saving model to ./checkpoints/unknown_person_p4_20.h5\n",
      "31674/31674 [==============================] - 42s 1ms/sample - loss: 9.3766 - val_loss: 1.3944\n",
      "Epoch 2/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3096\n",
      "Epoch 2: val_loss did not improve from 1.39444\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.3096 - val_loss: 1.4038\n",
      "Epoch 3/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2727\n",
      "Epoch 3: val_loss did not improve from 1.39444\n",
      "31674/31674 [==============================] - 31s 963us/sample - loss: 9.2727 - val_loss: 1.3952\n",
      "Epoch 4/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2344\n",
      "Epoch 4: val_loss did not improve from 1.39444\n",
      "31674/31674 [==============================] - 31s 989us/sample - loss: 9.2344 - val_loss: 1.4099\n",
      "Epoch 5/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2085\n",
      "Epoch 5: val_loss improved from 1.39444 to 1.38940, saving model to ./checkpoints/unknown_person_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.2085 - val_loss: 1.3894\n",
      "Epoch 6/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1951\n",
      "Epoch 6: val_loss did not improve from 1.38940\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.1951 - val_loss: 1.4061\n",
      "Epoch 7/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1657\n",
      "Epoch 7: val_loss improved from 1.38940 to 1.38789, saving model to ./checkpoints/unknown_person_p4_20.h5\n",
      "31674/31674 [==============================] - 30s 950us/sample - loss: 9.1657 - val_loss: 1.3879\n",
      "Epoch 8/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1534\n",
      "Epoch 8: val_loss did not improve from 1.38789\n",
      "31674/31674 [==============================] - 30s 949us/sample - loss: 9.1534 - val_loss: 1.4045\n",
      "Epoch 9/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1476\n",
      "Epoch 9: val_loss did not improve from 1.38789\n",
      "31674/31674 [==============================] - 29s 923us/sample - loss: 9.1476 - val_loss: 1.3899\n",
      "Epoch 10/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1431\n",
      "Epoch 10: val_loss improved from 1.38789 to 1.38051, saving model to ./checkpoints/unknown_person_p4_20.h5\n",
      "31674/31674 [==============================] - 30s 962us/sample - loss: 9.1431 - val_loss: 1.3805\n",
      "Epoch 11/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1107\n",
      "Epoch 11: val_loss improved from 1.38051 to 1.38050, saving model to ./checkpoints/unknown_person_p4_20.h5\n",
      "31674/31674 [==============================] - 30s 951us/sample - loss: 9.1107 - val_loss: 1.3805\n",
      "Epoch 12/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0800\n",
      "Epoch 12: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 32s 997us/sample - loss: 9.0800 - val_loss: 1.3823\n",
      "Epoch 13/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0855\n",
      "Epoch 13: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 31s 983us/sample - loss: 9.0855 - val_loss: 1.3839\n",
      "Epoch 14/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0565\n",
      "Epoch 14: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 31s 965us/sample - loss: 9.0565 - val_loss: 1.3826\n",
      "Epoch 15/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0514\n",
      "Epoch 15: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 31s 993us/sample - loss: 9.0514 - val_loss: 1.3808\n",
      "Epoch 16/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0528\n",
      "Epoch 16: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 31s 965us/sample - loss: 9.0528 - val_loss: 1.3821\n",
      "Epoch 17/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0379\n",
      "Epoch 17: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 31s 990us/sample - loss: 9.0379 - val_loss: 1.3849\n",
      "Epoch 18/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0320\n",
      "Epoch 18: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.0320 - val_loss: 1.3887\n",
      "Epoch 19/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0094\n",
      "Epoch 19: val_loss did not improve from 1.38050\n",
      "31674/31674 [==============================] - 31s 988us/sample - loss: 9.0094 - val_loss: 1.3885\n",
      "Epoch 20/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0052\n",
      "Epoch 20: val_loss improved from 1.38050 to 1.37881, saving model to ./checkpoints/unknown_person_p4_20.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.0052 - val_loss: 1.3788\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 02:17:48.451439: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_18_2/lstm_cell_92/kernel/Assign' id:40918 op device:{requested: '', assigned: ''} def:{{{node lstm_18_2/lstm_cell_92/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_18_2/lstm_cell_92/kernel, lstm_18_2/lstm_cell_92/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 02:17:51.315155: W tensorflow/c/c_api.cc:304] Operation '{name:'conv2d_1_2/kernel/v/Assign' id:45263 op device:{requested: '', assigned: ''} def:{{{node conv2d_1_2/kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](conv2d_1_2/kernel/v, conv2d_1_2/kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31674 samples, validate on 3539 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 02:17:56.918643: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 02:18:16.606649: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_6/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3939"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 02:18:52.134708: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.38548, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 45s 1ms/sample - loss: 1.3939 - val_loss: 1.3855\n",
      "Epoch 2/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3885\n",
      "Epoch 2: val_loss improved from 1.38548 to 1.38504, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 973us/sample - loss: 1.3885 - val_loss: 1.3850\n",
      "Epoch 3/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3858\n",
      "Epoch 3: val_loss improved from 1.38504 to 1.38097, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3858 - val_loss: 1.3810\n",
      "Epoch 4/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3850\n",
      "Epoch 4: val_loss did not improve from 1.38097\n",
      "31674/31674 [==============================] - 30s 956us/sample - loss: 1.3850 - val_loss: 1.3864\n",
      "Epoch 5/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3854\n",
      "Epoch 5: val_loss did not improve from 1.38097\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3854 - val_loss: 1.3888\n",
      "Epoch 6/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3838\n",
      "Epoch 6: val_loss improved from 1.38097 to 1.37860, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3838 - val_loss: 1.3786\n",
      "Epoch 7/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3787\n",
      "Epoch 7: val_loss did not improve from 1.37860\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3787 - val_loss: 1.3853\n",
      "Epoch 8/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3801\n",
      "Epoch 8: val_loss did not improve from 1.37860\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3801 - val_loss: 1.3831\n",
      "Epoch 9/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3789\n",
      "Epoch 9: val_loss did not improve from 1.37860\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3789 - val_loss: 1.3799\n",
      "Epoch 10/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3779\n",
      "Epoch 10: val_loss did not improve from 1.37860\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3779 - val_loss: 1.3809\n",
      "Epoch 11/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3753\n",
      "Epoch 11: val_loss improved from 1.37860 to 1.37781, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 30s 947us/sample - loss: 1.3753 - val_loss: 1.3778\n",
      "Epoch 12/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3787\n",
      "Epoch 12: val_loss improved from 1.37781 to 1.37585, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 988us/sample - loss: 1.3787 - val_loss: 1.3758\n",
      "Epoch 13/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3750\n",
      "Epoch 13: val_loss improved from 1.37585 to 1.37556, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 990us/sample - loss: 1.3750 - val_loss: 1.3756\n",
      "Epoch 14/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3709\n",
      "Epoch 14: val_loss improved from 1.37556 to 1.37539, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 31s 990us/sample - loss: 1.3709 - val_loss: 1.3754\n",
      "Epoch 15/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3702\n",
      "Epoch 15: val_loss did not improve from 1.37539\n",
      "31674/31674 [==============================] - 31s 965us/sample - loss: 1.3702 - val_loss: 1.3781\n",
      "Epoch 16/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3695\n",
      "Epoch 16: val_loss did not improve from 1.37539\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3695 - val_loss: 1.3767\n",
      "Epoch 17/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3706\n",
      "Epoch 17: val_loss improved from 1.37539 to 1.36900, saving model to ./checkpoints/unknown_person_baseline_2_p4_20.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3706 - val_loss: 1.3690\n",
      "Epoch 18/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3671\n",
      "Epoch 18: val_loss did not improve from 1.36900\n",
      "31674/31674 [==============================] - 30s 934us/sample - loss: 1.3671 - val_loss: 1.3749\n",
      "Epoch 19/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3689\n",
      "Epoch 19: val_loss did not improve from 1.36900\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3689 - val_loss: 1.3816\n",
      "Epoch 20/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3631\n",
      "Epoch 20: val_loss did not improve from 1.36900\n",
      "31674/31674 [==============================] - 31s 981us/sample - loss: 1.3631 - val_loss: 1.3723\n",
      "Train on 31674 samples, validate on 3539 samples\n",
      "Epoch 1/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3653\n",
      "Epoch 1: val_loss improved from inf to 1.37503, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3653 - val_loss: 1.3750\n",
      "Epoch 2/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3645\n",
      "Epoch 2: val_loss did not improve from 1.37503\n",
      "31674/31674 [==============================] - 31s 993us/sample - loss: 1.3645 - val_loss: 1.3758\n",
      "Epoch 3/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3624\n",
      "Epoch 3: val_loss improved from 1.37503 to 1.37316, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 999us/sample - loss: 1.3624 - val_loss: 1.3732\n",
      "Epoch 4/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3608\n",
      "Epoch 4: val_loss improved from 1.37316 to 1.37158, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3608 - val_loss: 1.3716\n",
      "Epoch 5/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3595\n",
      "Epoch 5: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3595 - val_loss: 1.3727\n",
      "Epoch 6/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3627\n",
      "Epoch 6: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 31s 976us/sample - loss: 1.3627 - val_loss: 1.3800\n",
      "Epoch 7/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3574\n",
      "Epoch 7: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 31s 976us/sample - loss: 1.3574 - val_loss: 1.3779\n",
      "Epoch 8/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3637\n",
      "Epoch 8: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3637 - val_loss: 1.3832\n",
      "Epoch 9/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3667\n",
      "Epoch 9: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3667 - val_loss: 1.3759\n",
      "Epoch 10/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3662\n",
      "Epoch 10: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3662 - val_loss: 1.3772\n",
      "Epoch 11/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3751\n",
      "Epoch 11: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 30s 947us/sample - loss: 1.3751 - val_loss: 1.3840\n",
      "Epoch 12/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3746\n",
      "Epoch 12: val_loss did not improve from 1.37158\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3746 - val_loss: 1.3815\n",
      "Epoch 13/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3938\n",
      "Epoch 13: val_loss improved from 1.37158 to 1.37146, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3938 - val_loss: 1.3715\n",
      "Epoch 14/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3725\n",
      "Epoch 14: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 966us/sample - loss: 1.3725 - val_loss: 1.3731\n",
      "Epoch 15/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3825\n",
      "Epoch 15: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3825 - val_loss: 1.3782\n",
      "Epoch 16/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3832\n",
      "Epoch 16: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3832 - val_loss: 1.3763\n",
      "Epoch 17/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3749\n",
      "Epoch 17: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 987us/sample - loss: 1.3749 - val_loss: 1.3760\n",
      "Epoch 18/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3894\n",
      "Epoch 18: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 30s 954us/sample - loss: 1.3894 - val_loss: 1.3745\n",
      "Epoch 19/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3952\n",
      "Epoch 19: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 977us/sample - loss: 1.3952 - val_loss: 1.3811\n",
      "Epoch 20/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4050\n",
      "Epoch 20: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 970us/sample - loss: 1.4050 - val_loss: 1.3786\n",
      "Epoch 21/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4149\n",
      "Epoch 21: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 977us/sample - loss: 1.4149 - val_loss: 1.3785\n",
      "Epoch 22/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4137\n",
      "Epoch 22: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 994us/sample - loss: 1.4137 - val_loss: 1.3805\n",
      "Epoch 23/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4149\n",
      "Epoch 23: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.4149 - val_loss: 1.3762\n",
      "Epoch 24/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4029\n",
      "Epoch 24: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 974us/sample - loss: 1.4029 - val_loss: 1.3797\n",
      "Epoch 25/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3963\n",
      "Epoch 25: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3963 - val_loss: 1.3760\n",
      "Epoch 26/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3934\n",
      "Epoch 26: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3934 - val_loss: 1.3755\n",
      "Epoch 27/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3902\n",
      "Epoch 27: val_loss did not improve from 1.37146\n",
      "31674/31674 [==============================] - 31s 989us/sample - loss: 1.3902 - val_loss: 1.3776\n",
      "Epoch 28/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3874\n",
      "Epoch 28: val_loss improved from 1.37146 to 1.37092, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3874 - val_loss: 1.3709\n",
      "Epoch 29/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3846\n",
      "Epoch 29: val_loss did not improve from 1.37092\n",
      "31674/31674 [==============================] - 31s 968us/sample - loss: 1.3846 - val_loss: 1.3734\n",
      "Epoch 30/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3813\n",
      "Epoch 30: val_loss did not improve from 1.37092\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3813 - val_loss: 1.3769\n",
      "Epoch 31/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3830\n",
      "Epoch 31: val_loss did not improve from 1.37092\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3830 - val_loss: 1.3758\n",
      "Epoch 32/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3806\n",
      "Epoch 32: val_loss did not improve from 1.37092\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3806 - val_loss: 1.3723\n",
      "Epoch 33/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3768\n",
      "Epoch 33: val_loss improved from 1.37092 to 1.36938, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3768 - val_loss: 1.3694\n",
      "Epoch 34/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3761\n",
      "Epoch 34: val_loss did not improve from 1.36938\n",
      "31674/31674 [==============================] - 31s 978us/sample - loss: 1.3761 - val_loss: 1.3732\n",
      "Epoch 35/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3773\n",
      "Epoch 35: val_loss did not improve from 1.36938\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3773 - val_loss: 1.3712\n",
      "Epoch 36/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3724\n",
      "Epoch 36: val_loss did not improve from 1.36938\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3724 - val_loss: 1.3714\n",
      "Epoch 37/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3725\n",
      "Epoch 37: val_loss did not improve from 1.36938\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3725 - val_loss: 1.3719\n",
      "Epoch 38/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3697\n",
      "Epoch 38: val_loss did not improve from 1.36938\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3697 - val_loss: 1.3710\n",
      "Epoch 39/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3677\n",
      "Epoch 39: val_loss improved from 1.36938 to 1.36810, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3677 - val_loss: 1.3681\n",
      "Epoch 40/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3666\n",
      "Epoch 40: val_loss improved from 1.36810 to 1.36676, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 31s 992us/sample - loss: 1.3666 - val_loss: 1.3668\n",
      "Epoch 41/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3672\n",
      "Epoch 41: val_loss improved from 1.36676 to 1.36398, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 999us/sample - loss: 1.3672 - val_loss: 1.3640\n",
      "Epoch 42/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3670\n",
      "Epoch 42: val_loss did not improve from 1.36398\n",
      "31674/31674 [==============================] - 31s 990us/sample - loss: 1.3670 - val_loss: 1.3731\n",
      "Epoch 43/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3645\n",
      "Epoch 43: val_loss did not improve from 1.36398\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3645 - val_loss: 1.3662\n",
      "Epoch 44/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3613\n",
      "Epoch 44: val_loss did not improve from 1.36398\n",
      "31674/31674 [==============================] - 31s 981us/sample - loss: 1.3613 - val_loss: 1.3693\n",
      "Epoch 45/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3609\n",
      "Epoch 45: val_loss did not improve from 1.36398\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3609 - val_loss: 1.3647\n",
      "Epoch 46/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3579\n",
      "Epoch 46: val_loss did not improve from 1.36398\n",
      "31674/31674 [==============================] - 31s 965us/sample - loss: 1.3579 - val_loss: 1.3682\n",
      "Epoch 47/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3579\n",
      "Epoch 47: val_loss improved from 1.36398 to 1.36330, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3579 - val_loss: 1.3633\n",
      "Epoch 48/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3572\n",
      "Epoch 48: val_loss did not improve from 1.36330\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3572 - val_loss: 1.3703\n",
      "Epoch 49/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3576\n",
      "Epoch 49: val_loss did not improve from 1.36330\n",
      "31674/31674 [==============================] - 31s 977us/sample - loss: 1.3576 - val_loss: 1.3744\n",
      "Epoch 50/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3583\n",
      "Epoch 50: val_loss improved from 1.36330 to 1.36173, saving model to ./checkpoints/unknown_person_baseline_p4_21.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3583 - val_loss: 1.3617\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 02:55:32.080829: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_20_3/lstm_cell_131/kernel/Assign' id:60598 op device:{requested: '', assigned: ''} def:{{{node lstm_20_3/lstm_cell_131/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_20_3/lstm_cell_131/kernel, lstm_20_3/lstm_cell_131/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 02:55:35.961464: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_33_3/lstm_cell_144/recurrent_kernel/v/Assign' id:65153 op device:{requested: '', assigned: ''} def:{{{node lstm_33_3/lstm_cell_144/recurrent_kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_33_3/lstm_cell_144/recurrent_kernel/v, lstm_33_3/lstm_cell_144/recurrent_kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 02:55:39.672692: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_3/cond/Merge' id:63349 op device:{requested: '', assigned: ''} def:{{{node dropout_4_3/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_3/cond/Identity, dropout_4_3/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1788)\n",
      "(1514, 1788)\n",
      "(1752, 1788)\n",
      "(1872, 1788)\n",
      "(1735, 1788)\n",
      "(1285, 1788)\n",
      "(1838, 1788)\n",
      "(1594, 1788)\n",
      "(1788, 1788)\n",
      "(1538, 1788)\n",
      "(1920, 1788)\n",
      "(1679, 1788)\n",
      "(1800, 1788)\n",
      "(1860, 1788)\n",
      "(1692, 1788)\n",
      "(1824, 1788)\n",
      "(958, 1788)\n",
      "(1680, 1788)\n",
      "(1860, 1788)\n",
      "{1: 5.0217754781146695, 2: 4.506766173230047, 5: 5.595260327304786, 6: 6.289007202790628, 8: 8.954729571844974, 9: 7.715610794224734, 10: 7.307192457038803, 11: 7.32258810780819, 12: 9.009658181642147, 13: 7.078010216288528, 17: 9.800165151228812, 19: 10.0, 21: 8.030032574078334, 22: 1.0, 25: 8.326829999432118, 26: 5.69562740244301, 27: 5.830412310190129, 28: 6.299040558870269, 29: 2.7770644601817036}\n",
      "Train on 31674 samples, validate on 3539 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 03:01:36.178226: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_7/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31674/31674 [==============================] - ETA: 0s - loss: 9.6606\n",
      "Epoch 1: val_loss improved from inf to 1.37152, saving model to ./checkpoints/unknown_person_p4_21.h5\n",
      "31674/31674 [==============================] - 46s 1ms/sample - loss: 9.6606 - val_loss: 1.3715\n",
      "Epoch 2/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.5570\n",
      "Epoch 2: val_loss did not improve from 1.37152\n",
      "31674/31674 [==============================] - 31s 975us/sample - loss: 9.5570 - val_loss: 1.3720\n",
      "Epoch 3/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.4799\n",
      "Epoch 3: val_loss improved from 1.37152 to 1.36787, saving model to ./checkpoints/unknown_person_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.4799 - val_loss: 1.3679\n",
      "Epoch 4/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.4386\n",
      "Epoch 4: val_loss did not improve from 1.36787\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.4386 - val_loss: 1.3688\n",
      "Epoch 5/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.4117\n",
      "Epoch 5: val_loss improved from 1.36787 to 1.35985, saving model to ./checkpoints/unknown_person_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 998us/sample - loss: 9.4117 - val_loss: 1.3598\n",
      "Epoch 6/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3906\n",
      "Epoch 6: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 31s 983us/sample - loss: 9.3906 - val_loss: 1.3703\n",
      "Epoch 7/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3844\n",
      "Epoch 7: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 31s 988us/sample - loss: 9.3844 - val_loss: 1.3686\n",
      "Epoch 8/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3390\n",
      "Epoch 8: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 30s 954us/sample - loss: 9.3390 - val_loss: 1.3683\n",
      "Epoch 9/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3469\n",
      "Epoch 9: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.3469 - val_loss: 1.3669\n",
      "Epoch 10/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3189\n",
      "Epoch 10: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.3189 - val_loss: 1.3810\n",
      "Epoch 11/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3116\n",
      "Epoch 11: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 31s 986us/sample - loss: 9.3116 - val_loss: 1.3727\n",
      "Epoch 12/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3036\n",
      "Epoch 12: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 30s 943us/sample - loss: 9.3036 - val_loss: 1.3729\n",
      "Epoch 13/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3022\n",
      "Epoch 13: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.3022 - val_loss: 1.3802\n",
      "Epoch 14/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2497\n",
      "Epoch 14: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.2497 - val_loss: 1.3703\n",
      "Epoch 15/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2716\n",
      "Epoch 15: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.2716 - val_loss: 1.3664\n",
      "Epoch 16/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2458\n",
      "Epoch 16: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 31s 987us/sample - loss: 9.2458 - val_loss: 1.3647\n",
      "Epoch 17/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2403\n",
      "Epoch 17: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 9.2403 - val_loss: 1.3612\n",
      "Epoch 18/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2276\n",
      "Epoch 18: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 31s 985us/sample - loss: 9.2276 - val_loss: 1.3627\n",
      "Epoch 19/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2283\n",
      "Epoch 19: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 30s 961us/sample - loss: 9.2283 - val_loss: 1.3689\n",
      "Epoch 20/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2276\n",
      "Epoch 20: val_loss did not improve from 1.35985\n",
      "31674/31674 [==============================] - 30s 952us/sample - loss: 9.2276 - val_loss: 1.3758\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 03:12:22.077600: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_3_4/lstm_cell_151/recurrent_kernel/Assign' id:77296 op device:{requested: '', assigned: ''} def:{{{node lstm_3_4/lstm_cell_151/recurrent_kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_3_4/lstm_cell_151/recurrent_kernel, lstm_3_4/lstm_cell_151/recurrent_kernel/Initializer/mul_1)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 03:12:27.865557: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_21_4/lstm_cell_169/recurrent_kernel/v/Assign' id:84371 op device:{requested: '', assigned: ''} def:{{{node lstm_21_4/lstm_cell_169/recurrent_kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_21_4/lstm_cell_169/recurrent_kernel/v, lstm_21_4/lstm_cell_169/recurrent_kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31674 samples, validate on 3539 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 03:12:36.935565: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 03:13:05.959263: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_8/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3565"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 03:13:39.233937: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.36437, saving model to ./checkpoints/unknown_person_baseline_2_p4_21.h5\n",
      "31674/31674 [==============================] - 48s 2ms/sample - loss: 1.3565 - val_loss: 1.3644\n",
      "Epoch 2/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3551\n",
      "Epoch 2: val_loss did not improve from 1.36437\n",
      "31674/31674 [==============================] - 31s 991us/sample - loss: 1.3551 - val_loss: 1.3682\n",
      "Epoch 3/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3526\n",
      "Epoch 3: val_loss improved from 1.36437 to 1.36223, saving model to ./checkpoints/unknown_person_baseline_2_p4_21.h5\n",
      "31674/31674 [==============================] - 32s 996us/sample - loss: 1.3526 - val_loss: 1.3622\n",
      "Epoch 4/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3505\n",
      "Epoch 4: val_loss improved from 1.36223 to 1.36124, saving model to ./checkpoints/unknown_person_baseline_2_p4_21.h5\n",
      "31674/31674 [==============================] - 31s 972us/sample - loss: 1.3505 - val_loss: 1.3612\n",
      "Epoch 5/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3505\n",
      "Epoch 5: val_loss improved from 1.36124 to 1.36023, saving model to ./checkpoints/unknown_person_baseline_2_p4_21.h5\n",
      "31674/31674 [==============================] - 30s 957us/sample - loss: 1.3505 - val_loss: 1.3602\n",
      "Epoch 6/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3468\n",
      "Epoch 6: val_loss improved from 1.36023 to 1.35790, saving model to ./checkpoints/unknown_person_baseline_2_p4_21.h5\n",
      "31674/31674 [==============================] - 31s 980us/sample - loss: 1.3468 - val_loss: 1.3579\n",
      "Epoch 7/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3448\n",
      "Epoch 7: val_loss did not improve from 1.35790\n",
      "31674/31674 [==============================] - 31s 979us/sample - loss: 1.3448 - val_loss: 1.3617\n",
      "Epoch 8/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3433\n",
      "Epoch 8: val_loss did not improve from 1.35790\n",
      "31674/31674 [==============================] - 29s 923us/sample - loss: 1.3433 - val_loss: 1.3603\n",
      "Epoch 9/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3420\n",
      "Epoch 9: val_loss did not improve from 1.35790\n",
      "31674/31674 [==============================] - 31s 965us/sample - loss: 1.3420 - val_loss: 1.3660\n",
      "Epoch 10/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3400\n",
      "Epoch 10: val_loss improved from 1.35790 to 1.35658, saving model to ./checkpoints/unknown_person_baseline_2_p4_21.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3400 - val_loss: 1.3566\n",
      "Epoch 11/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3397\n",
      "Epoch 11: val_loss did not improve from 1.35658\n",
      "31674/31674 [==============================] - 30s 955us/sample - loss: 1.3397 - val_loss: 1.3630\n",
      "Epoch 12/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3381\n",
      "Epoch 12: val_loss did not improve from 1.35658\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3381 - val_loss: 1.3611\n",
      "Epoch 13/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3393\n",
      "Epoch 13: val_loss did not improve from 1.35658\n",
      "31674/31674 [==============================] - 31s 978us/sample - loss: 1.3393 - val_loss: 1.3599\n",
      "Epoch 14/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3399\n",
      "Epoch 14: val_loss did not improve from 1.35658\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3399 - val_loss: 1.3645\n",
      "Epoch 15/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3368\n",
      "Epoch 15: val_loss did not improve from 1.35658\n",
      "31674/31674 [==============================] - 32s 998us/sample - loss: 1.3368 - val_loss: 1.3614\n",
      "Epoch 16/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3343\n",
      "Epoch 16: val_loss improved from 1.35658 to 1.35541, saving model to ./checkpoints/unknown_person_baseline_2_p4_21.h5\n",
      "31674/31674 [==============================] - 31s 978us/sample - loss: 1.3343 - val_loss: 1.3554\n",
      "Epoch 17/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3382\n",
      "Epoch 17: val_loss did not improve from 1.35541\n",
      "31674/31674 [==============================] - 31s 972us/sample - loss: 1.3382 - val_loss: 1.3565\n",
      "Epoch 18/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3343\n",
      "Epoch 18: val_loss did not improve from 1.35541\n",
      "31674/31674 [==============================] - 31s 992us/sample - loss: 1.3343 - val_loss: 1.3582\n",
      "Epoch 19/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3344\n",
      "Epoch 19: val_loss did not improve from 1.35541\n",
      "31674/31674 [==============================] - 31s 988us/sample - loss: 1.3344 - val_loss: 1.3562\n",
      "Epoch 20/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3319\n",
      "Epoch 20: val_loss did not improve from 1.35541\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3319 - val_loss: 1.3555\n",
      "Train on 31674 samples, validate on 3539 samples\n",
      "Epoch 1/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3316\n",
      "Epoch 1: val_loss improved from inf to 1.36379, saving model to ./checkpoints/unknown_person_baseline_p4_22.h5\n",
      "31674/31674 [==============================] - 31s 973us/sample - loss: 1.3316 - val_loss: 1.3638\n",
      "Epoch 2/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3295\n",
      "Epoch 2: val_loss improved from 1.36379 to 1.35545, saving model to ./checkpoints/unknown_person_baseline_p4_22.h5\n",
      "31674/31674 [==============================] - 31s 970us/sample - loss: 1.3295 - val_loss: 1.3554\n",
      "Epoch 3/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3282\n",
      "Epoch 3: val_loss improved from 1.35545 to 1.35296, saving model to ./checkpoints/unknown_person_baseline_p4_22.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3282 - val_loss: 1.3530\n",
      "Epoch 4/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3229\n",
      "Epoch 4: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3229 - val_loss: 1.3570\n",
      "Epoch 5/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3269\n",
      "Epoch 5: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 30s 944us/sample - loss: 1.3269 - val_loss: 1.3575\n",
      "Epoch 6/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3209\n",
      "Epoch 6: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3209 - val_loss: 1.3534\n",
      "Epoch 7/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3218\n",
      "Epoch 7: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 999us/sample - loss: 1.3218 - val_loss: 1.3593\n",
      "Epoch 8/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3280\n",
      "Epoch 8: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3280 - val_loss: 1.3535\n",
      "Epoch 9/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3322\n",
      "Epoch 9: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 30s 935us/sample - loss: 1.3322 - val_loss: 1.3553\n",
      "Epoch 10/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3417\n",
      "Epoch 10: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3417 - val_loss: 1.3606\n",
      "Epoch 11/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3357\n",
      "Epoch 11: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 996us/sample - loss: 1.3357 - val_loss: 1.3633\n",
      "Epoch 12/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3460\n",
      "Epoch 12: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 987us/sample - loss: 1.3460 - val_loss: 1.3617\n",
      "Epoch 13/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3391\n",
      "Epoch 13: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 977us/sample - loss: 1.3391 - val_loss: 1.3590\n",
      "Epoch 14/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3438\n",
      "Epoch 14: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 965us/sample - loss: 1.3438 - val_loss: 1.3587\n",
      "Epoch 15/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3488\n",
      "Epoch 15: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 997us/sample - loss: 1.3488 - val_loss: 1.3614\n",
      "Epoch 16/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3628\n",
      "Epoch 16: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 988us/sample - loss: 1.3628 - val_loss: 1.3665\n",
      "Epoch 17/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3574\n",
      "Epoch 17: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 994us/sample - loss: 1.3574 - val_loss: 1.3666\n",
      "Epoch 18/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.4066\n",
      "Epoch 18: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 994us/sample - loss: 1.4066 - val_loss: 1.3806\n",
      "Epoch 19/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3804\n",
      "Epoch 19: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3804 - val_loss: 1.3678\n",
      "Epoch 20/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3722\n",
      "Epoch 20: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3722 - val_loss: 1.3701\n",
      "Epoch 21/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3802\n",
      "Epoch 21: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 30s 959us/sample - loss: 1.3802 - val_loss: 1.3728\n",
      "Epoch 22/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3767\n",
      "Epoch 22: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 30s 950us/sample - loss: 1.3767 - val_loss: 1.3699\n",
      "Epoch 23/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3736\n",
      "Epoch 23: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 981us/sample - loss: 1.3736 - val_loss: 1.3721\n",
      "Epoch 24/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3754\n",
      "Epoch 24: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 969us/sample - loss: 1.3754 - val_loss: 1.3700\n",
      "Epoch 25/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3746\n",
      "Epoch 25: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 30s 936us/sample - loss: 1.3746 - val_loss: 1.3697\n",
      "Epoch 26/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3728\n",
      "Epoch 26: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3728 - val_loss: 1.3705\n",
      "Epoch 27/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3780\n",
      "Epoch 27: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3780 - val_loss: 1.3724\n",
      "Epoch 28/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3784\n",
      "Epoch 28: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 32s 996us/sample - loss: 1.3784 - val_loss: 1.3678\n",
      "Epoch 29/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3751\n",
      "Epoch 29: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 31s 993us/sample - loss: 1.3751 - val_loss: 1.3732\n",
      "Epoch 30/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3754\n",
      "Epoch 30: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3754 - val_loss: 1.3667\n",
      "Epoch 31/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3721\n",
      "Epoch 31: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3721 - val_loss: 1.3689\n",
      "Epoch 32/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3717\n",
      "Epoch 32: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3717 - val_loss: 1.3669\n",
      "Epoch 33/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3688\n",
      "Epoch 33: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3688 - val_loss: 1.3659\n",
      "Epoch 34/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3671\n",
      "Epoch 34: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3671 - val_loss: 1.3625\n",
      "Epoch 35/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3664\n",
      "Epoch 35: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3664 - val_loss: 1.3656\n",
      "Epoch 36/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3679\n",
      "Epoch 36: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3679 - val_loss: 1.3700\n",
      "Epoch 37/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3647\n",
      "Epoch 37: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3647 - val_loss: 1.3635\n",
      "Epoch 38/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3650\n",
      "Epoch 38: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3650 - val_loss: 1.3654\n",
      "Epoch 39/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3615\n",
      "Epoch 39: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3615 - val_loss: 1.3728\n",
      "Epoch 40/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3617\n",
      "Epoch 40: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3617 - val_loss: 1.3633\n",
      "Epoch 41/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3599\n",
      "Epoch 41: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3599 - val_loss: 1.3645\n",
      "Epoch 42/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3599\n",
      "Epoch 42: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3599 - val_loss: 1.3714\n",
      "Epoch 43/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3612\n",
      "Epoch 43: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3612 - val_loss: 1.3680\n",
      "Epoch 44/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3601\n",
      "Epoch 44: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3601 - val_loss: 1.3645\n",
      "Epoch 45/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3556\n",
      "Epoch 45: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3556 - val_loss: 1.3695\n",
      "Epoch 46/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3545\n",
      "Epoch 46: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3545 - val_loss: 1.3631\n",
      "Epoch 47/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3548\n",
      "Epoch 47: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3548 - val_loss: 1.3630\n",
      "Epoch 48/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3552\n",
      "Epoch 48: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3552 - val_loss: 1.3618\n",
      "Epoch 49/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3520\n",
      "Epoch 49: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3520 - val_loss: 1.3617\n",
      "Epoch 50/50\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3517\n",
      "Epoch 50: val_loss did not improve from 1.35296\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3517 - val_loss: 1.3577\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 03:50:40.819023: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_6_5/lstm_cell_191/bias/Assign' id:97145 op device:{requested: '', assigned: ''} def:{{{node lstm_6_5/lstm_cell_191/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_6_5/lstm_cell_191/bias, lstm_6_5/lstm_cell_191/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 03:50:48.744482: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_35_5/lstm_cell_220/kernel/v/Assign' id:103936 op device:{requested: '', assigned: ''} def:{{{node lstm_35_5/lstm_cell_220/kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_35_5/lstm_cell_220/kernel/v, lstm_35_5/lstm_cell_220/kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 03:50:56.542348: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_5/cond/Merge' id:102107 op device:{requested: '', assigned: ''} def:{{{node dropout_4_5/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_5/cond/Identity, dropout_4_5/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1788)\n",
      "(1514, 1788)\n",
      "(1752, 1788)\n",
      "(1872, 1788)\n",
      "(1735, 1788)\n",
      "(1285, 1788)\n",
      "(1838, 1788)\n",
      "(1594, 1788)\n",
      "(1788, 1788)\n",
      "(1538, 1788)\n",
      "(1920, 1788)\n",
      "(1679, 1788)\n",
      "(1800, 1788)\n",
      "(1860, 1788)\n",
      "(1692, 1788)\n",
      "(1824, 1788)\n",
      "(958, 1788)\n",
      "(1680, 1788)\n",
      "(1860, 1788)\n",
      "{1: 4.822142736379561, 2: 4.513638066406196, 5: 5.727068954869054, 6: 6.286221815751522, 8: 8.753671244703233, 9: 7.37767529197566, 10: 7.273281826031801, 11: 7.136035718702895, 12: 8.919006732432141, 13: 7.146083062777624, 17: 9.694760315657422, 19: 10.0, 21: 7.969365674986582, 22: 1.0, 25: 8.23023773510952, 26: 5.678657300189833, 27: 5.592485313481252, 28: 6.199060704709752, 29: 2.681889217750486}\n",
      "Train on 31674 samples, validate on 3539 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 03:57:43.114748: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_9/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3636\n",
      "Epoch 1: val_loss improved from inf to 1.38023, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 54s 2ms/sample - loss: 9.3636 - val_loss: 1.3802\n",
      "Epoch 2/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3002\n",
      "Epoch 2: val_loss improved from 1.38023 to 1.37606, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.3002 - val_loss: 1.3761\n",
      "Epoch 3/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.3461\n",
      "Epoch 3: val_loss did not improve from 1.37606\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.3461 - val_loss: 1.3816\n",
      "Epoch 4/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.2449\n",
      "Epoch 4: val_loss improved from 1.37606 to 1.36692, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.2449 - val_loss: 1.3669\n",
      "Epoch 5/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1878\n",
      "Epoch 5: val_loss improved from 1.36692 to 1.36300, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.1878 - val_loss: 1.3630\n",
      "Epoch 6/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1730\n",
      "Epoch 6: val_loss improved from 1.36300 to 1.35919, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.1730 - val_loss: 1.3592\n",
      "Epoch 7/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1628\n",
      "Epoch 7: val_loss improved from 1.35919 to 1.35824, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.1628 - val_loss: 1.3582\n",
      "Epoch 8/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1240\n",
      "Epoch 8: val_loss improved from 1.35824 to 1.35759, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.1240 - val_loss: 1.3576\n",
      "Epoch 9/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1343\n",
      "Epoch 9: val_loss improved from 1.35759 to 1.35428, saving model to ./checkpoints/unknown_person_p4_22.h5\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.1343 - val_loss: 1.3543\n",
      "Epoch 10/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1284\n",
      "Epoch 10: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.1284 - val_loss: 1.3565\n",
      "Epoch 11/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.1127\n",
      "Epoch 11: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.1127 - val_loss: 1.3610\n",
      "Epoch 12/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0860\n",
      "Epoch 12: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.0860 - val_loss: 1.3597\n",
      "Epoch 13/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0795\n",
      "Epoch 13: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.0795 - val_loss: 1.3596\n",
      "Epoch 14/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0739\n",
      "Epoch 14: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.0739 - val_loss: 1.3639\n",
      "Epoch 15/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0880\n",
      "Epoch 15: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.0880 - val_loss: 1.3696\n",
      "Epoch 16/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0570\n",
      "Epoch 16: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 9.0570 - val_loss: 1.3627\n",
      "Epoch 17/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0294\n",
      "Epoch 17: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.0294 - val_loss: 1.3641\n",
      "Epoch 18/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0528\n",
      "Epoch 18: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.0528 - val_loss: 1.3607\n",
      "Epoch 19/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0176\n",
      "Epoch 19: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.0176 - val_loss: 1.3632\n",
      "Epoch 20/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 9.0330\n",
      "Epoch 20: val_loss did not improve from 1.35428\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 9.0330 - val_loss: 1.3642\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:09:17.305010: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_29_6/lstm_cell_251/kernel/Assign' id:120196 op device:{requested: '', assigned: ''} def:{{{node lstm_29_6/lstm_cell_251/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_29_6/lstm_cell_251/kernel, lstm_29_6/lstm_cell_251/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 04:09:26.570518: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_21_6/lstm_cell_243/bias/v/Assign' id:123134 op device:{requested: '', assigned: ''} def:{{{node lstm_21_6/lstm_cell_243/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_21_6/lstm_cell_243/bias/v, lstm_21_6/lstm_cell_243/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31674 samples, validate on 3539 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:09:40.081387: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:10:25.926505: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_10/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3283"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:11:00.574470: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.35956, saving model to ./checkpoints/unknown_person_baseline_2_p4_22.h5\n",
      "31674/31674 [==============================] - 53s 2ms/sample - loss: 1.3283 - val_loss: 1.3596\n",
      "Epoch 2/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3237\n",
      "Epoch 2: val_loss improved from 1.35956 to 1.35179, saving model to ./checkpoints/unknown_person_baseline_2_p4_22.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3237 - val_loss: 1.3518\n",
      "Epoch 3/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3330\n",
      "Epoch 3: val_loss did not improve from 1.35179\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3330 - val_loss: 1.3573\n",
      "Epoch 4/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3271\n",
      "Epoch 4: val_loss did not improve from 1.35179\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3271 - val_loss: 1.3571\n",
      "Epoch 5/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3237\n",
      "Epoch 5: val_loss did not improve from 1.35179\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3237 - val_loss: 1.3555\n",
      "Epoch 6/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3255\n",
      "Epoch 6: val_loss improved from 1.35179 to 1.35132, saving model to ./checkpoints/unknown_person_baseline_2_p4_22.h5\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3255 - val_loss: 1.3513\n",
      "Epoch 7/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3216\n",
      "Epoch 7: val_loss did not improve from 1.35132\n",
      "31674/31674 [==============================] - 35s 1ms/sample - loss: 1.3216 - val_loss: 1.3518\n",
      "Epoch 8/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3239\n",
      "Epoch 8: val_loss improved from 1.35132 to 1.34806, saving model to ./checkpoints/unknown_person_baseline_2_p4_22.h5\n",
      "31674/31674 [==============================] - 31s 972us/sample - loss: 1.3239 - val_loss: 1.3481\n",
      "Epoch 9/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3215\n",
      "Epoch 9: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3215 - val_loss: 1.3507\n",
      "Epoch 10/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3226\n",
      "Epoch 10: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3226 - val_loss: 1.3514\n",
      "Epoch 11/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3226\n",
      "Epoch 11: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3226 - val_loss: 1.3509\n",
      "Epoch 12/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3200\n",
      "Epoch 12: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 31s 983us/sample - loss: 1.3200 - val_loss: 1.3534\n",
      "Epoch 13/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3176\n",
      "Epoch 13: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3176 - val_loss: 1.3503\n",
      "Epoch 14/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3176\n",
      "Epoch 14: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3176 - val_loss: 1.3586\n",
      "Epoch 15/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3192\n",
      "Epoch 15: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 32s 1ms/sample - loss: 1.3192 - val_loss: 1.3557\n",
      "Epoch 16/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3165\n",
      "Epoch 16: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3165 - val_loss: 1.3571\n",
      "Epoch 17/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3165\n",
      "Epoch 17: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3165 - val_loss: 1.3553\n",
      "Epoch 18/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3154\n",
      "Epoch 18: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 37s 1ms/sample - loss: 1.3154 - val_loss: 1.3491\n",
      "Epoch 19/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3169\n",
      "Epoch 19: val_loss did not improve from 1.34806\n",
      "31674/31674 [==============================] - 34s 1ms/sample - loss: 1.3169 - val_loss: 1.3550\n",
      "Epoch 20/20\n",
      "31674/31674 [==============================] - ETA: 0s - loss: 1.3152\n",
      "Epoch 20: val_loss improved from 1.34806 to 1.34770, saving model to ./checkpoints/unknown_person_baseline_2_p4_22.h5\n",
      "31674/31674 [==============================] - 33s 1ms/sample - loss: 1.3152 - val_loss: 1.3477\n"
     ]
    }
   ],
   "source": [
    "person_nums = [1,2,4,5,6,8,9,10,11,12,13,17,19,21,22,25,26,27,28,29]\n",
    "## Build the baseline model for emotion recognition with dropout layers\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, SimpleRNN, LSTM, Conv2D, Flatten, MaxPooling2D, GRU, AveragePooling2D, Dropout, Lambda\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "def individual_model(features_list):\n",
    "    input_layers = []\n",
    "    hidden_layers = []\n",
    "    combined_feature = np.empty((len(features_list[0]),0))\n",
    "    for i, feature in enumerate(features_list):\n",
    "        \n",
    "        if len(feature.shape) == 3:\n",
    "            input_i = Input(shape=(feature.shape[1], feature.shape[2]))\n",
    "            input_layers.append(input_i)\n",
    "\n",
    "            hidden_i = input_i[:,:,:,None]\n",
    "            hidden_i = Conv2D(32, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(16, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(8, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(4, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Flatten()(hidden_i)\n",
    "\n",
    "            hidden_layers.append(hidden_i)\n",
    "        elif feature.shape[1] <20:\n",
    "            combined_feature = np.hstack((combined_feature, feature))\n",
    "            \n",
    "        else:  # For series features\n",
    "            input_i = Input(shape=(feature.shape[1],))\n",
    "            input_layers.append(input_i)\n",
    "            hidden_i = Lambda(lambda x: x[:, :, None])(input_i)  # Add a new dimension\n",
    "            hidden_i = LSTM(4)(hidden_i)\n",
    "            hidden_layers.append(hidden_i)\n",
    "    input_i = Input(shape=(combined_feature.shape[1],))\n",
    "    input_layers.append(input_i)\n",
    "    dense_num = np.max((1, int(combined_feature.shape[1]/2)))\n",
    "    hidden_i = Dense(dense_num, activation='relu')(input_i)\n",
    "    hidden_layers.append(hidden_i)\n",
    "    print(combined_feature.shape)\n",
    "    concat_layer = concatenate(hidden_layers)\n",
    "    h = Dropout(0.2)(concat_layer)\n",
    "    h = Dense(64, activation='relu')(h)\n",
    "    h = Dense(32, activation='relu')(h)\n",
    "    output_layer = Dense(2)(h)\n",
    "    model = Model(inputs=input_layers, outputs=output_layer)\n",
    "    model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "    return model\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.callbacks import Callback\n",
    "import numpy as np\n",
    "\n",
    "class PruningCallback(tf.keras.callbacks.Callback):\n",
    "    def __init__(self, initial_pruning_factor=0.1, final_pruning_factor=0.5, start_epoch=0, end_epoch=None, frequency=1):\n",
    "        super(PruningCallback, self).__init__()\n",
    "        self.initial_pruning_factor = initial_pruning_factor\n",
    "        self.final_pruning_factor = final_pruning_factor\n",
    "        self.start_epoch = start_epoch\n",
    "        self.end_epoch = end_epoch if end_epoch is not None else np.inf\n",
    "        self.frequency = frequency\n",
    "        self.pruned_weights = {}\n",
    "        self.layer_importance = {}\n",
    "\n",
    "    def get_pruning_factor(self, epoch):\n",
    "        if epoch < self.start_epoch:\n",
    "            return 0\n",
    "        if epoch > self.end_epoch:\n",
    "            return self.final_pruning_factor\n",
    "        return self.initial_pruning_factor + (self.final_pruning_factor - self.initial_pruning_factor) * (epoch - self.start_epoch) / (self.end_epoch - self.start_epoch)\n",
    "\n",
    "    def on_train_begin(self, logs=None):\n",
    "        total_weight_magnitude = 0\n",
    "        for layer in self.model.layers:\n",
    "            if hasattr(layer, 'get_weights'):\n",
    "                weights = layer.get_weights()\n",
    "                layer_norm = sum(np.linalg.norm(w) for w in weights)\n",
    "                total_weight_magnitude += layer_norm\n",
    "                self.layer_importance[layer.name] = layer_norm\n",
    "    \n",
    "        # Normalize the layer importance values so they sum up to 1\n",
    "        for layer_name in self.layer_importance:\n",
    "            self.layer_importance[layer_name] /= total_weight_magnitude\n",
    "    # def on_train_begin(self, logs=None):\n",
    "    #     total_weight_magnitude = sum([np.linalg.norm(layer.get_weights()) for layer in self.model.layers if hasattr(layer, 'get_weights')])\n",
    "    #     for layer in self.model.layers:\n",
    "    #         if hasattr(layer, 'get_weights'):\n",
    "    #             self.layer_importance[layer.name] = np.linalg.norm(layer.get_weights()) / total_weight_magnitude\n",
    "\n",
    "    def get_layer_pruning_factor(self, layer_name, global_pruning_factor):\n",
    "        if layer_name in self.layer_importance:\n",
    "            importance = self.layer_importance[layer_name]\n",
    "            adjusted_pruning_factor = global_pruning_factor * (1 - importance)\n",
    "            return min(adjusted_pruning_factor, 1)  # Ensure the pruning factor is not greater than 1\n",
    "        return global_pruning_factor\n",
    "    def prune_weights(self, layer, global_pruning_factor):\n",
    "        \n",
    "        weights = layer.get_weights()\n",
    "        layer_name = layer.name\n",
    "        pruning_factor = self.get_layer_pruning_factor(layer_name, global_pruning_factor)\n",
    "\n",
    "        if layer_name not in self.pruned_weights:\n",
    "            self.pruned_weights[layer_name] = [np.zeros_like(w, dtype=bool) for w in weights]\n",
    "        \n",
    "        for i in range(len(weights)):\n",
    "            weight = weights[i]\n",
    "            # print(weight.shape)\n",
    "            # print(weight.size)\n",
    "            if weight.ndim > 1:  # Only prune dense or convolutional layers\n",
    "                unpruned_weights = np.logical_not(self.pruned_weights[layer_name][i])\n",
    "                num_unpruned = np.sum(unpruned_weights)\n",
    "                num_pruning = min(num_unpruned, int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i]))\n",
    "                num_pruning = int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i])\n",
    "                if num_pruning > 0:\n",
    "                    unpruned_flat_indices = np.flatnonzero(unpruned_weights)\n",
    "                    abs_unpruned_weights = np.abs(weight[unpruned_weights])\n",
    "                    pruning_flat_indices = np.argpartition(abs_unpruned_weights, num_pruning)[:num_pruning]\n",
    "                    \n",
    "                    indices = np.unravel_index(pruning_flat_indices, weight.shape)\n",
    "                    self.pruned_weights[layer_name][i][indices] = True\n",
    "\n",
    "                weights[i] = weights[i]*(~self.pruned_weights[layer_name][i])\n",
    "                \n",
    "        layer.set_weights(weights)\n",
    "\n",
    "    def on_epoch_end(self, epoch, logs=None):\n",
    "        if (epoch - self.start_epoch) % self.frequency != 0:\n",
    "            return\n",
    "\n",
    "        pruning_factor = self.get_pruning_factor(epoch)\n",
    "        for layer in self.model.layers:\n",
    "            if isinstance(layer, (tf.keras.layers.Dense, tf.keras.layers.Conv2D)):\n",
    "                self.prune_weights(layer, pruning_factor)\n",
    "from feature_emotion import feature_extract, split_data, label_unique_tuples, split_data_unknown\n",
    "gts, sensor_nums, walk_nums, trace_nums, people_nums, spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features = feature_extract(person_nums)\n",
    "\n",
    "walk_nums_all = np.squeeze(walk_nums)\n",
    "trace_nums_all = np.squeeze(trace_nums)\n",
    "people_nums_all = np.squeeze(people_nums)\n",
    "\n",
    "## 0: train, 1: validation 2: test\n",
    "\n",
    "test_person_id = [4]\n",
    "flag_tr_val_te = split_data_unknown(test_person_id, walk_nums_all, trace_nums_all, people_nums_all, person_nums, rand_seed = 42)\n",
    "## Data Normalization before training ans testing\n",
    "import tensorflow as tf\n",
    "tf.compat.v1.disable_v2_behavior()\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, LSTM\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "scalers = []\n",
    "X_train_normalized = []\n",
    "X_val_normalized = []\n",
    "X_test_normalized = []\n",
    "train_idx = np.where(flag_tr_val_te ==0)[0]\n",
    "np.random.shuffle(train_idx)\n",
    "val_idx = np.where(flag_tr_val_te ==1)[0]\n",
    "test_idx = np.where(flag_tr_val_te ==2)[0]\n",
    "\n",
    "for i, feature in enumerate([spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features]):\n",
    "    scaler = StandardScaler()\n",
    "    if len(feature.shape)==2:\n",
    "        X_train_i = feature[train_idx,:]\n",
    "        X_val_i = feature[val_idx,:]\n",
    "        X_test_i = feature[test_idx,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i)\n",
    "        scalers.append(scaler)\n",
    "    else:\n",
    "        X_train_i = feature[train_idx,:,:]\n",
    "        X_val_i = feature[val_idx,:,:]\n",
    "        X_test_i = feature[test_idx,:,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i.reshape(X_train_i.shape[0], -1)).reshape(X_train_i.shape)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i.reshape(X_val_i.shape[0], -1)).reshape(X_val_i.shape)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i.reshape(X_test_i.shape[0], -1)).reshape(X_test_i.shape)\n",
    "        scalers.append(scaler)\n",
    "    X_train_normalized.append(X_train_normalized_i)\n",
    "    X_val_normalized.append(X_val_normalized_i)\n",
    "    X_test_normalized.append(X_test_normalized_i)\n",
    "y_train = gts[train_idx,:]\n",
    "y_val = gts[val_idx,:]\n",
    "y_test = gts[test_idx,:]\n",
    "X_train_normalized_new = []\n",
    "combined_feature = np.empty((len(X_train_normalized[0]),0))\n",
    "for feature in X_train_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_train_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_train_normalized_new.append(feature)\n",
    "X_train_normalized_new.append(combined_feature)\n",
    "\n",
    "X_val_normalized_new = []\n",
    "combined_feature = np.empty((len(X_val_normalized[0]),0))\n",
    "for feature in X_val_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_val_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_val_normalized_new.append(feature)\n",
    "X_val_normalized_new.append(combined_feature)\n",
    "\n",
    "X_test_normalized_new = []\n",
    "combined_feature = np.empty((len(X_test_normalized[0]),0))\n",
    "for feature in X_test_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_test_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_test_normalized_new.append(feature)\n",
    "X_test_normalized_new.append(combined_feature)\n",
    "\n",
    "model = individual_model(X_train_normalized)\n",
    "model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "num_epochs = 50\n",
    "\n",
    "\n",
    "# Gradually prune weights in dense and convolutional layers from 10% to 50% over the course of training, starting from epoch 0.\n",
    "\n",
    "\n",
    "rates = [0.4, 0.5, 0.6]\n",
    "idx = 20\n",
    "for r in rates:\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=0.01, final_pruning_factor=r, start_epoch=5, end_epoch=20, frequency=1)\n",
    "    model.fit(X_train_normalized_new, y_train, epochs=num_epochs, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import tensorflow as tf\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    from tensorflow.keras.models import Model\n",
    "    layers = model.layers\n",
    "    second_last_layer_output = layers[-4].output\n",
    "    feature_extractor_model = Model(inputs=model.input, outputs=second_last_layer_output)\n",
    "    train_features = feature_extractor_model.predict(X_train_normalized_new)\n",
    "    test_features = feature_extractor_model.predict(X_test_normalized_new)\n",
    "    \n",
    "    p_train = people_nums[train_idx,:]\n",
    "    p_val = people_nums[val_idx,:]\n",
    "    p_test = people_nums[test_idx,:]\n",
    "    ## Calculate the distance between test person and training person\n",
    "    def euclidean_distance(a, b):\n",
    "        return np.sqrt(np.sum((a - b) ** 2, axis=1))\n",
    "    \n",
    "    distance_dict = {}\n",
    "    for ii in range(len(person_nums)):\n",
    "        if person_nums[ii] == test_person_id[0]:\n",
    "            continue\n",
    "        else:\n",
    "            \n",
    "            ind = np.where(p_train ==person_nums[ii])[0]\n",
    "            tmp_train_features = train_features[ind, :]\n",
    "            distances = np.array([euclidean_distance(train_sample, test_features) for train_sample in tmp_train_features])\n",
    "            print(distances.shape)\n",
    "            average_distances = np.mean(distances, axis=1)\n",
    "    \n",
    "            # Step 4: Find the overall average distance\n",
    "            overall_average_distance = np.mean(average_distances)\n",
    "            distance_dict[person_nums[ii]] = overall_average_distance\n",
    "    \n",
    "    \n",
    "    def normalize_to_weights(distance_dict):\n",
    "        distances = np.array(list(distance_dict.values()))\n",
    "        # Handle the case where a distance is zero to avoid division by zero\n",
    "        distances = np.clip(distances, a_min=1e-10, a_max=None)\n",
    "        weights = 1 / distances\n",
    "        normalized_weights = weights\n",
    "        # normalized_weights = weights / sum(weights)\n",
    "        # print(sum(weights))\n",
    "        # print(sum(normalized_weights))\n",
    "        # Assign the normalized weights back to the dictionary\n",
    "        normalized_weight_dict = dict(zip(distance_dict.keys(), normalized_weights))\n",
    "        return normalized_weight_dict\n",
    "    def scale_dict_values(my_dict):\n",
    "        scaled_dict = my_dict.copy()\n",
    "        min_val = min(scaled_dict.values())\n",
    "        max_val = max(scaled_dict.values())\n",
    "        \n",
    "        for key in scaled_dict:\n",
    "            scaled_dict[key] = 1 + 9 * (scaled_dict[key] - min_val) / (max_val - min_val)\n",
    "        \n",
    "        return scaled_dict\n",
    "    weights_dict = normalize_to_weights(distance_dict)\n",
    "    weights_dict = scale_dict_values(weights_dict)\n",
    "    print(weights_dict)\n",
    "    \n",
    "    w_train = np.zeros_like(p_train)\n",
    "    for i in range(len(w_train)):\n",
    "        w_train[i] = weights_dict[int(p_train[i])]\n",
    "    \n",
    "    w_train = np.squeeze(w_train)\n",
    "    \n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,sample_weight= w_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    model_name = './checkpoints/unknown_person_baseline_2_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    idx += 1\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f71b59e4-6581-4ea8-994d-a02a6654ab6b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
