{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c77f8da1-2837-4bf7-b3f4-dfcaa7ab42f6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-08T09:21:50.842407Z",
     "iopub.status.busy": "2023-11-08T09:21:50.842236Z",
     "iopub.status.idle": "2023-11-08T09:21:50.995831Z",
     "shell.execute_reply": "2023-11-08T09:21:50.994631Z"
    }
   },
   "outputs": [],
   "source": [
    "import scipy.io\n",
    "import numpy as np\n",
    "import random\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3fe25376-b856-4296-ba02-5e3771ff9451",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-11-08T09:21:50.999210Z",
     "iopub.status.busy": "2023-11-08T09:21:50.998976Z",
     "iopub.status.idle": "2023-11-08T12:15:33.482786Z",
     "shell.execute_reply": "2023-11-08T12:15:33.481347Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:21:51.254004: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/usr/lib/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.2 when it was built against 1.14.1, this may cause problems\n",
      "  _warn((\"h5py is running against HDF5 {0} when it was built against {1}, \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "35105\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "non-resource variables are not supported in the long term\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:23:45.982697: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:45.996995: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:45.997268: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:46.005498: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:46.005815: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:46.006050: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:46.117565: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:46.117874: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:46.118148: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:46.118367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:41:00.0, compute capability: 8.6\n",
      "2023-11-08 04:23:46.118977: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:23:47.589022: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:47.589402: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:47.589783: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:47.590273: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:47.590475: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2023-11-08 04:23:47.590632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46608 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:41:00.0, compute capability: 8.6\n",
      "2023-11-08 04:23:47.590687: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\n",
      "2023-11-08 04:23:47.627017: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled\n",
      "2023-11-08 04:23:47.942490: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_14/lstm_cell_14/kernel/Assign' id:2326 op device:{requested: '', assigned: ''} def:{{{node lstm_14/lstm_cell_14/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_14/lstm_cell_14/kernel, lstm_14/lstm_cell_14/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 04:23:48.158647: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_1' id:3634 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_1}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 0 0 0...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 04:23:48.216226: W tensorflow/c/c_api.cc:304] Operation '{name:'strided_slice/stack_2' id:3635 op device:{requested: '', assigned: ''} def:{{{node strided_slice/stack_2}} = Const[_has_manual_control_dependencies=true, dtype=DT_INT32, value=Tensor<type: int32 shape: [4] values: 1 1 1...>]()}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "(31578, 95)\n",
      "Train on 31578 samples, validate on 3527 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:23:55.123645: W tensorflow/c/c_api.cc:304] Operation '{name:'training/Adam/dense/kernel/v/Assign' id:17594 op device:{requested: '', assigned: ''} def:{{{node training/Adam/dense/kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](training/Adam/dense/kernel/v, training/Adam/dense/kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:24:01.888327: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n",
      "2023-11-08 04:24:05.710639: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "2023-11-08 04:24:05.732371: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8902\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31578/31578 [==============================] - ETA: 0s - loss: 3.4749"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2335: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates = self.state_updates\n",
      "2023-11-08 04:24:39.277401: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_1/mul' id:6477 op device:{requested: '', assigned: ''} def:{{{node loss_1/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_1/mul/x, loss_1/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 2.09652, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 47s 1ms/sample - loss: 3.4749 - val_loss: 2.0965\n",
      "Epoch 2/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.8088\n",
      "Epoch 2: val_loss improved from 2.09652 to 1.57186, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.8088 - val_loss: 1.5719\n",
      "Epoch 3/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.5574\n",
      "Epoch 3: val_loss improved from 1.57186 to 1.47927, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.5574 - val_loss: 1.4793\n",
      "Epoch 4/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4944\n",
      "Epoch 4: val_loss improved from 1.47927 to 1.43614, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 998us/sample - loss: 1.4944 - val_loss: 1.4361\n",
      "Epoch 5/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4707\n",
      "Epoch 5: val_loss improved from 1.43614 to 1.41116, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.4707 - val_loss: 1.4112\n",
      "Epoch 6/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4503\n",
      "Epoch 6: val_loss improved from 1.41116 to 1.40436, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.4503 - val_loss: 1.4044\n",
      "Epoch 7/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4381\n",
      "Epoch 7: val_loss improved from 1.40436 to 1.39626, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.4381 - val_loss: 1.3963\n",
      "Epoch 8/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4346\n",
      "Epoch 8: val_loss improved from 1.39626 to 1.39546, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 31s 995us/sample - loss: 1.4346 - val_loss: 1.3955\n",
      "Epoch 9/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4377\n",
      "Epoch 9: val_loss improved from 1.39546 to 1.38565, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4377 - val_loss: 1.3856\n",
      "Epoch 10/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4415\n",
      "Epoch 10: val_loss improved from 1.38565 to 1.38074, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 31s 996us/sample - loss: 1.4415 - val_loss: 1.3807\n",
      "Epoch 11/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4318\n",
      "Epoch 11: val_loss did not improve from 1.38074\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4318 - val_loss: 1.3812\n",
      "Epoch 12/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4189\n",
      "Epoch 12: val_loss improved from 1.38074 to 1.37670, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.4189 - val_loss: 1.3767\n",
      "Epoch 13/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4130\n",
      "Epoch 13: val_loss improved from 1.37670 to 1.37278, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4130 - val_loss: 1.3728\n",
      "Epoch 14/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4279\n",
      "Epoch 14: val_loss did not improve from 1.37278\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.4279 - val_loss: 1.3754\n",
      "Epoch 15/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4479\n",
      "Epoch 15: val_loss did not improve from 1.37278\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.4479 - val_loss: 1.3844\n",
      "Epoch 16/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4076\n",
      "Epoch 16: val_loss did not improve from 1.37278\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4076 - val_loss: 1.3754\n",
      "Epoch 17/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4011\n",
      "Epoch 17: val_loss improved from 1.37278 to 1.37055, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4011 - val_loss: 1.3705\n",
      "Epoch 18/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4643\n",
      "Epoch 18: val_loss did not improve from 1.37055\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4643 - val_loss: 1.4066\n",
      "Epoch 19/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4958\n",
      "Epoch 19: val_loss did not improve from 1.37055\n",
      "31578/31578 [==============================] - 31s 991us/sample - loss: 1.4958 - val_loss: 1.3757\n",
      "Epoch 20/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4422\n",
      "Epoch 20: val_loss did not improve from 1.37055\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4422 - val_loss: 1.3716\n",
      "Epoch 21/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4274\n",
      "Epoch 21: val_loss did not improve from 1.37055\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.4274 - val_loss: 1.3755\n",
      "Epoch 22/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4409\n",
      "Epoch 22: val_loss improved from 1.37055 to 1.36623, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.4409 - val_loss: 1.3662\n",
      "Epoch 23/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4040\n",
      "Epoch 23: val_loss did not improve from 1.36623\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.4040 - val_loss: 1.3686\n",
      "Epoch 24/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3963\n",
      "Epoch 24: val_loss improved from 1.36623 to 1.36516, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3963 - val_loss: 1.3652\n",
      "Epoch 25/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3899\n",
      "Epoch 25: val_loss did not improve from 1.36516\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3899 - val_loss: 1.3657\n",
      "Epoch 26/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3915\n",
      "Epoch 26: val_loss improved from 1.36516 to 1.36413, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3915 - val_loss: 1.3641\n",
      "Epoch 27/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3861\n",
      "Epoch 27: val_loss improved from 1.36413 to 1.36042, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3861 - val_loss: 1.3604\n",
      "Epoch 28/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3864\n",
      "Epoch 28: val_loss improved from 1.36042 to 1.35863, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3864 - val_loss: 1.3586\n",
      "Epoch 29/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3836\n",
      "Epoch 29: val_loss did not improve from 1.35863\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3836 - val_loss: 1.3596\n",
      "Epoch 30/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3806\n",
      "Epoch 30: val_loss improved from 1.35863 to 1.35706, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3806 - val_loss: 1.3571\n",
      "Epoch 31/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3776\n",
      "Epoch 31: val_loss did not improve from 1.35706\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3776 - val_loss: 1.3577\n",
      "Epoch 32/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3749\n",
      "Epoch 32: val_loss did not improve from 1.35706\n",
      "31578/31578 [==============================] - 32s 998us/sample - loss: 1.3749 - val_loss: 1.3575\n",
      "Epoch 33/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3743\n",
      "Epoch 33: val_loss improved from 1.35706 to 1.34737, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3743 - val_loss: 1.3474\n",
      "Epoch 34/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3730\n",
      "Epoch 34: val_loss did not improve from 1.34737\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3730 - val_loss: 1.3505\n",
      "Epoch 35/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3695\n",
      "Epoch 35: val_loss did not improve from 1.34737\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3695 - val_loss: 1.3562\n",
      "Epoch 36/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3680\n",
      "Epoch 36: val_loss did not improve from 1.34737\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3680 - val_loss: 1.3476\n",
      "Epoch 37/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3648\n",
      "Epoch 37: val_loss improved from 1.34737 to 1.34274, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3648 - val_loss: 1.3427\n",
      "Epoch 38/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3662\n",
      "Epoch 38: val_loss improved from 1.34274 to 1.34156, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3662 - val_loss: 1.3416\n",
      "Epoch 39/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3652\n",
      "Epoch 39: val_loss improved from 1.34156 to 1.34129, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3652 - val_loss: 1.3413\n",
      "Epoch 40/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3613\n",
      "Epoch 40: val_loss did not improve from 1.34129\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3613 - val_loss: 1.3431\n",
      "Epoch 41/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3610\n",
      "Epoch 41: val_loss improved from 1.34129 to 1.34079, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3610 - val_loss: 1.3408\n",
      "Epoch 42/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3607\n",
      "Epoch 42: val_loss did not improve from 1.34079\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3607 - val_loss: 1.3431\n",
      "Epoch 43/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3547\n",
      "Epoch 43: val_loss improved from 1.34079 to 1.33430, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3547 - val_loss: 1.3343\n",
      "Epoch 44/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3555\n",
      "Epoch 44: val_loss did not improve from 1.33430\n",
      "31578/31578 [==============================] - 31s 971us/sample - loss: 1.3555 - val_loss: 1.3347\n",
      "Epoch 45/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3551\n",
      "Epoch 45: val_loss improved from 1.33430 to 1.33218, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3551 - val_loss: 1.3322\n",
      "Epoch 46/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3529\n",
      "Epoch 46: val_loss did not improve from 1.33218\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3529 - val_loss: 1.3409\n",
      "Epoch 47/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3528\n",
      "Epoch 47: val_loss improved from 1.33218 to 1.33066, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3528 - val_loss: 1.3307\n",
      "Epoch 48/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3509\n",
      "Epoch 48: val_loss did not improve from 1.33066\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3509 - val_loss: 1.3309\n",
      "Epoch 49/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3492\n",
      "Epoch 49: val_loss improved from 1.33066 to 1.32696, saving model to ./checkpoints/unknown_person_baseline_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3492 - val_loss: 1.3270\n",
      "Epoch 50/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3484\n",
      "Epoch 50: val_loss did not improve from 1.32696\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3484 - val_loss: 1.3346\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /usr/lib/python3.11/site-packages/tensorflow/python/ops/init_ops.py:94: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:51:30.080143: W tensorflow/c/c_api.cc:304] Operation '{name:'dense_3_1/kernel/Assign' id:24643 op device:{requested: '', assigned: ''} def:{{{node dense_3_1/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_3_1/kernel, dense_3_1/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 04:51:32.985421: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_29_1/lstm_cell_66/kernel/v/Assign' id:26330 op device:{requested: '', assigned: ''} def:{{{node lstm_29_1/lstm_cell_66/kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_29_1/lstm_cell_66/kernel/v, lstm_29_1/lstm_cell_66/kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "/usr/lib/python3.11/site-packages/keras/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.\n",
      "  updates=self.state_updates,\n",
      "2023-11-08 04:51:35.305161: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_1/cond/Merge' id:24591 op device:{requested: '', assigned: ''} def:{{{node dropout_4_1/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_1/cond/Identity, dropout_4_1/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1896)\n",
      "(1514, 1896)\n",
      "(1644, 1896)\n",
      "(1884, 1896)\n",
      "(1723, 1896)\n",
      "(1321, 1896)\n",
      "(1814, 1896)\n",
      "(1582, 1896)\n",
      "(1800, 1896)\n",
      "(1526, 1896)\n",
      "(1920, 1896)\n",
      "(1691, 1896)\n",
      "(1788, 1896)\n",
      "(1872, 1896)\n",
      "(1692, 1896)\n",
      "(1824, 1896)\n",
      "(970, 1896)\n",
      "(1656, 1896)\n",
      "(1872, 1896)\n",
      "{1: 6.985232807071035, 2: 2.2133731386113915, 4: 6.735943611725709, 6: 9.086122556124954, 8: 7.5929700531045015, 9: 1.725222274216191, 10: 10.0, 11: 4.688159995043362, 12: 7.3144086519413225, 13: 9.113487108666126, 17: 6.938741829292749, 19: 6.785495639300266, 21: 9.678360852998194, 22: 1.8742246693808604, 25: 5.740122187638081, 26: 5.795646637394244, 27: 1.0, 28: 6.951141575591168, 29: 5.312916443156008}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_2790731/1387230376.py:300: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)\n",
      "  w_train[i] = weights_dict[int(p_train[i])]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31578 samples, validate on 3527 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 04:57:53.723832: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_5/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31578/31578 [==============================] - ETA: 0s - loss: 8.6919\n",
      "Epoch 1: val_loss improved from inf to 1.36116, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 47s 1ms/sample - loss: 8.6919 - val_loss: 1.3612\n",
      "Epoch 2/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.6520\n",
      "Epoch 2: val_loss improved from 1.36116 to 1.33495, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.6520 - val_loss: 1.3349\n",
      "Epoch 3/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.6061\n",
      "Epoch 3: val_loss did not improve from 1.33495\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.6061 - val_loss: 1.3388\n",
      "Epoch 4/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5496\n",
      "Epoch 4: val_loss improved from 1.33495 to 1.33050, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.5496 - val_loss: 1.3305\n",
      "Epoch 5/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5152\n",
      "Epoch 5: val_loss did not improve from 1.33050\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.5152 - val_loss: 1.3371\n",
      "Epoch 6/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5142\n",
      "Epoch 6: val_loss did not improve from 1.33050\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.5142 - val_loss: 1.3352\n",
      "Epoch 7/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5034\n",
      "Epoch 7: val_loss did not improve from 1.33050\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.5034 - val_loss: 1.3328\n",
      "Epoch 8/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4572\n",
      "Epoch 8: val_loss did not improve from 1.33050\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.4572 - val_loss: 1.3441\n",
      "Epoch 9/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4771\n",
      "Epoch 9: val_loss improved from 1.33050 to 1.32303, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.4771 - val_loss: 1.3230\n",
      "Epoch 10/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4559\n",
      "Epoch 10: val_loss improved from 1.32303 to 1.32284, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.4559 - val_loss: 1.3228\n",
      "Epoch 11/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4342\n",
      "Epoch 11: val_loss did not improve from 1.32284\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.4342 - val_loss: 1.3279\n",
      "Epoch 12/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4244\n",
      "Epoch 12: val_loss did not improve from 1.32284\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.4244 - val_loss: 1.3352\n",
      "Epoch 13/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4349\n",
      "Epoch 13: val_loss did not improve from 1.32284\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.4349 - val_loss: 1.3328\n",
      "Epoch 14/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3873\n",
      "Epoch 14: val_loss improved from 1.32284 to 1.32264, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.3873 - val_loss: 1.3226\n",
      "Epoch 15/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4037\n",
      "Epoch 15: val_loss improved from 1.32264 to 1.32227, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.4037 - val_loss: 1.3223\n",
      "Epoch 16/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3959\n",
      "Epoch 16: val_loss improved from 1.32227 to 1.32158, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.3959 - val_loss: 1.3216\n",
      "Epoch 17/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3932\n",
      "Epoch 17: val_loss did not improve from 1.32158\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.3932 - val_loss: 1.3236\n",
      "Epoch 18/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3625\n",
      "Epoch 18: val_loss did not improve from 1.32158\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.3625 - val_loss: 1.3295\n",
      "Epoch 19/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3500\n",
      "Epoch 19: val_loss did not improve from 1.32158\n",
      "31578/31578 [==============================] - 36s 1ms/sample - loss: 8.3500 - val_loss: 1.3258\n",
      "Epoch 20/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3423\n",
      "Epoch 20: val_loss improved from 1.32158 to 1.31878, saving model to ./checkpoints/unknown_person_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 8.3423 - val_loss: 1.3188\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 05:09:49.318667: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_15_2/lstm_cell_89/bias/Assign' id:40467 op device:{requested: '', assigned: ''} def:{{{node lstm_15_2/lstm_cell_89/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_15_2/lstm_cell_89/bias, lstm_15_2/lstm_cell_89/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 05:09:53.191977: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_1_2/lstm_cell_75/bias/v/Assign' id:45318 op device:{requested: '', assigned: ''} def:{{{node lstm_1_2/lstm_cell_75/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_1_2/lstm_cell_75/bias/v, lstm_1_2/lstm_cell_75/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31578 samples, validate on 3527 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 05:10:00.967527: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 05:10:21.261093: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_6/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3478"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 05:10:59.239163: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_5/mul' id:44579 op device:{requested: '', assigned: ''} def:{{{node loss_5/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_5/mul/x, loss_5/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.32821, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 48s 2ms/sample - loss: 1.3478 - val_loss: 1.3282\n",
      "Epoch 2/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3454\n",
      "Epoch 2: val_loss did not improve from 1.32821\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3454 - val_loss: 1.3324\n",
      "Epoch 3/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3468\n",
      "Epoch 3: val_loss improved from 1.32821 to 1.32617, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3468 - val_loss: 1.3262\n",
      "Epoch 4/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3431\n",
      "Epoch 4: val_loss improved from 1.32617 to 1.32547, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3431 - val_loss: 1.3255\n",
      "Epoch 5/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3412\n",
      "Epoch 5: val_loss did not improve from 1.32547\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3412 - val_loss: 1.3277\n",
      "Epoch 6/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3433\n",
      "Epoch 6: val_loss improved from 1.32547 to 1.32405, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3433 - val_loss: 1.3240\n",
      "Epoch 7/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3403\n",
      "Epoch 7: val_loss did not improve from 1.32405\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3403 - val_loss: 1.3255\n",
      "Epoch 8/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3401\n",
      "Epoch 8: val_loss improved from 1.32405 to 1.32340, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3401 - val_loss: 1.3234\n",
      "Epoch 9/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3363\n",
      "Epoch 9: val_loss improved from 1.32340 to 1.32087, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3363 - val_loss: 1.3209\n",
      "Epoch 10/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3362\n",
      "Epoch 10: val_loss did not improve from 1.32087\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3362 - val_loss: 1.3223\n",
      "Epoch 11/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3362\n",
      "Epoch 11: val_loss did not improve from 1.32087\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3362 - val_loss: 1.3240\n",
      "Epoch 12/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3336\n",
      "Epoch 12: val_loss did not improve from 1.32087\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3336 - val_loss: 1.3238\n",
      "Epoch 13/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3349\n",
      "Epoch 13: val_loss improved from 1.32087 to 1.31697, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3349 - val_loss: 1.3170\n",
      "Epoch 14/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3327\n",
      "Epoch 14: val_loss did not improve from 1.31697\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3327 - val_loss: 1.3224\n",
      "Epoch 15/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3303\n",
      "Epoch 15: val_loss did not improve from 1.31697\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3303 - val_loss: 1.3222\n",
      "Epoch 16/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3307\n",
      "Epoch 16: val_loss did not improve from 1.31697\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3307 - val_loss: 1.3176\n",
      "Epoch 17/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3306\n",
      "Epoch 17: val_loss improved from 1.31697 to 1.31689, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3306 - val_loss: 1.3169\n",
      "Epoch 18/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3295\n",
      "Epoch 18: val_loss improved from 1.31689 to 1.31348, saving model to ./checkpoints/unknown_person_baseline_2_p5_20.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3295 - val_loss: 1.3135\n",
      "Epoch 19/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3293\n",
      "Epoch 19: val_loss did not improve from 1.31348\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3293 - val_loss: 1.3233\n",
      "Epoch 20/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3275\n",
      "Epoch 20: val_loss did not improve from 1.31348\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3275 - val_loss: 1.3172\n",
      "Train on 31578 samples, validate on 3527 samples\n",
      "Epoch 1/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3239\n",
      "Epoch 1: val_loss improved from inf to 1.31523, saving model to ./checkpoints/unknown_person_baseline_p5_21.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3239 - val_loss: 1.3152\n",
      "Epoch 2/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3227\n",
      "Epoch 2: val_loss did not improve from 1.31523\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3227 - val_loss: 1.3166\n",
      "Epoch 3/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3267\n",
      "Epoch 3: val_loss improved from 1.31523 to 1.31283, saving model to ./checkpoints/unknown_person_baseline_p5_21.h5\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3267 - val_loss: 1.3128\n",
      "Epoch 4/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3222\n",
      "Epoch 4: val_loss improved from 1.31283 to 1.31091, saving model to ./checkpoints/unknown_person_baseline_p5_21.h5\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3222 - val_loss: 1.3109\n",
      "Epoch 5/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3226\n",
      "Epoch 5: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3226 - val_loss: 1.3168\n",
      "Epoch 6/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3194\n",
      "Epoch 6: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3194 - val_loss: 1.3161\n",
      "Epoch 7/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3186\n",
      "Epoch 7: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3186 - val_loss: 1.3201\n",
      "Epoch 8/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3236\n",
      "Epoch 8: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3236 - val_loss: 1.3150\n",
      "Epoch 9/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3238\n",
      "Epoch 9: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3238 - val_loss: 1.3212\n",
      "Epoch 10/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3335\n",
      "Epoch 10: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3335 - val_loss: 1.3224\n",
      "Epoch 11/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3310\n",
      "Epoch 11: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3310 - val_loss: 1.3132\n",
      "Epoch 12/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3377\n",
      "Epoch 12: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3377 - val_loss: 1.3152\n",
      "Epoch 13/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3300\n",
      "Epoch 13: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3300 - val_loss: 1.3201\n",
      "Epoch 14/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3343\n",
      "Epoch 14: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3343 - val_loss: 1.3234\n",
      "Epoch 15/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3426\n",
      "Epoch 15: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3426 - val_loss: 1.3138\n",
      "Epoch 16/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3425\n",
      "Epoch 16: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3425 - val_loss: 1.3163\n",
      "Epoch 17/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3509\n",
      "Epoch 17: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3509 - val_loss: 1.3140\n",
      "Epoch 18/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3432\n",
      "Epoch 18: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3432 - val_loss: 1.3204\n",
      "Epoch 19/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3457\n",
      "Epoch 19: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3457 - val_loss: 1.3174\n",
      "Epoch 20/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3461\n",
      "Epoch 20: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3461 - val_loss: 1.3268\n",
      "Epoch 21/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3718\n",
      "Epoch 21: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3718 - val_loss: 1.3345\n",
      "Epoch 22/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.4534\n",
      "Epoch 22: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.4534 - val_loss: 1.3560\n",
      "Epoch 23/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3784\n",
      "Epoch 23: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3784 - val_loss: 1.3356\n",
      "Epoch 24/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3738\n",
      "Epoch 24: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3738 - val_loss: 1.3409\n",
      "Epoch 25/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3651\n",
      "Epoch 25: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3651 - val_loss: 1.3311\n",
      "Epoch 26/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3532\n",
      "Epoch 26: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3532 - val_loss: 1.3310\n",
      "Epoch 27/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3511\n",
      "Epoch 27: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3511 - val_loss: 1.3257\n",
      "Epoch 28/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3469\n",
      "Epoch 28: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3469 - val_loss: 1.3269\n",
      "Epoch 29/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3453\n",
      "Epoch 29: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3453 - val_loss: 1.3285\n",
      "Epoch 30/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3403\n",
      "Epoch 30: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3403 - val_loss: 1.3196\n",
      "Epoch 31/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3381\n",
      "Epoch 31: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3381 - val_loss: 1.3272\n",
      "Epoch 32/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3374\n",
      "Epoch 32: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3374 - val_loss: 1.3173\n",
      "Epoch 33/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3334\n",
      "Epoch 33: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3334 - val_loss: 1.3144\n",
      "Epoch 34/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3317\n",
      "Epoch 34: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 35s 1ms/sample - loss: 1.3317 - val_loss: 1.3164\n",
      "Epoch 35/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3330\n",
      "Epoch 35: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 34s 1ms/sample - loss: 1.3330 - val_loss: 1.3155\n",
      "Epoch 36/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3296\n",
      "Epoch 36: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3296 - val_loss: 1.3154\n",
      "Epoch 37/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3281\n",
      "Epoch 37: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 28s 894us/sample - loss: 1.3281 - val_loss: 1.3140\n",
      "Epoch 38/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3288\n",
      "Epoch 38: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 30s 950us/sample - loss: 1.3288 - val_loss: 1.3239\n",
      "Epoch 39/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3278\n",
      "Epoch 39: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3278 - val_loss: 1.3191\n",
      "Epoch 40/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3244\n",
      "Epoch 40: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3244 - val_loss: 1.3150\n",
      "Epoch 41/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3236\n",
      "Epoch 41: val_loss did not improve from 1.31091\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3236 - val_loss: 1.3119\n",
      "Epoch 42/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3224\n",
      "Epoch 42: val_loss improved from 1.31091 to 1.30926, saving model to ./checkpoints/unknown_person_baseline_p5_21.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3224 - val_loss: 1.3093\n",
      "Epoch 43/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3199\n",
      "Epoch 43: val_loss did not improve from 1.30926\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3199 - val_loss: 1.3113\n",
      "Epoch 44/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3197\n",
      "Epoch 44: val_loss improved from 1.30926 to 1.30639, saving model to ./checkpoints/unknown_person_baseline_p5_21.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3197 - val_loss: 1.3064\n",
      "Epoch 45/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3195\n",
      "Epoch 45: val_loss did not improve from 1.30639\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3195 - val_loss: 1.3086\n",
      "Epoch 46/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3170\n",
      "Epoch 46: val_loss did not improve from 1.30639\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3170 - val_loss: 1.3067\n",
      "Epoch 47/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3182\n",
      "Epoch 47: val_loss did not improve from 1.30639\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3182 - val_loss: 1.3180\n",
      "Epoch 48/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3153\n",
      "Epoch 48: val_loss did not improve from 1.30639\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3153 - val_loss: 1.3091\n",
      "Epoch 49/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3146\n",
      "Epoch 49: val_loss improved from 1.30639 to 1.30618, saving model to ./checkpoints/unknown_person_baseline_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3146 - val_loss: 1.3062\n",
      "Epoch 50/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3122\n",
      "Epoch 50: val_loss did not improve from 1.30618\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3122 - val_loss: 1.3074\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 05:49:45.067705: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_2_3/lstm_cell_113/recurrent_kernel/Assign' id:57738 op device:{requested: '', assigned: ''} def:{{{node lstm_2_3/lstm_cell_113/recurrent_kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_2_3/lstm_cell_113/recurrent_kernel, lstm_2_3/lstm_cell_113/recurrent_kernel/Initializer/mul_1)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 05:49:50.388602: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_13_3/lstm_cell_124/recurrent_kernel/v/Assign' id:64853 op device:{requested: '', assigned: ''} def:{{{node lstm_13_3/lstm_cell_124/recurrent_kernel/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_13_3/lstm_cell_124/recurrent_kernel/v, lstm_13_3/lstm_cell_124/recurrent_kernel/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 05:49:55.275575: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_3/cond/Merge' id:63349 op device:{requested: '', assigned: ''} def:{{{node dropout_4_3/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_3/cond/Identity, dropout_4_3/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1896)\n",
      "(1514, 1896)\n",
      "(1644, 1896)\n",
      "(1884, 1896)\n",
      "(1723, 1896)\n",
      "(1321, 1896)\n",
      "(1814, 1896)\n",
      "(1582, 1896)\n",
      "(1800, 1896)\n",
      "(1526, 1896)\n",
      "(1920, 1896)\n",
      "(1691, 1896)\n",
      "(1788, 1896)\n",
      "(1872, 1896)\n",
      "(1692, 1896)\n",
      "(1824, 1896)\n",
      "(970, 1896)\n",
      "(1656, 1896)\n",
      "(1872, 1896)\n",
      "{1: 6.742137880794816, 2: 2.34696982183226, 4: 7.266810562286924, 6: 9.68361637240041, 8: 8.046568141142135, 9: 2.0182980212868653, 10: 10.0, 11: 4.949485975632692, 12: 7.387330274905337, 13: 9.22939329820075, 17: 7.420734464915321, 19: 7.099973094945554, 21: 9.74161499814651, 22: 1.7176654797240123, 25: 5.87000063458026, 26: 5.560584181378544, 27: 1.0, 28: 6.9080786087014445, 29: 5.7372470185495565}\n",
      "Train on 31578 samples, validate on 3527 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 05:56:05.730509: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_7/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31578/31578 [==============================] - ETA: 0s - loss: 8.7569\n",
      "Epoch 1: val_loss improved from inf to 1.32254, saving model to ./checkpoints/unknown_person_p5_21.h5\n",
      "31578/31578 [==============================] - 49s 2ms/sample - loss: 8.7569 - val_loss: 1.3225\n",
      "Epoch 2/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.7162\n",
      "Epoch 2: val_loss did not improve from 1.32254\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.7162 - val_loss: 1.3338\n",
      "Epoch 3/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.6383\n",
      "Epoch 3: val_loss improved from 1.32254 to 1.31853, saving model to ./checkpoints/unknown_person_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.6383 - val_loss: 1.3185\n",
      "Epoch 4/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5929\n",
      "Epoch 4: val_loss improved from 1.31853 to 1.31618, saving model to ./checkpoints/unknown_person_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.5929 - val_loss: 1.3162\n",
      "Epoch 5/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5985\n",
      "Epoch 5: val_loss improved from 1.31618 to 1.31077, saving model to ./checkpoints/unknown_person_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.5985 - val_loss: 1.3108\n",
      "Epoch 6/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5339\n",
      "Epoch 6: val_loss did not improve from 1.31077\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.5339 - val_loss: 1.3113\n",
      "Epoch 7/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5417\n",
      "Epoch 7: val_loss did not improve from 1.31077\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.5417 - val_loss: 1.3215\n",
      "Epoch 8/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5366\n",
      "Epoch 8: val_loss did not improve from 1.31077\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.5366 - val_loss: 1.3194\n",
      "Epoch 9/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4889\n",
      "Epoch 9: val_loss did not improve from 1.31077\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.4889 - val_loss: 1.3198\n",
      "Epoch 10/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4608\n",
      "Epoch 10: val_loss improved from 1.31077 to 1.30639, saving model to ./checkpoints/unknown_person_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.4608 - val_loss: 1.3064\n",
      "Epoch 11/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4748\n",
      "Epoch 11: val_loss did not improve from 1.30639\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4748 - val_loss: 1.3157\n",
      "Epoch 12/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4600\n",
      "Epoch 12: val_loss did not improve from 1.30639\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4600 - val_loss: 1.3072\n",
      "Epoch 13/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4533\n",
      "Epoch 13: val_loss did not improve from 1.30639\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4533 - val_loss: 1.3070\n",
      "Epoch 14/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4516\n",
      "Epoch 14: val_loss improved from 1.30639 to 1.29586, saving model to ./checkpoints/unknown_person_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.4516 - val_loss: 1.2959\n",
      "Epoch 15/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4329\n",
      "Epoch 15: val_loss did not improve from 1.29586\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4329 - val_loss: 1.3092\n",
      "Epoch 16/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4245\n",
      "Epoch 16: val_loss did not improve from 1.29586\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4245 - val_loss: 1.3009\n",
      "Epoch 17/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4002\n",
      "Epoch 17: val_loss did not improve from 1.29586\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.4002 - val_loss: 1.2999\n",
      "Epoch 18/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3953\n",
      "Epoch 18: val_loss did not improve from 1.29586\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.3953 - val_loss: 1.3045\n",
      "Epoch 19/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3901\n",
      "Epoch 19: val_loss did not improve from 1.29586\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.3901 - val_loss: 1.3048\n",
      "Epoch 20/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3966\n",
      "Epoch 20: val_loss did not improve from 1.29586\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.3966 - val_loss: 1.3015\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 06:07:17.401473: W tensorflow/c/c_api.cc:304] Operation '{name:'dense_3_4/kernel/Assign' id:82799 op device:{requested: '', assigned: ''} def:{{{node dense_3_4/kernel/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](dense_3_4/kernel, dense_3_4/kernel/Initializer/random_uniform)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 06:07:24.098175: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_26_4/lstm_cell_174/bias/v/Assign' id:84451 op device:{requested: '', assigned: ''} def:{{{node lstm_26_4/lstm_cell_174/bias/v/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_26_4/lstm_cell_174/bias/v, lstm_26_4/lstm_cell_174/bias/v/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31578 samples, validate on 3527 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 06:07:34.895553: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 06:08:07.913403: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_8/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3149"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 06:08:42.134217: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_9/mul' id:83337 op device:{requested: '', assigned: ''} def:{{{node loss_9/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_9/mul/x, loss_9/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.31000, saving model to ./checkpoints/unknown_person_baseline_2_p5_21.h5\n",
      "31578/31578 [==============================] - 49s 2ms/sample - loss: 1.3149 - val_loss: 1.3100\n",
      "Epoch 2/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3135\n",
      "Epoch 2: val_loss improved from 1.31000 to 1.30608, saving model to ./checkpoints/unknown_person_baseline_2_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3135 - val_loss: 1.3061\n",
      "Epoch 3/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3107\n",
      "Epoch 3: val_loss did not improve from 1.30608\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3107 - val_loss: 1.3096\n",
      "Epoch 4/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3134\n",
      "Epoch 4: val_loss did not improve from 1.30608\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3134 - val_loss: 1.3131\n",
      "Epoch 5/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3091\n",
      "Epoch 5: val_loss improved from 1.30608 to 1.30558, saving model to ./checkpoints/unknown_person_baseline_2_p5_21.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3091 - val_loss: 1.3056\n",
      "Epoch 6/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3081\n",
      "Epoch 6: val_loss did not improve from 1.30558\n",
      "31578/31578 [==============================] - 31s 997us/sample - loss: 1.3081 - val_loss: 1.3062\n",
      "Epoch 7/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3060\n",
      "Epoch 7: val_loss did not improve from 1.30558\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3060 - val_loss: 1.3101\n",
      "Epoch 8/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3050\n",
      "Epoch 8: val_loss did not improve from 1.30558\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3050 - val_loss: 1.3066\n",
      "Epoch 9/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3039\n",
      "Epoch 9: val_loss improved from 1.30558 to 1.30089, saving model to ./checkpoints/unknown_person_baseline_2_p5_21.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3039 - val_loss: 1.3009\n",
      "Epoch 10/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3034\n",
      "Epoch 10: val_loss improved from 1.30089 to 1.29549, saving model to ./checkpoints/unknown_person_baseline_2_p5_21.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3034 - val_loss: 1.2955\n",
      "Epoch 11/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3025\n",
      "Epoch 11: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3025 - val_loss: 1.2960\n",
      "Epoch 12/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3016\n",
      "Epoch 12: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3016 - val_loss: 1.2989\n",
      "Epoch 13/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3012\n",
      "Epoch 13: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3012 - val_loss: 1.2998\n",
      "Epoch 14/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2963\n",
      "Epoch 14: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2963 - val_loss: 1.2986\n",
      "Epoch 15/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2965\n",
      "Epoch 15: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 31s 997us/sample - loss: 1.2965 - val_loss: 1.2978\n",
      "Epoch 16/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2948\n",
      "Epoch 16: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2948 - val_loss: 1.3029\n",
      "Epoch 17/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2921\n",
      "Epoch 17: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2921 - val_loss: 1.3011\n",
      "Epoch 18/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2935\n",
      "Epoch 18: val_loss did not improve from 1.29549\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2935 - val_loss: 1.2959\n",
      "Epoch 19/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2943\n",
      "Epoch 19: val_loss improved from 1.29549 to 1.29455, saving model to ./checkpoints/unknown_person_baseline_2_p5_21.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.2943 - val_loss: 1.2946\n",
      "Epoch 20/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2903\n",
      "Epoch 20: val_loss did not improve from 1.29455\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2903 - val_loss: 1.2970\n",
      "Train on 31578 samples, validate on 3527 samples\n",
      "Epoch 1/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2923\n",
      "Epoch 1: val_loss improved from inf to 1.29068, saving model to ./checkpoints/unknown_person_baseline_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2923 - val_loss: 1.2907\n",
      "Epoch 2/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2924\n",
      "Epoch 2: val_loss did not improve from 1.29068\n",
      "31578/31578 [==============================] - 32s 999us/sample - loss: 1.2924 - val_loss: 1.2950\n",
      "Epoch 3/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2871\n",
      "Epoch 3: val_loss improved from 1.29068 to 1.29011, saving model to ./checkpoints/unknown_person_baseline_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2871 - val_loss: 1.2901\n",
      "Epoch 4/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2867\n",
      "Epoch 4: val_loss improved from 1.29011 to 1.28805, saving model to ./checkpoints/unknown_person_baseline_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2867 - val_loss: 1.2880\n",
      "Epoch 5/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2856\n",
      "Epoch 5: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2856 - val_loss: 1.2884\n",
      "Epoch 6/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2826\n",
      "Epoch 6: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2826 - val_loss: 1.2918\n",
      "Epoch 7/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2825\n",
      "Epoch 7: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2825 - val_loss: 1.2908\n",
      "Epoch 8/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2893\n",
      "Epoch 8: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 31s 996us/sample - loss: 1.2893 - val_loss: 1.3009\n",
      "Epoch 9/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3204\n",
      "Epoch 9: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3204 - val_loss: 1.2992\n",
      "Epoch 10/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3079\n",
      "Epoch 10: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3079 - val_loss: 1.2979\n",
      "Epoch 11/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2990\n",
      "Epoch 11: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2990 - val_loss: 1.2986\n",
      "Epoch 12/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3051\n",
      "Epoch 12: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3051 - val_loss: 1.3057\n",
      "Epoch 13/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3065\n",
      "Epoch 13: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1000us/sample - loss: 1.3065 - val_loss: 1.3023\n",
      "Epoch 14/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3058\n",
      "Epoch 14: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3058 - val_loss: 1.3069\n",
      "Epoch 15/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3132\n",
      "Epoch 15: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3132 - val_loss: 1.3077\n",
      "Epoch 16/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3191\n",
      "Epoch 16: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3191 - val_loss: 1.3068\n",
      "Epoch 17/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3229\n",
      "Epoch 17: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3229 - val_loss: 1.3069\n",
      "Epoch 18/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3352\n",
      "Epoch 18: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3352 - val_loss: 1.3132\n",
      "Epoch 19/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3381\n",
      "Epoch 19: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3381 - val_loss: 1.3159\n",
      "Epoch 20/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3350\n",
      "Epoch 20: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3350 - val_loss: 1.3141\n",
      "Epoch 21/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3391\n",
      "Epoch 21: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3391 - val_loss: 1.3132\n",
      "Epoch 22/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3454\n",
      "Epoch 22: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3454 - val_loss: 1.3177\n",
      "Epoch 23/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3465\n",
      "Epoch 23: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3465 - val_loss: 1.3204\n",
      "Epoch 24/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3432\n",
      "Epoch 24: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3432 - val_loss: 1.3188\n",
      "Epoch 25/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3370\n",
      "Epoch 25: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 31s 988us/sample - loss: 1.3370 - val_loss: 1.3180\n",
      "Epoch 26/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3341\n",
      "Epoch 26: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3341 - val_loss: 1.3129\n",
      "Epoch 27/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3278\n",
      "Epoch 27: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 31s 996us/sample - loss: 1.3278 - val_loss: 1.3186\n",
      "Epoch 28/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3360\n",
      "Epoch 28: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3360 - val_loss: 1.3231\n",
      "Epoch 29/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3368\n",
      "Epoch 29: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3368 - val_loss: 1.3171\n",
      "Epoch 30/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3322\n",
      "Epoch 30: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3322 - val_loss: 1.3224\n",
      "Epoch 31/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3378\n",
      "Epoch 31: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3378 - val_loss: 1.3189\n",
      "Epoch 32/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3366\n",
      "Epoch 32: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3366 - val_loss: 1.3203\n",
      "Epoch 33/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3310\n",
      "Epoch 33: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3310 - val_loss: 1.3240\n",
      "Epoch 34/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3344\n",
      "Epoch 34: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3344 - val_loss: 1.3185\n",
      "Epoch 35/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3276\n",
      "Epoch 35: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3276 - val_loss: 1.3164\n",
      "Epoch 36/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3305\n",
      "Epoch 36: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3305 - val_loss: 1.3208\n",
      "Epoch 37/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3299\n",
      "Epoch 37: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 998us/sample - loss: 1.3299 - val_loss: 1.3223\n",
      "Epoch 38/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3310\n",
      "Epoch 38: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.3310 - val_loss: 1.3160\n",
      "Epoch 39/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3405\n",
      "Epoch 39: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3405 - val_loss: 1.3191\n",
      "Epoch 40/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3388\n",
      "Epoch 40: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3388 - val_loss: 1.3230\n",
      "Epoch 41/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3309\n",
      "Epoch 41: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3309 - val_loss: 1.3160\n",
      "Epoch 42/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3300\n",
      "Epoch 42: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3300 - val_loss: 1.3195\n",
      "Epoch 43/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3341\n",
      "Epoch 43: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3341 - val_loss: 1.3180\n",
      "Epoch 44/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3330\n",
      "Epoch 44: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3330 - val_loss: 1.3125\n",
      "Epoch 45/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3278\n",
      "Epoch 45: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3278 - val_loss: 1.3146\n",
      "Epoch 46/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3279\n",
      "Epoch 46: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3279 - val_loss: 1.3162\n",
      "Epoch 47/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3285\n",
      "Epoch 47: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3285 - val_loss: 1.3228\n",
      "Epoch 48/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3268\n",
      "Epoch 48: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3268 - val_loss: 1.3193\n",
      "Epoch 49/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3261\n",
      "Epoch 49: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3261 - val_loss: 1.3150\n",
      "Epoch 50/50\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.3260\n",
      "Epoch 50: val_loss did not improve from 1.28805\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.3260 - val_loss: 1.3142\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 06:45:51.478774: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_8_5/lstm_cell_193/bias/Assign' id:97465 op device:{requested: '', assigned: ''} def:{{{node lstm_8_5/lstm_cell_193/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_8_5/lstm_cell_193/bias, lstm_8_5/lstm_cell_193/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 06:45:59.311003: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_16_5/lstm_cell_201/bias/m/Assign' id:103018 op device:{requested: '', assigned: ''} def:{{{node lstm_16_5/lstm_cell_201/bias/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_16_5/lstm_cell_201/bias/m, lstm_16_5/lstm_cell_201/bias/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 06:46:06.890064: W tensorflow/c/c_api.cc:304] Operation '{name:'dropout_4_5/cond/Merge' id:102107 op device:{requested: '', assigned: ''} def:{{{node dropout_4_5/cond/Merge}} = Merge[N=2, T=DT_FLOAT, _has_manual_control_dependencies=true](dropout_4_5/cond/Identity, dropout_4_5/cond/dropout/SelectV2)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1485, 1896)\n",
      "(1514, 1896)\n",
      "(1644, 1896)\n",
      "(1884, 1896)\n",
      "(1723, 1896)\n",
      "(1321, 1896)\n",
      "(1814, 1896)\n",
      "(1582, 1896)\n",
      "(1800, 1896)\n",
      "(1526, 1896)\n",
      "(1920, 1896)\n",
      "(1691, 1896)\n",
      "(1788, 1896)\n",
      "(1872, 1896)\n",
      "(1692, 1896)\n",
      "(1824, 1896)\n",
      "(970, 1896)\n",
      "(1656, 1896)\n",
      "(1872, 1896)\n",
      "{1: 6.817824111273128, 2: 2.6997004814474614, 4: 7.432167735133331, 6: 9.414395569663414, 8: 8.190762363960998, 9: 2.3760069688022756, 10: 10.0, 11: 5.040148887582996, 12: 7.589299342434918, 13: 9.307249345192314, 17: 7.621310054181371, 19: 7.126008599520984, 21: 9.866817720634758, 22: 1.4285555449476481, 25: 5.973561602326413, 26: 5.787418619724106, 27: 1.0, 28: 6.695339643127588, 29: 5.3531445890084814}\n",
      "Train on 31578 samples, validate on 3527 samples\n",
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 06:52:26.026869: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_9/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31578/31578 [==============================] - ETA: 0s - loss: 8.7174\n",
      "Epoch 1: val_loss improved from inf to 1.36735, saving model to ./checkpoints/unknown_person_p5_22.h5\n",
      "31578/31578 [==============================] - 52s 2ms/sample - loss: 8.7174 - val_loss: 1.3674\n",
      "Epoch 2/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.6453\n",
      "Epoch 2: val_loss improved from 1.36735 to 1.31096, saving model to ./checkpoints/unknown_person_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.6453 - val_loss: 1.3110\n",
      "Epoch 3/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.6640\n",
      "Epoch 3: val_loss did not improve from 1.31096\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.6640 - val_loss: 1.3162\n",
      "Epoch 4/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5932\n",
      "Epoch 4: val_loss did not improve from 1.31096\n",
      "31578/31578 [==============================] - 31s 990us/sample - loss: 8.5932 - val_loss: 1.3228\n",
      "Epoch 5/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5598\n",
      "Epoch 5: val_loss improved from 1.31096 to 1.29308, saving model to ./checkpoints/unknown_person_p5_22.h5\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 8.5598 - val_loss: 1.2931\n",
      "Epoch 6/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5494\n",
      "Epoch 6: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.5494 - val_loss: 1.2931\n",
      "Epoch 7/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.5273\n",
      "Epoch 7: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.5273 - val_loss: 1.2975\n",
      "Epoch 8/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4831\n",
      "Epoch 8: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4831 - val_loss: 1.3016\n",
      "Epoch 9/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4835\n",
      "Epoch 9: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4835 - val_loss: 1.3057\n",
      "Epoch 10/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4667\n",
      "Epoch 10: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4667 - val_loss: 1.3006\n",
      "Epoch 11/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4388\n",
      "Epoch 11: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4388 - val_loss: 1.2935\n",
      "Epoch 12/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4341\n",
      "Epoch 12: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4341 - val_loss: 1.2987\n",
      "Epoch 13/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4194\n",
      "Epoch 13: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4194 - val_loss: 1.2955\n",
      "Epoch 14/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4158\n",
      "Epoch 14: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4158 - val_loss: 1.3103\n",
      "Epoch 15/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4076\n",
      "Epoch 15: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4076 - val_loss: 1.2983\n",
      "Epoch 16/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4285\n",
      "Epoch 16: val_loss did not improve from 1.29308\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4285 - val_loss: 1.2959\n",
      "Epoch 17/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.4025\n",
      "Epoch 17: val_loss improved from 1.29308 to 1.29215, saving model to ./checkpoints/unknown_person_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.4025 - val_loss: 1.2922\n",
      "Epoch 18/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3835\n",
      "Epoch 18: val_loss improved from 1.29215 to 1.28326, saving model to ./checkpoints/unknown_person_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.3835 - val_loss: 1.2833\n",
      "Epoch 19/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3849\n",
      "Epoch 19: val_loss did not improve from 1.28326\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.3849 - val_loss: 1.2971\n",
      "Epoch 20/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 8.3910\n",
      "Epoch 20: val_loss did not improve from 1.28326\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 8.3910 - val_loss: 1.2947\n",
      "WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_3 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_4 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_5 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_6 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_7 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_8 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_9 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_10 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_11 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_12 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_13 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_14 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_15 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_16 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_17 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_18 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_19 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_20 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_21 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_22 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_23 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_24 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_25 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_26 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_27 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_28 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_29 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_30 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_31 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_32 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_33 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_34 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_35 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n",
      "WARNING:tensorflow:Layer lstm_36 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 07:03:28.797415: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_26_6/lstm_cell_248/bias/Assign' id:119745 op device:{requested: '', assigned: ''} def:{{{node lstm_26_6/lstm_cell_248/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_26_6/lstm_cell_248/bias, lstm_26_6/lstm_cell_248/bias/Initializer/concat)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n",
      "2023-11-08 07:03:38.580686: W tensorflow/c/c_api.cc:304] Operation '{name:'lstm_8_6/lstm_cell_230/recurrent_kernel/m/Assign' id:122291 op device:{requested: '', assigned: ''} def:{{{node lstm_8_6/lstm_cell_230/recurrent_kernel/m/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](lstm_8_6/lstm_cell_230/recurrent_kernel/m, lstm_8_6/lstm_cell_230/recurrent_kernel/m/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train on 31578 samples, validate on 3527 samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 07:03:52.427505: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 07:04:37.253338: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape indropout_10/cond/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2835"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-11-08 07:05:11.248531: W tensorflow/c/c_api.cc:304] Operation '{name:'loss_13/mul' id:122095 op device:{requested: '', assigned: ''} def:{{{node loss_13/mul}} = Mul[T=DT_FLOAT, _has_manual_control_dependencies=true](loss_13/mul/x, loss_13/dense_3_loss/value)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1: val_loss improved from inf to 1.29049, saving model to ./checkpoints/unknown_person_baseline_2_p5_22.h5\n",
      "31578/31578 [==============================] - 52s 2ms/sample - loss: 1.2835 - val_loss: 1.2905\n",
      "Epoch 2/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2843\n",
      "Epoch 2: val_loss did not improve from 1.29049\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2843 - val_loss: 1.3011\n",
      "Epoch 3/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2930\n",
      "Epoch 3: val_loss did not improve from 1.29049\n",
      "31578/31578 [==============================] - 32s 998us/sample - loss: 1.2930 - val_loss: 1.2986\n",
      "Epoch 4/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2917\n",
      "Epoch 4: val_loss did not improve from 1.29049\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2917 - val_loss: 1.2983\n",
      "Epoch 5/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2862\n",
      "Epoch 5: val_loss did not improve from 1.29049\n",
      "31578/31578 [==============================] - 32s 999us/sample - loss: 1.2862 - val_loss: 1.2947\n",
      "Epoch 6/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2838\n",
      "Epoch 6: val_loss improved from 1.29049 to 1.29035, saving model to ./checkpoints/unknown_person_baseline_2_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2838 - val_loss: 1.2903\n",
      "Epoch 7/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2828\n",
      "Epoch 7: val_loss improved from 1.29035 to 1.28595, saving model to ./checkpoints/unknown_person_baseline_2_p5_22.h5\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2828 - val_loss: 1.2859\n",
      "Epoch 8/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2814\n",
      "Epoch 8: val_loss did not improve from 1.28595\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2814 - val_loss: 1.2965\n",
      "Epoch 9/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2799\n",
      "Epoch 9: val_loss did not improve from 1.28595\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2799 - val_loss: 1.2896\n",
      "Epoch 10/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2820\n",
      "Epoch 10: val_loss did not improve from 1.28595\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2820 - val_loss: 1.2892\n",
      "Epoch 11/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2816\n",
      "Epoch 11: val_loss did not improve from 1.28595\n",
      "31578/31578 [==============================] - 31s 993us/sample - loss: 1.2816 - val_loss: 1.2875\n",
      "Epoch 12/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2782\n",
      "Epoch 12: val_loss did not improve from 1.28595\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2782 - val_loss: 1.2954\n",
      "Epoch 13/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2785\n",
      "Epoch 13: val_loss did not improve from 1.28595\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2785 - val_loss: 1.3036\n",
      "Epoch 14/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2777\n",
      "Epoch 14: val_loss did not improve from 1.28595\n",
      "31578/31578 [==============================] - 31s 989us/sample - loss: 1.2777 - val_loss: 1.2982\n",
      "Epoch 15/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2786\n",
      "Epoch 15: val_loss improved from 1.28595 to 1.28456, saving model to ./checkpoints/unknown_person_baseline_2_p5_22.h5\n",
      "31578/31578 [==============================] - 31s 997us/sample - loss: 1.2786 - val_loss: 1.2846\n",
      "Epoch 16/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2782\n",
      "Epoch 16: val_loss did not improve from 1.28456\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2782 - val_loss: 1.2902\n",
      "Epoch 17/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2784\n",
      "Epoch 17: val_loss did not improve from 1.28456\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2784 - val_loss: 1.2907\n",
      "Epoch 18/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2753\n",
      "Epoch 18: val_loss did not improve from 1.28456\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2753 - val_loss: 1.2896\n",
      "Epoch 19/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2752\n",
      "Epoch 19: val_loss did not improve from 1.28456\n",
      "31578/31578 [==============================] - 32s 1ms/sample - loss: 1.2752 - val_loss: 1.2891\n",
      "Epoch 20/20\n",
      "31578/31578 [==============================] - ETA: 0s - loss: 1.2723\n",
      "Epoch 20: val_loss did not improve from 1.28456\n",
      "31578/31578 [==============================] - 33s 1ms/sample - loss: 1.2723 - val_loss: 1.2891\n"
     ]
    }
   ],
   "source": [
    "person_nums = [1,2,4,5,6,8,9,10,11,12,13,17,19,21,22,25,26,27,28,29]\n",
    "## Build the baseline model for emotion recognition with dropout layers\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, SimpleRNN, LSTM, Conv2D, Flatten, MaxPooling2D, GRU, AveragePooling2D, Dropout, Lambda\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "def individual_model(features_list):\n",
    "    input_layers = []\n",
    "    hidden_layers = []\n",
    "    combined_feature = np.empty((len(features_list[0]),0))\n",
    "    for i, feature in enumerate(features_list):\n",
    "        \n",
    "        if len(feature.shape) == 3:\n",
    "            input_i = Input(shape=(feature.shape[1], feature.shape[2]))\n",
    "            input_layers.append(input_i)\n",
    "\n",
    "            hidden_i = input_i[:,:,:,None]\n",
    "            hidden_i = Conv2D(32, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(16, 3, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((3, 3))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(8, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Conv2D(4, 1, activation='relu')(hidden_i)\n",
    "            hidden_i = AveragePooling2D((2, 2))(hidden_i)\n",
    "            hidden_i = Dropout(0.5)(hidden_i)\n",
    "            hidden_i = Flatten()(hidden_i)\n",
    "\n",
    "            hidden_layers.append(hidden_i)\n",
    "        elif feature.shape[1] <20:\n",
    "            combined_feature = np.hstack((combined_feature, feature))\n",
    "            \n",
    "        else:  # For series features\n",
    "            input_i = Input(shape=(feature.shape[1],))\n",
    "            input_layers.append(input_i)\n",
    "            hidden_i = Lambda(lambda x: x[:, :, None])(input_i)  # Add a new dimension\n",
    "            hidden_i = LSTM(4)(hidden_i)\n",
    "            hidden_layers.append(hidden_i)\n",
    "    input_i = Input(shape=(combined_feature.shape[1],))\n",
    "    input_layers.append(input_i)\n",
    "    dense_num = np.max((1, int(combined_feature.shape[1]/2)))\n",
    "    hidden_i = Dense(dense_num, activation='relu')(input_i)\n",
    "    hidden_layers.append(hidden_i)\n",
    "    print(combined_feature.shape)\n",
    "    concat_layer = concatenate(hidden_layers)\n",
    "    h = Dropout(0.2)(concat_layer)\n",
    "    h = Dense(64, activation='relu')(h)\n",
    "    h = Dense(32, activation='relu')(h)\n",
    "    output_layer = Dense(2)(h)\n",
    "    model = Model(inputs=input_layers, outputs=output_layer)\n",
    "    model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "    return model\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.callbacks import Callback\n",
    "import numpy as np\n",
    "\n",
    "class PruningCallback(tf.keras.callbacks.Callback):\n",
    "    def __init__(self, initial_pruning_factor=0.1, final_pruning_factor=0.5, start_epoch=0, end_epoch=None, frequency=1):\n",
    "        super(PruningCallback, self).__init__()\n",
    "        self.initial_pruning_factor = initial_pruning_factor\n",
    "        self.final_pruning_factor = final_pruning_factor\n",
    "        self.start_epoch = start_epoch\n",
    "        self.end_epoch = end_epoch if end_epoch is not None else np.inf\n",
    "        self.frequency = frequency\n",
    "        self.pruned_weights = {}\n",
    "        self.layer_importance = {}\n",
    "\n",
    "    def get_pruning_factor(self, epoch):\n",
    "        if epoch < self.start_epoch:\n",
    "            return 0\n",
    "        if epoch > self.end_epoch:\n",
    "            return self.final_pruning_factor\n",
    "        return self.initial_pruning_factor + (self.final_pruning_factor - self.initial_pruning_factor) * (epoch - self.start_epoch) / (self.end_epoch - self.start_epoch)\n",
    "\n",
    "    def on_train_begin(self, logs=None):\n",
    "        total_weight_magnitude = 0\n",
    "        for layer in self.model.layers:\n",
    "            if hasattr(layer, 'get_weights'):\n",
    "                weights = layer.get_weights()\n",
    "                layer_norm = sum(np.linalg.norm(w) for w in weights)\n",
    "                total_weight_magnitude += layer_norm\n",
    "                self.layer_importance[layer.name] = layer_norm\n",
    "    \n",
    "        # Normalize the layer importance values so they sum up to 1\n",
    "        for layer_name in self.layer_importance:\n",
    "            self.layer_importance[layer_name] /= total_weight_magnitude\n",
    "    # def on_train_begin(self, logs=None):\n",
    "    #     total_weight_magnitude = sum([np.linalg.norm(layer.get_weights()) for layer in self.model.layers if hasattr(layer, 'get_weights')])\n",
    "    #     for layer in self.model.layers:\n",
    "    #         if hasattr(layer, 'get_weights'):\n",
    "    #             self.layer_importance[layer.name] = np.linalg.norm(layer.get_weights()) / total_weight_magnitude\n",
    "\n",
    "    def get_layer_pruning_factor(self, layer_name, global_pruning_factor):\n",
    "        if layer_name in self.layer_importance:\n",
    "            importance = self.layer_importance[layer_name]\n",
    "            adjusted_pruning_factor = global_pruning_factor * (1 - importance)\n",
    "            return min(adjusted_pruning_factor, 1)  # Ensure the pruning factor is not greater than 1\n",
    "        return global_pruning_factor\n",
    "    def prune_weights(self, layer, global_pruning_factor):\n",
    "        \n",
    "        weights = layer.get_weights()\n",
    "        layer_name = layer.name\n",
    "        pruning_factor = self.get_layer_pruning_factor(layer_name, global_pruning_factor)\n",
    "\n",
    "        if layer_name not in self.pruned_weights:\n",
    "            self.pruned_weights[layer_name] = [np.zeros_like(w, dtype=bool) for w in weights]\n",
    "        \n",
    "        for i in range(len(weights)):\n",
    "            weight = weights[i]\n",
    "            # print(weight.shape)\n",
    "            # print(weight.size)\n",
    "            if weight.ndim > 1:  # Only prune dense or convolutional layers\n",
    "                unpruned_weights = np.logical_not(self.pruned_weights[layer_name][i])\n",
    "                num_unpruned = np.sum(unpruned_weights)\n",
    "                num_pruning = min(num_unpruned, int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i]))\n",
    "                num_pruning = int(weight.size * pruning_factor) - np.sum(self.pruned_weights[layer_name][i])\n",
    "                if num_pruning > 0:\n",
    "                    unpruned_flat_indices = np.flatnonzero(unpruned_weights)\n",
    "                    abs_unpruned_weights = np.abs(weight[unpruned_weights])\n",
    "                    pruning_flat_indices = np.argpartition(abs_unpruned_weights, num_pruning)[:num_pruning]\n",
    "                    \n",
    "                    indices = np.unravel_index(pruning_flat_indices, weight.shape)\n",
    "                    self.pruned_weights[layer_name][i][indices] = True\n",
    "\n",
    "                weights[i] = weights[i]*(~self.pruned_weights[layer_name][i])\n",
    "                \n",
    "        layer.set_weights(weights)\n",
    "\n",
    "    def on_epoch_end(self, epoch, logs=None):\n",
    "        if (epoch - self.start_epoch) % self.frequency != 0:\n",
    "            return\n",
    "\n",
    "        pruning_factor = self.get_pruning_factor(epoch)\n",
    "        for layer in self.model.layers:\n",
    "            if isinstance(layer, (tf.keras.layers.Dense, tf.keras.layers.Conv2D)):\n",
    "                self.prune_weights(layer, pruning_factor)\n",
    "from feature_emotion import feature_extract, split_data, label_unique_tuples, split_data_unknown\n",
    "gts, sensor_nums, walk_nums, trace_nums, people_nums, spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features = feature_extract(person_nums)\n",
    "\n",
    "walk_nums_all = np.squeeze(walk_nums)\n",
    "trace_nums_all = np.squeeze(trace_nums)\n",
    "people_nums_all = np.squeeze(people_nums)\n",
    "\n",
    "## 0: train, 1: validation 2: test\n",
    "\n",
    "test_person_id = [5]\n",
    "flag_tr_val_te = split_data_unknown(test_person_id, walk_nums_all, trace_nums_all, people_nums_all, person_nums, rand_seed = 42)\n",
    "## Data Normalization before training ans testing\n",
    "import tensorflow as tf\n",
    "tf.compat.v1.disable_v2_behavior()\n",
    "from tensorflow.keras.models import Model\n",
    "from tensorflow.keras.layers import Input, Dense, concatenate, LSTM\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "scalers = []\n",
    "X_train_normalized = []\n",
    "X_val_normalized = []\n",
    "X_test_normalized = []\n",
    "train_idx = np.where(flag_tr_val_te ==0)[0]\n",
    "np.random.shuffle(train_idx)\n",
    "val_idx = np.where(flag_tr_val_te ==1)[0]\n",
    "test_idx = np.where(flag_tr_val_te ==2)[0]\n",
    "\n",
    "for i, feature in enumerate([spe_centr, delta_spe_centr, spe_crest, delta_spe_crest, spe_decrease, delta_spe_decrease, spe_entropy, delta_spe_entropy, spe_flatness, delta_spe_flatness, spe_flux, delta_spe_flux, spe_kurtosis, delta_spe_kurtosis, spe_skewness, delta_spe_skewness, spe_rfp, delta_spe_rfp, spe_slope, delta_spe_slope, spe_spread, delta_spe_spread, wlk_fre, wlk_fres_trace, cwt_figs_all, cwt_sum_all_0, cwt_sum_all_1, cwt_sum_all_2, cwt_sum_all_3, high_fre_compos, pitchs, low_fre_compos, auto_corrs, real_hils, imag_hils, dur_time_1_alls, dur_time_2_alls, jitters, shimmers, jitter_rap, hrs, feature, slope, zcrs, fft_features, energy_alls, log_energy_alls, smoothe_energy_alls, legendres, double_support_time, pdps_new, lpcs, ceps_features]):\n",
    "    scaler = StandardScaler()\n",
    "    if len(feature.shape)==2:\n",
    "        X_train_i = feature[train_idx,:]\n",
    "        X_val_i = feature[val_idx,:]\n",
    "        X_test_i = feature[test_idx,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i)\n",
    "        scalers.append(scaler)\n",
    "    else:\n",
    "        X_train_i = feature[train_idx,:,:]\n",
    "        X_val_i = feature[val_idx,:,:]\n",
    "        X_test_i = feature[test_idx,:,:]\n",
    "        X_train_normalized_i = scaler.fit_transform(X_train_i.reshape(X_train_i.shape[0], -1)).reshape(X_train_i.shape)\n",
    "        X_val_normalized_i = scaler.transform(X_val_i.reshape(X_val_i.shape[0], -1)).reshape(X_val_i.shape)\n",
    "        X_test_normalized_i = scaler.transform(X_test_i.reshape(X_test_i.shape[0], -1)).reshape(X_test_i.shape)\n",
    "        scalers.append(scaler)\n",
    "    X_train_normalized.append(X_train_normalized_i)\n",
    "    X_val_normalized.append(X_val_normalized_i)\n",
    "    X_test_normalized.append(X_test_normalized_i)\n",
    "y_train = gts[train_idx,:]\n",
    "y_val = gts[val_idx,:]\n",
    "y_test = gts[test_idx,:]\n",
    "X_train_normalized_new = []\n",
    "combined_feature = np.empty((len(X_train_normalized[0]),0))\n",
    "for feature in X_train_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_train_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_train_normalized_new.append(feature)\n",
    "X_train_normalized_new.append(combined_feature)\n",
    "\n",
    "X_val_normalized_new = []\n",
    "combined_feature = np.empty((len(X_val_normalized[0]),0))\n",
    "for feature in X_val_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_val_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_val_normalized_new.append(feature)\n",
    "X_val_normalized_new.append(combined_feature)\n",
    "\n",
    "X_test_normalized_new = []\n",
    "combined_feature = np.empty((len(X_test_normalized[0]),0))\n",
    "for feature in X_test_normalized:\n",
    "    if len(feature.shape) == 3:\n",
    "        X_test_normalized_new.append(feature)\n",
    "    elif feature.shape[1] <20:\n",
    "        combined_feature = np.hstack((combined_feature, feature))\n",
    "    else:\n",
    "        X_test_normalized_new.append(feature)\n",
    "X_test_normalized_new.append(combined_feature)\n",
    "\n",
    "model = individual_model(X_train_normalized)\n",
    "model.compile(loss='mean_absolute_error', optimizer='adam')\n",
    "num_epochs = 50\n",
    "\n",
    "\n",
    "# Gradually prune weights in dense and convolutional layers from 10% to 50% over the course of training, starting from epoch 0.\n",
    "\n",
    "\n",
    "rates = [0.4, 0.5, 0.6]\n",
    "idx = 20\n",
    "for r in rates:\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=0.01, final_pruning_factor=r, start_epoch=5, end_epoch=20, frequency=1)\n",
    "    model.fit(X_train_normalized_new, y_train, epochs=num_epochs, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import tensorflow as tf\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    from tensorflow.keras.models import Model\n",
    "    layers = model.layers\n",
    "    second_last_layer_output = layers[-4].output\n",
    "    feature_extractor_model = Model(inputs=model.input, outputs=second_last_layer_output)\n",
    "    train_features = feature_extractor_model.predict(X_train_normalized_new)\n",
    "    test_features = feature_extractor_model.predict(X_test_normalized_new)\n",
    "    \n",
    "    p_train = people_nums[train_idx,:]\n",
    "    p_val = people_nums[val_idx,:]\n",
    "    p_test = people_nums[test_idx,:]\n",
    "    ## Calculate the distance between test person and training person\n",
    "    def euclidean_distance(a, b):\n",
    "        return np.sqrt(np.sum((a - b) ** 2, axis=1))\n",
    "    \n",
    "    distance_dict = {}\n",
    "    for ii in range(len(person_nums)):\n",
    "        if person_nums[ii] == test_person_id[0]:\n",
    "            continue\n",
    "        else:\n",
    "            \n",
    "            ind = np.where(p_train ==person_nums[ii])[0]\n",
    "            tmp_train_features = train_features[ind, :]\n",
    "            distances = np.array([euclidean_distance(train_sample, test_features) for train_sample in tmp_train_features])\n",
    "            print(distances.shape)\n",
    "            average_distances = np.mean(distances, axis=1)\n",
    "    \n",
    "            # Step 4: Find the overall average distance\n",
    "            overall_average_distance = np.mean(average_distances)\n",
    "            distance_dict[person_nums[ii]] = overall_average_distance\n",
    "    \n",
    "    \n",
    "    def normalize_to_weights(distance_dict):\n",
    "        distances = np.array(list(distance_dict.values()))\n",
    "        # Handle the case where a distance is zero to avoid division by zero\n",
    "        distances = np.clip(distances, a_min=1e-10, a_max=None)\n",
    "        weights = 1 / distances\n",
    "        normalized_weights = weights\n",
    "        # normalized_weights = weights / sum(weights)\n",
    "        # print(sum(weights))\n",
    "        # print(sum(normalized_weights))\n",
    "        # Assign the normalized weights back to the dictionary\n",
    "        normalized_weight_dict = dict(zip(distance_dict.keys(), normalized_weights))\n",
    "        return normalized_weight_dict\n",
    "    def scale_dict_values(my_dict):\n",
    "        scaled_dict = my_dict.copy()\n",
    "        min_val = min(scaled_dict.values())\n",
    "        max_val = max(scaled_dict.values())\n",
    "        \n",
    "        for key in scaled_dict:\n",
    "            scaled_dict[key] = 1 + 9 * (scaled_dict[key] - min_val) / (max_val - min_val)\n",
    "        \n",
    "        return scaled_dict\n",
    "    weights_dict = normalize_to_weights(distance_dict)\n",
    "    weights_dict = scale_dict_values(weights_dict)\n",
    "    print(weights_dict)\n",
    "    \n",
    "    w_train = np.zeros_like(p_train)\n",
    "    for i in range(len(w_train)):\n",
    "        w_train[i] = weights_dict[int(p_train[i])]\n",
    "    \n",
    "    w_train = np.squeeze(w_train)\n",
    "    \n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,sample_weight= w_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])\n",
    "    import sys\n",
    "    sys.path.append('..')\n",
    "    # for layer in model.layers[-4:]:\n",
    "    #     layer.trainable = False\n",
    "    # model = individual_model.individual_model(X_train_normalized)\n",
    "    model_name = './checkpoints/unknown_person_baseline_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    model = tf.keras.models.load_model(model_name)\n",
    "    model_name = './checkpoints/unknown_person_baseline_2_p'+str(test_person_id[0])+'_'+str(idx)+'.h5'\n",
    "    idx += 1\n",
    "    checkpoint = ModelCheckpoint(model_name, monitor='val_loss', mode='min', save_best_only=True, verbose=1)\n",
    "    pruning_callback = PruningCallback(initial_pruning_factor=r, final_pruning_factor=r, start_epoch=1, end_epoch=20, frequency=1)\n",
    "    \n",
    "    history = model.fit(x=X_train_normalized_new, y=y_train,epochs=20, batch_size=1024, validation_data=(X_val_normalized_new, y_val), callbacks=[pruning_callback, checkpoint])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f71b59e4-6581-4ea8-994d-a02a6654ab6b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
